### ISSUE TITLE
Undefined variable: g:mucomplete#can_complete

### ISSUE THREAD

**Issue by sunaku** [lifepillar/vim-mucomplete#1]
Using NeoVim 0.1.5, in a brand new buffer, typing "hello" and then pressing TAB causes this error: :bomb:

```
Error detected while processing function mucomplete#complete[7]..<SNR>370_complete[5]..mucomplete#complete_chain:
line    5:
E121: Undefined variable: g:mucomplete#can_complete
Press ENTER or type command to continue
```

**Comment by lifepillar** [comment]
MUcomplete currently requires Vim compiled with `+lambda` and NeoVim does not have lambdas yet. I will fix this.

**Comment by tjharman** [comment]
This means that older versions of vim don't work either
For example the 7.4 vim that's included in Debian 8.6 won't work:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:03)
Included patches: 1-488, 576

tim@animal ~> vim --version | grep lambda
tim@animal ~>

It might pay to update the Readme to clearly state that vim8 is a requirement.

**Comment by calebeby** [comment]
Is there a way to use this plugin with neovim?

**Comment by tjharman** [comment]
No, it doesn't support +lambda

**Comment by lifepillar** [comment]
Older Vim and NeoVim are now supported. Fixed by https://github.com/lifepillar/vim-mucomplete/commit/42b12a975c9ed5834e50e72ae7bc7511908dd820.
