### ISSUE TITLE
Select first entry with auto_at_startup enabled?

### ISSUE THREAD

**Issue by for-coursera** [lifepillar/vim-mucomplete#10]
Is it possible to add an option to select the first entry in the suggestion list if the variable `g:mucomplete#enable_auto_at_startup` is set to `1`?

**Comment by lifepillar** [comment]
Yes, it would be possible. Actually, I had implemented it, but I didn't like it, because most of the time the first choice was not what I wanted. But if you think it would make a worth addition, I may step back.

For now, you may try and set `menu+=longest`.

**Comment by for-coursera** [comment]
> For now, you may try and set menu+=longest.

You mean `:set wildmode+=longest`? If so, that doesn't seem to work (and I don't think it should, as I understand from the help). Nonetheless, it's definitely not an urgent matter, I really can wait :).

As per being a worth addition... Well, tastes differ, I'm sure :). Thus, an option would be an ideal choice.

**Comment by lifepillar** [comment]
Ops, sorry, I meant `completeopt+=longest`.

**Comment by for-coursera** [comment]
Oh, I see. Well, this behaviour a bit differs, I think: it inserts but doesn't select. While I personally would like something like the opposite: select but do not insert (insert only on pressing a confirming key, usually Enter).

Sorry, wasn't clear enough from the very beginning (and now I think this may be not compatible with the mucomplete's modus operandi...)

**Comment by lifepillar** [comment]
Do you mean, like this?

![mucomplete auto select feature request](https://raw.github.com/lifepillar/Resources/master/issues/mucomplete-issue-10.png)

**Comment by for-coursera** [comment]
Yes, exactly.

**Comment by lifepillar** [comment]
Could you try the `auto-select` branch? I have added an option `g:mucomplete#auto_select` which, when set to `1`, should do what you want.

**Comment by for-coursera** [comment]
Well... For me, it has stopped displaying menu at all :).

    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 15 2016 16:30:52)
    MacOS X (unix) version
    Included patches: 1-33
    Compiled by Homebrew
    Huge version without GUI.  Features included (+) or not (-):
    +acl             +dialog_con      +job             +mouse_sgr       +rightleft       +user_commands
    +arabic          +diff            +jumplist        -mouse_sysmouse  +ruby            +vertsplit
    +autocmd         +digraphs        +keymap          +mouse_urxvt     +scrollbind      +virtualedit
    -balloon_eval    -dnd             +lambda          +mouse_xterm     +signs           +visual
    -browse          -ebcdic          +langmap         +multi_byte      +smartindent     +visualextra
    ++builtin_terms  +emacs_tags      +libcall         +multi_lang      +startuptime     +viminfo
    +byte_offset     +eval            +linebreak       -mzscheme        +statusline      +vreplace
    +channel         +ex_extra        +lispindent      +netbeans_intg   -sun_workshop    +wildignore
    +cindent         +extra_search    +listcmds        +num64           +syntax          +wildmenu
    -clientserver    +farsi           +localmap        +packages        +tag_binary      +windows
    +clipboard       +file_in_path    +lua             +path_extra      +tag_old_static  +writebackup
    +cmdline_compl   +find_in_path    +menu            +perl            -tag_any_white   -X11
    +cmdline_hist    +float           +mksession       +persistent_undo -tcl             -xfontset
    +cmdline_info    +folding         +modify_fname    +postscript      +termguicolors   -xim
    +comments        -footer          +mouse           +printer         +terminfo        -xpm
    +conceal         +fork()          -mouseshape      +profile         +termresponse    -xsmp
    +cryptv          -gettext         +mouse_dec       +python          +textobjects     -xterm_clipboard
    +cscope          -hangul_input    -mouse_gpm       -python3         +timers          -xterm_save
    +cursorbind      +iconv           -mouse_jsbterm   +quickfix        +title
    +cursorshape     +insert_expand   +mouse_netterm   +reltime         -toolbar
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
      fall-back for $VIM: "/usr/local/share/vim"
    Compilation:
    clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: clang   -L.     -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua
    -fstack-protector -L/usr/local/lib  -L/System/Library/Perl/5.12/darwin-thread-multi-2level/CORE -lperl -lm -lutil -
    lc -framework Python   -lruby -lobjc

**Comment by for-coursera** [comment]
Huh? Doesn't work.

**Comment by lifepillar** [comment]
Can you please elaborate?

**Comment by for-coursera** [comment]
> For me, after adding let g:mucomplete#auto_select = 1 to .vimrc, it has stopped displaying the completion menu at all :)

**Comment by lifepillar** [comment]
Are you sure you are using the current master or are you still on the auto-select branch (which I have deleted)?

**Comment by for-coursera** [comment]
Have just switched to the main branch before commenting. Same situation: after setting `g:mucomplete#auto_select` to `1` I see no menus.

**Comment by lifepillar** [comment]
Even after `:MUcompleteAutoOn`? That's strange. Can you please provide the µcomplete settings from your `vimrc`? Also, that is the filetype of your buffer?

**Comment by for-coursera** [comment]
> Even after :MUcompleteAutoOn?

Yep.

> Can you please provide the µcomplete settings from your vimrc? 

    if &runtimepath =~ 'mucomplete'
        let g:mucomplete#no_mappings = 1
        let g:mucomplete#enable_auto_at_startup = 1
        let g:mucomplete#auto_select = 1
    endif

> Also, what is the filetype of your buffer?

Let it be `Vim`.

**Comment by lifepillar** [comment]
I cannot reproduce your problem with a minimal `vimrc` with your settings:

```
set nocompatible
filetype on
filetype plugin on
filetype indent on
syntax on

let g:mucomplete#no_mappings = 1
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#auto_select = 1
```

Do you still see no menu if you run `vim -u vimrc_above`?

**Comment by lifepillar** [comment]
It might be a conflict with another plugin…

**Comment by for-coursera** [comment]
OK, you are probably right, that's a problem with some other setting. Thanks for your support, I'll try to investigate that (and may be come back later).

Once again, thanks for your time.

**Comment by lifepillar** [comment]
Feel free to open a new issue if you need to provide more feedback.
