### ISSUE TITLE
<c-e> map error

### ISSUE THREAD

**Issue by Asheq** [lifepillar/vim-mucomplete#100]
I'm receiving these errors when starting insert mode for the first time:

```
[MUcomplete] <c-e> is already mapped. Use :verbose imap <c-e> to see where it is mapped.
[MUcomplete] NOTE: since v1.0.0, you do not need to map <c-e> in your vimrc any longer.
```

`verbose imap <C-e>` gives me

```
i  <C-E>       * col('.')>strlen(getline('.'))||pumvisible()?"\<C-E>":"\<End>"
	Last set from ~/.vim/plugged/vim-rsi/plugin/rsi.vim
```
I have Tim Pope's popular [RSI plugin](https://github.com/tpope/vim-rsi) installed. Any idea what I should do?

PS: I love the plugin! It was hard to find a completion plugin that I liked but I like this one.

**Comment by lifepillar** [comment]
I copy the answer from the other thread:

> Vim-rsi maps `<c-e>` in Insert mode (and MUcomplete too). To get rid of MUcomplete's warning, you may add these lines to your `vimrc`:
> 
> ```vim
> let g:mucomplete#no_popup_mappings = 1
> imap <c-y> <plug>(MUcompletePopupAccept)
> imap <cr> <plug>(MUcompleteCR)
> ```
> 
> The first line wil prevent MUcomplete from mapping `<c-e>`, `<c-y>` and `<cr>`. The other two lines recover the functionality of `<c-y>` and `<cr>`. With this setup, MUcomplete will work as usual, except that you will have to press `<c-e>` twice to cancel a pop-up menu.
> 
> Unfortunately, vim-rsi does not use plugs and does not check whether a mapping is already defined. Instead, it silently overrides an existing mapping. Maybe, that should be reported to vim-rsi's repo.
> 
> 
>
