### ISSUE TITLE
can show  the pop-up menu when i input "."(omni-complete)?

### ISSUE THREAD

**Issue by wining** [lifepillar/vim-mucomplete#102]

**Comment by lifepillar** [comment]
You need to tweak the value of `g:mucomplete#can_complete`, which determines when completion should be tried. For example, for Go, you may put this in your `vimrc`:

```vim
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.go = { 'omni': { t -> t =~# '\m\k\%(\k\|\.\)$' } }
```

This will enable omni-completion after two keyword characters or after a keyword character followed by a dot. You may use any regexp, of course. In the snippet above, `t` represents the text before the cursor.

If you want to apply the same pattern for all file types, you may use this instead:

```vim
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.default = { 'omni': { t -> t =~# '\m\k\%(\k\|\.\)$' } }
```

See `:help g:mucomplete#can_complete` for further examples.
