### ISSUE TITLE
new window open when complete popup

### ISSUE THREAD

**Issue by trlsmax** [lifepillar/vim-mucomplete#103]
I use mucomplete with nvim. When the complete menu popup and select, a new window opened on top, saying filename, cmd, kind, name and others. How can I disable it ?

**Comment by lifepillar** [comment]
What is the output of `completeopt`? Does it contain `preview`? If so, try to remove it with:

```vim
:set completeopt-=preview
```

If that doesn't work, please provide a step-by-step way to reproduce your issue.

**Comment by trlsmax** [comment]
`:set completeopt-=preview` works , thanks
