### ISSUE TITLE
omni without '+python' error

### ISSUE THREAD

**Issue by wining** [lifepillar/vim-mucomplete#104]
when i config 'omni', but vim does not has '+python'  ,it comes error
![default](https://user-images.githubusercontent.com/4005513/42081521-33ec5d96-7bb8-11e8-9309-dc0f8c8bec2f.png)

**Comment by lifepillar** [comment]
Thanks for the report! The current master should fix your issue. Let me know if it works for you.

**Comment by wining** [comment]
it doesn't work

**Comment by lifepillar** [comment]
Can you please try reproducing your issue with the provided `troubleshooting_vimrc.vim` (see `:h mucomplete-troubleshooting`)? Or at least post your settings and steps to reproduce.

**Comment by wining** [comment]
my vimrc :
[vimrc.txt](https://github.com/lifepillar/vim-mucomplete/files/2155637/vimrc.txt)
I put the plugin in ther folder "pack\plugins\start\vim-mucomplete"

my vim version
![image](https://user-images.githubusercontent.com/4005513/42170658-c4043ae6-7e49-11e8-8426-90f7faa195d4.png)

**Comment by lifepillar** [comment]
Ok, I see. Option `omnifunc` is set even when Vim is built without Python support (I believe that this should be reported as a bug to the maintainer of Python's ftplugin). To fix the error you need either to `setlocal omnifunc=` in `python` buffers (with an autocommand or in `~/.vim/after/ftplugin/python.vim`), or remove `'omni'` from MUcomplete's completion chain. The latter can be achieved by adding this to your `vimrc`:

```vim
let g:mucomplete#chains = {}
if !(has('python') || has('python3'))
  " Define whatever completion chain you want, but without 'omni':
  let g:mucomplete#chains.python = ['path', 'keyn'] 
endif
```

**Comment by sunaku** [comment]
Thanks for the workaround! :+1: Here is the former `~/.vim/after/ftplugin/python.vim` one:
```vim
" https://github.com/lifepillar/vim-mucomplete/issues/104
if !has('python') && !has('python3')
  " Error: Required vim compiled with +python
  " E117: Unknown function: pythoncomplete#Complete
  setlocal omnifunc=
endif
```
