### ISSUE TITLE
path autocomplete

### ISSUE THREAD

**Issue by wining** [lifepillar/vim-mucomplete#106]
1. Create a folder and create a file “main.go" in the folder
2. Input "// m" or “// M”，it shows below:
![b](https://user-images.githubusercontent.com/4005513/42793367-6b6da958-89ac-11e8-93cc-309430032260.gif)

and the C-X C-F shows :

![c](https://user-images.githubusercontent.com/4005513/42793555-3b019954-89ad-11e8-8805-4461d8feb3f1.gif)

**Comment by lifepillar** [comment]
Mmh, possibly MUcomplete’s path completion should watch for double slashes.

**Comment by lifepillar** [comment]
You are on Windows, so `let g:mucomplete#use_only_windows_paths=1` may be a workaround.

**Comment by lifepillar** [comment]
The current master should solve your issue. Feel free to re-open if you need to provide more feedback.
