### ISSUE TITLE
E15: Invalid expression: mucomplete#popup_exit("\^M")

### ISSUE THREAD

**Issue by tngreene** [lifepillar/vim-mucomplete#108]
Hi,

I've noticed something new while using vim-mucomplete for Python (haven't checked with other languages) that sometimes it gets broken and won't accept my pressing enter to close the pop up window full of good suggestions.

I instead get
```
E117: Unknown function: mucomplete#popup_exit
E15: Invalid expression: mucomplete#popup_exit("\^M")
```

I'm using gVim on Windows.

**Comment by tngreene** [comment]
There are my settings for the plugin

	"vim-mucomplete
	set completeopt+=menuone

	"For automatic completion, you also need to put these in your vimrc:
	inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
	inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
	inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")

	set completeopt+=noinsert

**Comment by lifepillar** [comment]
Remove the three `inoremap` commands: they are not needed any longer.

**Comment by memborg** [comment]
I can confirm removing `inoremap` results in no more errors

**Comment by tngreene** [comment]
I know this is after the closing, but I can also confirm that it results in no more errors. I turned it back on today and it appears to be working well! Thank you for your response!
