### ISSUE TITLE
error in config! E474: Invalid argument: completeopt+=noselect

### ISSUE THREAD

**Issue by Hello-Linux** [lifepillar/vim-mucomplete#109]
My vimrc configuration is 

set completeopt+=menuone
set completeopt+=noselect
let g:mucomplete#enable_auto_at_startup = 1

but vim show “Error detected while processing /root/.vimrc:
line   50:
E474: Invalid argument: completeopt+=noselect”

**Comment by lifepillar** [comment]
More precisely, auto-completion technically works before Vim 7.4.775, but there's currently no way for MUcomplete to avoid inserting the first match (which is typically annoying), because of the lack of `noselect` and `noinsert`. I am planning to improve backwards compatibility, though, so that may change in the future.

**Comment by lifepillar** [comment]
The current master makes auto-completion available for Vim as early as v7.4.143. If you have a version older than 7.4.775, you just `set completeopt=menuone`, and everything should work. Does that help?

**Comment by lifepillar** [comment]
Closing for lack of feedback. Feel free to reopen if you still have issues with the current master!

**Comment by Felixoid** [comment]
A little note from me:
It does work only if `longest` isn't in `completeopt`

**Comment by Felixoid** [comment]
7.4 without 775, precisely will write tomorrow

**Comment by Felixoid** [comment]
From Debian GNU/Linux 8.11 (jessie):
```
$ dpkg -l | grep vim
ii  vim                              2:7.4.488-7+deb8u3
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 10 2017 00:53:26)
Included patches: 1-488, 576
```

on `completeopt=preview,menuone,menu,longest` the longest variant is inserted automatically

**Comment by lifepillar** [comment]
I see. I have opened https://github.com/lifepillar/vim-mucomplete/issues/135 to track the bug.

**Comment by lifepillar** [comment]
https://github.com/lifepillar/vim-mucomplete/issues/135 should be fixed. I have also fixed `g:mucomplete#popup_direction`, which was not working correctly before v7.4.775.  @Felixoid Feel free to reopen https://github.com/lifepillar/vim-mucomplete/issues/135 if necessary.
