### ISSUE TITLE
<tab> in insert mode: open popup completion without selecting any

### ISSUE THREAD

**Issue by mrajner** [lifepillar/vim-mucomplete#110]
I spend quite a lot time trying customize mucomplete to my needs but I failed. Mayby I am missing something, but seeing great support from the author, I simply asking my question here.

According to documentation you can set `noinsert` and/or `noselect` to `completeopt` and that works if I enable completion on startup. But I prefer to trigger completion with default `<tab>` key. But with that single press of tab selects first entry in popup list (I think that `mucomplete#tab_complete(1)` is responsible for that). How can I get the popup menu to show on tab press, without going to first entry (and then I could select by subsequent tab press)?

**Comment by lifepillar** [comment]
You may want to add this to your `vimrc`:

```vim
setc completeopt=menuone,noinsert
let g:mucomplete#always_use_completeopt = 1`
```

See also `:help mucomplete-customization` for an explanation of the option.

**Comment by mrajner** [comment]
Yes, that is it. I just missed the customization option. Thank you for patience.
