### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by midnio** [lifepillar/vim-mucomplete#112]
What is your recommendation for snippets? Maybe you can add special Snippet plugin for mucomplete.

**Comment by lifepillar** [comment]
MUcomplete works with UltiSnips out of the box: just add the `'ulti'` method to your completion chain (see `:help mucomplete-methods`). If you prefer SnipMate, that works, too (see `:help mucomplete-compatibility` for the configuration).

**Comment by midnio** [comment]
I don't know how to add it, can you send a piece of code?

**Comment by lifepillar** [comment]
You'll likely want to redefine `g:UltiSnipsJumpForwardTrigger`, too, because Ultisnips's default (`<c-j>`) may conflict with a corresponding mapping in MUcomplete.

**Comment by midnio** [comment]
Why not integrating UltiSnips with MUComplete? Like when you see a ultisnips recommendation and press <tab>, expand it automatically without finishing it. Maybe this is should be good, opening a new issue for integrating ultisnips snippets with mucomplete.

**Comment by midnio** [comment]
Let's move to #113 to the tab-complete issue.
