### ISSUE TITLE
Automatically expand Snippets while in Recommendations Menu.

### ISSUE THREAD

**Issue by midnio** [lifepillar/vim-mucomplete#113]

**Comment by lifepillar** [comment]
You may put this in your `vimrc`:

```vim
  let g:mucomplete#chains = {}
  let g:mucomplete#chains.default = ['ulti', 'path', 'omni', 'keyn', 'dict', 'uspl']
  let g:UltiSnipsExpandTrigger = "<nop>"

  fun! MyCR()
    return pumvisible()
          \ ? "\<c-r>=UltiSnips#ExpandSnippetOrJump()\<cr>"
          \ : "\<cr>"
  endf

  inoremap <expr> <plug>MyCR MyCR()
  imap <cr> <plug>MyCR
```

Then, the selected snippet is expanded upon pressing Enter to accept the current menu entry. Is this what you want?

**Comment by midnio** [comment]
`inoremap <silent> <expr> <plug>MyCR MyCR()` isnt working. It just inserts MyCR()

**Comment by lifepillar** [comment]
That may happen if `MyCR()` is not defined. Have you restarted Vim after updating your `vimrc`?

**Comment by midnio** [comment]
Yeah i restarted

**Comment by lifepillar** [comment]
Can you please try using the `troubleshooting_vimrc.vim` that comes with MUcomplete? Edit the file and change the `runtimepath` to include the path to MUcomplete, UltiSnips and vim-snippets. For example:

```vim
set runtimepath+=~/.vim/pack/plugins/start/mucomplete
set runtimepath+=~/.vim/pack/plugins/start/ultisnips
set runtimepath+=~/.vim/pack/plugins/start/snippets
```

Then paste the configuration I have proposed at the end of the file. Save, exit Vim and start a new instance with:

```
vim -u troubleshooting_vimrc.vim
```

Can you still reproduce your issue?

**Comment by midnio** [comment]
Maybe casue of i'm using NeoVim?

**Comment by lifepillar** [comment]
No, in NeoVim it works the same (just tried with v0.3.1).

**Comment by lifepillar** [comment]
MUcomplete's documentation now describes the recommended configuration for UltiSnips, including how to have snippets automatically expanded upon accepting a menu entry. I have tried it in Vim 8.1.300 and NeoVim 0.3.1, with no issues. Feel free to reopen if necessary.

**Comment by midnio** [comment]
Maybe add it as option or default?

**Comment by lifepillar** [comment]
Ok, so now you may add this single line to your `vimrc`:

```vim
inoremap <silent> <expr> <cr> mucomplete#ultisnips#expand_snippet("\<cr>")
```

to have snippets expanded automatically.
