### ISSUE TITLE
Suggestions from buffer when pressing backspace

### ISSUE THREAD

**Issue by gjunkie** [lifepillar/vim-mucomplete#116]
I'm trying to figure out how this is happening. When typing I get all suggestions from my current buffer. But when I press backspace, I also get suggestions from other files buffer. How do control this behavior?

**Comment by lifepillar** [comment]
That's how Vim does it. It can be reproduced without MUcomplete. Turn off auto-completion if it's on, and use CTRL-X CTRL-N to trigger keyword completion. Then press backspace. You should see the behaviour you are describing.

**Comment by lifepillar** [comment]
See also https://github.com/lifepillar/vim-mucomplete/issues/101.
