### ISSUE TITLE
Example for manual tab invoked completion, with auto completion of C++ member functions

### ISSUE THREAD

**Issue by smhc** [lifepillar/vim-mucomplete#117]
Thanks for the great plugin. With some customisation it does exactly what I want.
I thought it might be useful to open the wiki to add example config like the below.

Perhaps vim-mucomplete could use a flag to add the '&& (g:mucomplete_with_key)' condition to all default 'can_complete' types. This allows someone to set that flag to suppress auto-complete, but still selectively turn on auto completion using trigger text (such as 'keword->'). Otherwise there is the need to override all can_complete types to add the condition like I have done below.

Configuration of Language-neovim
```vim
let g:LanguageClient_serverCommands = {
    \ 'cpp': ['/usr/local/bin/clangd']
    \ }
```

Configuration of vim-mucomplete to only auto-complete after ->, ., :: for C++ member completion.
Also only auto-complete paths if there is at least one character following '/', or the path consists of multiple path components. This is needed to prevent path completion when adding '//' style comments in C++.

'tab' is required to invoke the completion menu in all other cases.

```vim
set pumheight=10
set complete=.,w,b,u,k
set completeopt=menuone,noselect
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['omni', 'c-n', 'path', 'tags']
let s:pathstart = exists('+shellslash') && !&shellslash
      \ ? (get(g:, 'mucomplete#use_only_windows_paths', 0) ? '[\\~]' : '[/\\~]')
      \ : '[/~]'
let s:cpp_cond = { t -> (t =~# '\m\k\%(->\|::\|\.\)$') || (g:mucomplete_with_key && t =~# '\m\k\k$') }
let s:key_cond = { t -> (t =~# '\m\k\k$') && (g:mucomplete_with_key) }

let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.default = {
            \ 'tags': { t -> !empty(tagfiles()) && s:key_cond(t) },
            \ 'c-n': s:key_cond,
            \ 'keyn': s:key_cond,
            \ 'omni': { t -> strlen(&l:omnifunc) > 0 && s:key_cond(t) },
            \ 'path': { t -> (t =~# '\m'.s:pathstart.'\k$') || (t =~# '\m'.s:pathstart.'\k\k*'.s:pathstart) }
            \ }

" Auto popup without tab key for member completion in cpp
let g:mucomplete#can_complete.cpp = { 'omni': s:cpp_cond }
set shortmess+=c    " Shut off completion messages
```

**Comment by lifepillar** [comment]
>Perhaps vim-mucomplete could use a flag to add the '&& (g:mucomplete_with_key)' condition to all default 'can_complete' types. This allows someone to set that flag to suppress auto-complete

Note that `g:mucomplete_with_key` is a **read-only** flag: the user must never change it's value, it's set automatically by MUcomplete to distinguish auto-completion from manual completion.

With a configuration like yours, keyword completion would never be tried on auto-completion, but only with manual completion (e.g., when the user presses `<tab>`). I don't think that this is what most users would want. MUcomplete comes with what I think are sensible defaults, but of course they cannot satisfy everyone. Flexibility in customisation is one of MUcomplete's strengths, I believe.

>Also only auto-complete paths if there is at least one character following '/', or the path consists of multiple path components. This is needed to prevent path completion when adding '//' style comments in C++.

Mmh, that should not happen. Recognising paths and avoiding false positive is tricky. I'll look into it.

**Comment by smhc** [comment]
I wasn't suggesting modifying the g:mucomplete_with_key flag. 

I was suggesting adding a new option that would introduce checking the flag for all the can complete checks. Similar to what I have done with my config.

There is already the option of turning off autocomplete, so people do want to turn it if

**Comment by lifepillar** [comment]
There is a new `g:mucomplete#force_manual` option in the current master. When set to 1, all completion methods are enabled only for manual completion, *even if* auto-completion is on. So, you may write:

```vim
let g:mucomplete#force_manual = 1
let s:cpp_cond = { t -> (t =~# '\m\k\%(->\|::\|\.\)$') || (g:mucomplete_with_key && t =~# '\m\k\k$') }
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.cpp = { 'omni': s:cpp_cond }
let g:mucomplete#enable_auto_at_startup = 1
```

to have *only* omni-completion to be tried automatically.

Btw, the issue with path completion should be fixed, too (comments should not trigger path completion any more).

Finallly, I have opened the wiki for people to share their tips and tricks.

**Comment by smhc** [comment]
Thanks, that's exactly what I was asking for. I've added a page to the wiki.
