### ISSUE TITLE
Completion in html not triggered after /

### ISSUE THREAD

**Issue by jqno** [lifepillar/vim-mucomplete#120]
When editing html or xml, completion doesn't trigger when the cursor is after an `/`. For example, if I have the following line, and the cursor is at the end of the line:

`<sometag>something</`

When I press tab, nothing happens. When I press `<C-X><C-O>` to manually trigger omni-complete, I get a completion popup with `sometag>`.

When I type an `s` first and hit tab then, I do get the same behaviour I would get with omni-completion.

I've followed the troubleshooting guide. Below is the modified parts of `troubleshooting_vimrc.vim` that I ended up with:

```
set runtimepath+=~/.vim/plugged/vim-mucomplete " CHANGE THIS

" Optionally add additional configuration below this line

set completeopt+=menuone,noinsert
let g:mucomplete#chains = {}
let g:mucomplete#chains.html = ['omni']
let g:mucomplete#chains.xml = ['omni']
```

If I change `let g:mucomplete#chains.xml = ['omni']` to `let g:mucomplete#chains.xml = ['path', 'omni']`, I do get path completion. But why would I want that in an xml file 😉

**Comment by lifepillar** [comment]
>completion doesn't trigger when the cursor is after an /

That's (kind of) expected, as by default omni-completion is tried only if there is a keyword character in front of the cursor. Probably it makes sense to use a different condition for HTML/XML.
For now, you have to do it yourself by putting something like this in your `vimrc`:

```vim
let g:mucomplete#can_complete = {}
" Trigger completion after a keyword char (\k) or a slash
let s:xml_cond = { t -> t =~# '\m\%(\k\|/\)$' }
let g:mucomplete#can_complete.html =  { 'omni': s:xml_cond }
let g:mucomplete#can_complete.xml =  { 'omni': s:xml_cond }
```

**Comment by lifepillar** [comment]
With the current master you do *not* get path completion after `</` and you *do* get omni-completion. Feel free to reopen if that doesn't work for you
