### ISSUE TITLE
Neovim flashes completion window.

### ISSUE THREAD

**Issue by katsika** [lifepillar/vim-mucomplete#122]
Pressing `<tab>`, `<s-tab>`, `<C-n>` or `<C-p>` repeatedly on pum visible causes pum redraw resulting in pum's flashing. This is not the case when `<down>` or `<up>` are used.

I noticed that on omnicompletion from Jedi-vim.

**Comment by lifepillar** [comment]
MUcomplete does absolutely nothing as long as the menu is visible. And `<tab>`/`<s-tab>` just maps to `<c-n>`/`<c-p>`. Anyway, later I’ll try to reproduce.

Do you have the same issue if you use the `troubleshooting_vimrc.vim` that comes with MUcomplete? Just to rule out other plugins or your own settings.

**Comment by katsika** [comment]
I have just checked with `troubleshooting_vimrc.vim` and issue still persists. I have tried both with MUcomplete alone and with `jedi-vim`.

Understandably that's probably not MUcomplete's issue, as `<C-n>` and `<C-p>` cause flicker as well.

I am on `NVIM v0.3.1`.

**Comment by lifepillar** [comment]
I cannot reproduce your issue, not even with jedi-vim. Using NeoVim 0.3.1 as well.

**Comment by katsika** [comment]
Not sure what to check for, here is what it looks like:

![muc](https://user-images.githubusercontent.com/796021/44999207-2a202280-afc4-11e8-83b6-21d3db2539bb.gif)

Tried in iTerm and Terminal.app. No difference.

**Comment by lifepillar** [comment]
I see that there's pylint on. My best guess is that pylint or some other plugin triggered by text change is interfering. That `<up>` and `<down>` don't cause flicker then is expected, as they do not change the current text. As for MUcomplete, as I have said, it does nothing as long as the pop-up menu is visible (well, strictly speaking, it updates an internal variable on `InsertCharPre`, but `InsertCharPre` is not triggered when you press CTRL-N or CTRL-P).

Try removing MUcomplete and see whether the issue disappears.

**Comment by katsika** [comment]
Yes, it still flickers without MUcomplete installed. `<C-x><C-o>` on `sys.` with `jedi-vim` (I use it as it gives me its of completions easily) active flickers on `<C-p>`/`<C-n>` but not `<up>`/`<down>`.

Had a suspicion it wasn't MUcomplete. Thanks for looking into this!

**Comment by katsika** [comment]
Seems related: https://github.com/neovim/neovim/issues/8802
