### ISSUE TITLE
Unknown function: s:iskeyword

### ISSUE THREAD

**Issue by midnio** [lifepillar/vim-mucomplete#123]
When I try to use mucomplete with vim, it gives the error at the title. Also after pressing enter gives one more error that says `get(g:, 'did_plugin_ultisnips', 0) && s:is_keyword(t)`. Works fine in Neovim.

**Comment by lifepillar** [comment]
Are you on the current master? There was a regression recently, but that should be fixed. Interesting that NeoVim does not give the same error.

**Comment by midnio** [comment]
Magically reinstalling plugin worked, I don't know what happened.
