### ISSUE TITLE
mucomplete#enable_auto_at_startup prevents manual completion

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-mucomplete#124]
If I set `g:mucomplete#enable_auto_at_startup` to `true`, I can't trigger vim completions manually (with `c-x` mappings). That is, I can't override MUcomplete with a specific vim completion, called manually.

It works with `g:mucomplete#enable_auto_at_startup` set to false.

I understood that I could set `g:mucomplete#force_manual` and `can_complete` dictionary, but isn't there an easier way?

**Comment by lifepillar** [comment]
Not sure what you are trying to accomplish. Could you provide an example that works with auto-completion off but not with auto-completion on?

**Comment by mg979** [comment]
I'd like to call a specific completion and override mucomplete chains. I can do it by setting:

`imap <c-z>  <c-e><c-x>`

and press `c-z` instead of `c-x`, but I'd like to use `c-x`.

About an example of the difference between `g:mucomplete#enable_auto_at_startup` true or false, in this code:
```vim
let s:default = get(g:, 'vimdo_use_default_commands', 1) ? {
      \ 'ws':  ['trim whitespaces',             ':call do#trim_whitespaces()<cr>'  ],
      \ 're':  ['redir expression',             ':call do#redir_expression()<cr>'  ],
      \ 'rc':  ['redir command',                ':RedirCommand<space>'             ],
      \ 'ut':  ['update tags',                  ':call do#update_tags()<cr>'       ],
      \ 'vp':  ['profiling',                    ':call do#profiling()<cr>'         ],
      \ 'ds':  ['diff saved',                   ':call do#diff_with_saved()<cr>'   ],
      \ 'do':  ['diff other',                   ':call do#diff_with_other()<cr>'   ],
      \ 'dl':  ['diff last revision',           ':call do#diff_last_revision()<cr>'],
      \ 'ssa': ['show syntax attributes',       ':call do#syntax_attr()<cr>'       ],
      \} : {}
```

try to do this:
* `setf vim`
* go after one `:call ` inside quotes
* press `C`
* enter `do`
* no popup appears, but:
  - if `g:mucomplete#enable_auto_at_startup` is false, you can press `c-n` or `c-x` something
  - if it's true, `c-n` (or `c-x c-n`) does nothing, `c-x c-]` works at second try, `c-x c-l` inserts `^L`, but they work after pressing `c-e`

**Comment by lifepillar** [comment]
I see. This seems to be related to https://github.com/vim/vim/issues/1319. To reproduce without MUcomplete, in Insert mode type `do<c-x><c-v>`. Then type CTRL-N or CTRL-X something. You should see the behaviour you are describing.

Btw, the issue also affects MUcomplete's manual completion: just type `do<tab>` then CTRL-N or CTRL-X something.

Long time ago I had added some code to work around this issue (in `s:verify_completion()`). I need to investigate why this still happens.

**Comment by lifepillar** [comment]
I have debugged this. For some reason, `s:verify_completion()` is not called when the `'cmd'` method is attempted but returns no result. Quite puzzling.

**Comment by lifepillar** [comment]
It seems that, when CTRL-X CTRL-V does not return any result, it also prevents the typeahead to be flushed. That's why, in your example, I need to type TAB twice after typing `do` to get keyword completion: the first time, `<plug>(MUcompleteVerify)` is not eaten, but it is when you type TAB the second time. At least, this is my understanding so far. If I am correct, there's not much that can be done on MUcomplete's side to work around this issue.

Given that CTRL-X CTRL-V is broken, I would suggest removing the `'cmd'` method from your completion chain.

**Comment by mg979** [comment]
Thanks, without `cmd` it works, and it can also call other completion types with `<c-x>`. A pity that it's broken, maybe it can be fixed in some way, because `<c-e>` can reset it.

**Comment by lifepillar** [comment]
For reference, this is the original discussion about this issue: https://github.com/lifepillar/vim-mucomplete/issues/42.

**Comment by mg979** [comment]
I found an alternative to `cmd` completion that seems to work very well, using omnifunc. with:

https://github.com/IngoHeimbach/neco-vim

There is also https://github.com/machakann/vim-Verdin but it's much slower.
