### ISSUE TITLE
Compatibility with neosnippet?

### ISSUE THREAD

**Issue by midnio** [lifepillar/vim-mucomplete#126]
I did not found it in mucomplete-compatibility.

**Comment by lifepillar** [comment]
Nobody has asked for it so far or submitted a pull request. I'll take a look. Suggestions welcome.

**Comment by lifepillar** [comment]
I have added experimental support for Neosnippet to a`neosnippet` branch. It works similarly to UltiSnips. To try it out, checkout the `neosnippet` branch and add this to your `vimrc`:

```vim
  let g:mucomplete#chains = {}
  let g:mucomplete#chains.default = ['path', 'nsnp', 'keyn']
  inoremap <silent> <expr> <cr> mucomplete#neosnips#expand_snippet("\<cr>")
```

The `'nsnp'` method enables Neosnippet in your completion chain.

**Comment by lifepillar** [comment]
Merged into master!
