### ISSUE TITLE
Feature request: allow path completion to begin after an assignment operator

### ISSUE THREAD

**Issue by lacygoill** [lifepillar/vim-mucomplete#127]
I often write a minimal `vimrc` containing lines like this:

    set rtp^=/path/to/some-plugin
    set rtp+=/path/to/some-plugin/after

The path completion method provided by `vim-mucomplete` fails to complete such paths, unless, I believe, a space is temporarily added between the assignment operator and the path.

I think it could succeed if, in `autoload/mucomplete/path.vim`, [this line](https://github.com/lifepillar/vim-mucomplete/blob/master/autoload/mucomplete/path.vim#L105):

    let l:prefix = matchstr(l:prefix, '\s\zs.*'.s:pathstart.'.*$', 1) " Next potential path

Was replaced by this line:

    let l:prefix = matchstr(l:prefix, '[ \t=]\zs.*'.s:pathstart.'.*$') " Next potential path
    "                                  ^^^^^^

I included the equal sign inside a collection with the space and the tab characters.
I also had to remove the third optional argument passed to `matchstr()`, otherwise the completion still failed after the `^=` operator, probably because the `^` character, contrary to `+`, is not in `'isfname'` by default.

I'm not sure whether you would agree with the idea of allowing path completion after such characters, so I only submitted an issue rather than a PR.

Thank you very much for your plugin.

**Comment by lifepillar** [comment]
>The path completion method provided by vim-mucomplete fails to complete such paths

Path completion works for me after `+=` or `^=` without typing spaces, but I need to type two characters after the backslash instead of just one (assuming auto-completion is on). I don't know whether the particular use case you propose justifies trying to fix what I think is a minor issue. Matching paths is extremely tricky and it's likely impossible to avoid false positives or false negatives, sometimes.

Anyway, I'll keep this open and think about it when I have some time.

**Comment by lacygoill** [comment]
I've just made a test again, and you're right, the `path` method works fine, it succeeds to complete both paths in the previous example. I think I've made an error and tested the `file` path completion instead of the `path` one, or maybe I misconfigured something else.

Anyway, since it works fine, I close the issue. Sorry for the trouble, and thank you for the answer.

**Comment by lifepillar** [comment]
@sharethewisdom Sure, you may define your own condition for the `conf` filetype (see `:help g:mucomplete#can_complete`). For example, you may put this in your `vimrc`:

```vim
" Enable path completion after two file characters or after !/
let s:path_cond = { t -> t =~ '\f\f\|!/' }
let g:mucomplete#can_complete = { 'conf': { 'path': s:path_cond } }
```

Of course, you may use the regular expression you prefer.

**Comment by sharethewisdom** [comment]
hmm I also added `setl iskeyword+=!` to `ftplugin/conf.vim` and

```
  let g:mucomplete#chains.conf = ['file', 'path']
  let s:path_cond = { t -> t =~ '\f\f\|!' }
  let g:mucomplete#can_complete.conf = { 'path': s:path_cond, 'file': s:path_cond }
```

which seems to work the way I want. thanks

**Comment by lifepillar** [comment]
>I also added setl iskeyword+=!

That shouldn't be necessary. But I have realised that I haven't suggested a good pattern. This is how it should be:

```vim
let s:path_cond = { t -> t =~ '\f\f$\|!/\f*$' }
```

The value of `t` is the part of the current line preceding the cursor, so the pattern should match at the end (dollar symbols).

If this still doesn't work without modifying `iskeyword`, can you please post the value of `iskeyword`, `isfname`, and the full `ftplugin/conf.vim` you are using? Also, how do you expect it to work, exactly? With my suggestions and autocompletion on, completions should appear as soon as you type `!` followed by `/`.

**Comment by sharethewisdom** [comment]
you're right about `iskeyword`. But I don't think one needs filename completion to start with `/`, because the un-ignored files are in the git root directory anyway. I prefer:

```vim
let g:mucomplete#can_complete.conf = {
  \ 'path': { t -> t =~ '\f\f$\|^!\f*$' },
  \ 'file': { t -> t =~ '\f\f$\|^!\f*$' }}
```
e.g.

```
*
!.gitignore
!README
!include
!include/*
```
