### ISSUE TITLE
How to show suggestions right after first key press

### ISSUE THREAD

**Issue by cwfoo** [lifepillar/vim-mucomplete#128]
vim-mucomplete starts to show a list of suggestions only after the second key press. Is there a way to make the list of suggestions appear right after the first key press?

**Comment by lifepillar** [comment]
Yes, see`g:mucomplete#can_complete`. I can post an example later.

**Comment by lifepillar** [comment]
The following example shows how to enable keyword completion and omni-completion after one (keyword) character:

```vim
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.default = {
      \ 'keyn': { t -> t =~# '\k$' },
      \ 'omni': { t -> !empty(&l:omnifunc) && t =~# '\k$' },
      \ }
```

In the lambdas (see `:help lambda`), `t` is the text before the cursor. Other completion methods can be defined in a similar way. And you may use any regular expression instead of `'\k$'`, of course.

**Comment by cwfoo** [comment]
Would you consider adding a setting to make this change easier?

I've used company mode in emacs before, and in company mode, this change is as easy as:

```lisp
; Start completing after entering 1 character.
(setq company-minimum-prefix-length 1)
```

**Comment by cwfoo** [comment]
Would you consider adding a setting to make this change easier?

I've used emacs' company mode (a text completion framework) before, and in company mode, this change is as easy as:

```lisp
; Show list of suggestions right after entering 1 character.
(setq company-minimum-prefix-length 1)
```

**Comment by lifepillar** [comment]
The current master has a new option: `g:mucomplete#minimum_prefix_length`. So, to get suggestions after one key, use:

```vim
let g:mucomplete#minimum_prefix_length = 1
```
