### ISSUE TITLE
It does not close the info buffer

### ISSUE THREAD

**Issue by gerroon** [lifepillar/vim-mucomplete#132]
Hi

It seems the like info buffer about classes is not turned off when the completion is entered, like when no completion list is available, the window is still open. It is a bit of drag since I have to move to the buffer and delete it manually.

I am using it with Python files, on Win x64 10

thanks

**Comment by gerroon** [comment]
Thanks, I will try to test the options you mentioned.

**Comment by lifepillar** [comment]
Closing for lack of feedback. Feel free to reopen if you think that this is a MUcomplete issue.
