### ISSUE TITLE
can_complete triggered by space

### ISSUE THREAD

**Issue by markwu** [lifepillar/vim-mucomplete#140]
Can I trigger omni completion with spaces? Take the following screenshot as example, I want to trigger omni completion after I typed `<table `, I wish mucomplete shows me the options for `<table` tag after the `space`.

![2019-03-05 4 59 30](https://user-images.githubusercontent.com/196861/53793246-68dd6800-3f68-11e9-9699-077eeb023d00.png)

I try to add `\s` into html can_complete like `'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }`, but no success.

Here comes with my original `can_complete` configuration. 
```
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete = {
            \   'html': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|<\|</\|"\|''\)$' }
            \   },
            \   'javascript': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'php': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|::\|->\)$' }
            \   },
            \   'python': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'xml': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|<\|</\|"\|''\)$' }
            \   }
            \ }
```

**Comment by markwu** [comment]
BTW, can we have a new wiki for can_complete for different languages? I think it is easier for new comer to play with `mucomplete`.

**Comment by lifepillar** [comment]
How did you get the completions in the screenshot (keys pressed, plugins used, …)?

**Comment by lifepillar** [comment]
The wiki page for configurations is a good idea. Feel free to create such a page yourself: the wiki is open for editing.

**Comment by lifepillar** [comment]
Have you tried `let g:mucomplete#empty_text = 1`?

**Comment by markwu** [comment]
I used `mucomplete` and pressed `<C-X><C-O>` after space manually.

I also tried `empty_text=1` before I report this issue, but it only popup at start of line, not space after `<table`.

**Comment by lifepillar** [comment]
Currently, `g:mucomplete#empty_text` only affects tab completion. So, after the space you need to press tab to trigger completion.

Currently, auto-completion is never triggered after a space, but I might change that.

**Comment by markwu** [comment]
I see, that's why I never get completions works with `\s`. Thanks for your explanation.

**Comment by lifepillar** [comment]
If you want to experiment yourself with autocompletion after space characters, you may edit `autoload/auto.vim` and change this:

```vim
  fun! mucomplete#auto#insertcharpre()
    let s:insertcharpre = !pumvisible() && (v:char =~# '\m\S')
  endf
```

into this:

```vim
  fun! mucomplete#auto#insertcharpre()
    let s:insertcharpre = !pumvisible()
  endf
```

and see whether it breaks anything. Feedback appreciated!

**Comment by markwu** [comment]
I test with the changes you suggested, and also add `\s` into my `can_complete` trigger, looks like:

```vim
\ 'html': {
\     'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
\  }
```
It works very well, here comes with the screencast. I test it both inside/outside tag, seems no problems at all.

![untitled](https://user-images.githubusercontent.com/196861/53972220-55cdc200-4139-11e9-94ca-d3a831587b66.gif)

**Comment by lifepillar** [comment]
Can you try the current master? If you set:

```vim
let g:mucomplete#empty_text = 1
```

you should now be able to autocomplete after spaces.

**Comment by markwu** [comment]
I tried, and it works! Thanks for this change.

**Comment by lifepillar** [comment]
Great! For the record (and for other users stumbling upon this issue), you must set `g:mucomplete#empty_text` *and* set `g:mucomplete#can_complete()`'s patterns so that they match white space.

**Comment by markwu** [comment]
After several days testing, I think ` g:mucomplete#empty_text = 1` too aggressive for me. Because the completion menu will popup in any place when I press `<tab>`.

I have two ways to solve this:

#### 1. Configuration way:
Map the cycling trigger from `<tab>` to other key, for example `<c-space>`, then I can enjoy the `<tab>`, `auto completion` and `completion after space` altoghter, without annoying  popup when I press `<tab>`.

But, I like `<tab>` completion. Ha ha ..

Here comes with my configuration:

```vim
let g:mucomplete#cycle_with_trigger = 0
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#empty_text = 1

imap <C-Space> <plug>(MUcompleteFwd)
" imap <C-@> <plug>(MUcompleteFwd)

imap <expr> <Tab> pumvisible() ? "\<plug>(MUcompleteFwd)" : "\<Tab>"
imap <expr> <S-Tab> pumvisible() ? "\<plug>(MUcompleteBwd)" : "\<S-Tab>"
inoremap <silent> <Plug>(MUcompleteFwdKey) <Right>
imap <Right> <Plug>(MUcompleteCycFwd)
inoremap <silent> <Plug>(MUcompleteBwdKey) <Left>
imap <Left> <Plug>(MUcompleteCycBwd)

let g:mucomplete#chains = {}
let g:mucomplete#chains = {
            \   'default' : ['path', 'omni', 'keyn', 'dict', 'ulti'],
            \   'vim'     : ['path', 'cmd', 'keyn', 'tags']
            \ }
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete = {
            \   'css': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\s\{'.&l:shiftwidth.'\}\|:\s\)$' }
            \   },
            \   'html': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   },
            \   'javascript': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'php': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|::\|->\)$' }
            \   },
            \   'python': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'xml': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   }
            \ }
```

#### 2. or Modification the core:

Change `autoload/mucomplete/auto.vim` line 50 from 
```vim
let s:insertcharpre = !pumvisible() && (v:char =~# s:v_char_expr)
```
to
```vim
let s:insertcharpre = !pumvisible()
```

And, let `g:mucomplete#can_complete` dictionary to decide can complete after space or not. With this change, I don't need to enable ` g:mucomplete#empty_text = 1`, and I can get everything I want.

Here comes the configuration with this change, I don't need to remap `<tab>` to other key to avoid annoying popup menu:

```vim
let g:mucomplete#enable_auto_at_startup = 1

inoremap <silent> <Plug>(MUcompleteFwdKey) <Right>
imap <Right> <Plug>(MUcompleteCycFwd)
inoremap <silent> <Plug>(MUcompleteBwdKey) <Left>
imap <Left> <Plug>(MUcompleteCycBwd)

let g:mucomplete#chains = {}
let g:mucomplete#chains = {
            \   'default' : ['path', 'omni', 'keyn', 'dict', 'ulti'],
            \   'vim'     : ['path', 'cmd', 'keyn', 'tags']
            \ }
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete = {
            \   'css': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\s\{'.&l:shiftwidth.'\}\|:\s\)$' }
            \   },
            \   'html': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   },
            \   'javascript': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'php': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|::\|->\)$' }
            \   },
            \   'python': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'xml': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   }
            \ }
```

I personally like 2nd way, but I am not sure if it violet any `mucomplete` original behaviors or features.

**Comment by markwu** [comment]
After several days testing, I think ` g:mucomplete#empty_text = 1` too aggressive for me. Because the completion menu will popup in any place when I press `<tab>`.

I have two ways to solve this:

#### 1. Configuration way:
Map the cycling trigger from `<tab>` to other key, for example `<c-space>`, then I can enjoy the `<tab> for indention`, `<tab> completion when menu popup`  and `completion after space with <c-space>` altogether, without annoying  popup when I press `<tab>`.

But, I like original `<tab>` completion. Ha ha ..

Here comes with my configuration:

```vim
let g:mucomplete#cycle_with_trigger = 0
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#empty_text = 1

imap <C-Space> <plug>(MUcompleteFwd)
" imap <C-@> <plug>(MUcompleteFwd)

imap <expr> <Tab> pumvisible() ? "\<plug>(MUcompleteFwd)" : "\<Tab>"
imap <expr> <S-Tab> pumvisible() ? "\<plug>(MUcompleteBwd)" : "\<S-Tab>"
inoremap <silent> <Plug>(MUcompleteFwdKey) <Right>
imap <Right> <Plug>(MUcompleteCycFwd)
inoremap <silent> <Plug>(MUcompleteBwdKey) <Left>
imap <Left> <Plug>(MUcompleteCycBwd)

let g:mucomplete#chains = {}
let g:mucomplete#chains = {
            \   'default' : ['path', 'omni', 'keyn', 'dict', 'ulti'],
            \   'vim'     : ['path', 'cmd', 'keyn', 'tags']
            \ }
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete = {
            \   'css': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\s\{'.&l:shiftwidth.'\}\|:\s\)$' }
            \   },
            \   'html': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   },
            \   'javascript': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'php': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|::\|->\)$' }
            \   },
            \   'python': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'xml': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   }
            \ }
```

#### 2. or Modification the core:

Change `autoload/mucomplete/auto.vim` line 50 from 
```vim
let s:insertcharpre = !pumvisible() && (v:char =~# s:v_char_expr)
```
to
```vim
let s:insertcharpre = !pumvisible()
```

And, let `g:mucomplete#can_complete` dictionary to decide can complete after space or not. With this change, I don't need to enable ` g:mucomplete#empty_text = 1`, and I can get everything I want.

Here comes the configuration with this change, I don't need to remap `<tab>` to other key to avoid annoying popup menu:

```vim
let g:mucomplete#enable_auto_at_startup = 1

inoremap <silent> <Plug>(MUcompleteFwdKey) <Right>
imap <Right> <Plug>(MUcompleteCycFwd)
inoremap <silent> <Plug>(MUcompleteBwdKey) <Left>
imap <Left> <Plug>(MUcompleteCycBwd)

let g:mucomplete#chains = {}
let g:mucomplete#chains = {
            \   'default' : ['path', 'omni', 'keyn', 'dict', 'ulti'],
            \   'vim'     : ['path', 'cmd', 'keyn', 'tags']
            \ }
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete = {
            \   'css': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\s\{'.&l:shiftwidth.'\}\|:\s\)$' }
            \   },
            \   'html': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   },
            \   'javascript': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'php': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|::\|->\)$' }
            \   },
            \   'python': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\k\|\.\)$' }
            \   },
            \   'xml': {
            \       'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\m\%(\s\|\k\|<\|</\|"\|''\)$' }
            \   }
            \ }
```

I personally like 2nd way, but I am not sure if it violet any `mucomplete` original behaviors or features.

**Comment by lifepillar** [comment]
Ok, I'll fix that. What is needed is two separate options, one for manual completion and one for autocompletion.

**Comment by lifepillar** [comment]
The current master has a new option called `g:mucomplete#empty_text_auto`, which controls autocompletion after spaces. Manual completion after spaces is controlled by `g:mucomplete#empty_text`, as before. So, if you set the former option to `1` and leave the latter to its default, autocompletion will be triggered after every character, but Tab will insert a literal tab when typed after a space.

**Comment by markwu** [comment]
Thanks, it works great.

**Comment by lifepillar** [comment]
I have made your `can_complete` condition the default for HTML and XML buffers. So, you should now be able to (auto)complete after spaces, single and double quotes without changing `g:mucomplete#can_complete`. You still need to enable (auto)completion after spaces by setting `g:mucomplete#empty_text` and `g:mucomplete#empty_text_auto` to `1`.

**Comment by markwu** [comment]
Great thanks, I'll change my vimrc according this change.
