### ISSUE TITLE
Using <tab> for ultisnips expansion?

### ISSUE THREAD

**Issue by garymh** [lifepillar/vim-mucomplete#142]
I see its possible with #113 to use `<CR>` for snippet expansion, but is it also possible to have some kind of conditional where (for example):

After typing the text `def`:

1) If there is a snippet called "def", pressing `<tab>` expands it (and would allow you to jump between the snippet triggers)
2) Otherwise, completes the word (say `definition`,  in this case)

It would be similar to how Sublime Text and Atom (I think) handles their snippets.

**Comment by lifepillar** [comment]
There’s a tip in MUcomplete’s documentation about how to perform different actions when Tab is pressed. Does that help?

**Comment by garymh** [comment]
Ah, thanks! Must have missed that. I should be able to figure it out from there.

**Comment by lifepillar** [comment]
Mmh, that might be less obvious than expected… I'll leave this open: if you find a solution, please post it!

**Comment by lifepillar** [comment]
Try this:

```vim
  let g:ulti_expand_or_jump_res = 0

  fun! MyTabAction()
    return g:ulti_expand_or_jump_res ? "" : "\<plug>(MyFwd)"
  endf

  imap <plug>(MyFwd) <plug>(MUcompleteFwd)
  inoremap <plug>(TryUlti) <c-r>=UltiSnips#ExpandSnippetOrJump()<cr>
  imap <expr> <silent> <plug>(TryMUcomplete) MyTabAction()
  imap <expr> <silent> <tab> "\<plug>(TryUlti)\<plug>(TryMUcomplete)"
```

How does it work for you?

**Comment by lifepillar** [comment]
This may be better if you use Tab also to move down in the pop-up menu:

```vim
  let g:ulti_expand_or_jump_res = 0

  fun! TryUltiSnips()
    if !pumvisible() " Do not trigger UltiSnips with Tab when the pop-up menu is open
      call UltiSnips#ExpandSnippetOrJump()
    endif
    return ''
  endf

  fun! TryMUcomplete()
    return g:ulti_expand_or_jump_res ? "" : "\<plug>(MyFwd)"
  endf

  imap <plug>(MyFwd) <plug>(MUcompleteFwd)
  inoremap <plug>(TryUlti) <c-r>=TryUltiSnips()<cr>
  imap <expr> <silent> <plug>(TryMU) TryMUcomplete()
  imap <expr> <silent> <tab> "\<plug>(TryUlti)\<plug>(TryMU)"
```

In either case, you must still remap UltiSnips's expand trigger to avoid conflicts with MUcomplete's mappings, e.g.:

```vim
  let g:UltiSnipsExpandTrigger = "<f5>"        " Do not use <tab>
  let g:UltiSnipsJumpForwardTrigger = "<c-b>"  " Do not use <c-j>
```

**Comment by garymh** [comment]
Oh wow, that's absolutely perfect! Thank you so much for the effort! 😄

**Comment by garymh** [comment]
Actually... I think it does break when including "ulti" in the chain. I'm using it with a ruby file and its skipping over my snippets.

Besides the code above, I have the following:

```vim
call plug#begin()
Plug 'lifepillar/vim-mucomplete'
Plug 'honza/vim-snippets'
Plug 'SirVer/ultisnips'
call plug#end()

set completeopt+=menuone,noselect
let g:mucomplete#enable_auto_at_startup = 1
let g:ulti_expand_or_jump_res = 0
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['path', 'ulti', 'keyn']
```

**Comment by garymh** [comment]
Only small issue I can find: It seems to insert words automatically despite my `completeopt` settings. For example, with these settings (using your first configuration, btw):

```vim
set completeopt=longest,menuone,preview,noinsert

let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#completion_delay = 50
let g:mucomplete#reopen_immediately = 0
let g:mucomplete#always_use_completeopt = 1
```

When I go to type `blank` it auto inserts `blankslate` (the name of a snippet I have) as I start to type `bl`.

**Comment by lifepillar** [comment]
That's likely because of `longest`. How does it work after `set cot-=longest`?

**Comment by garymh** [comment]
Yes! You're a genius. Works perfectly!
