### ISSUE TITLE
go language complete error

### ISSUE THREAD

**Issue by wining** [lifepillar/vim-mucomplete#143]
![图片](https://user-images.githubusercontent.com/4005513/54679208-a7b31680-4b41-11e9-82c4-18f076cff481.png)

my vim conf:
```
"MUcomplete
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#completion_delay = 100
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.go = { 'omni': { t -> t =~# '\m\k\%(\k\|\.\)$' } }
```

**Comment by lifepillar** [comment]
That doesn't look like a MUcomplete issue. I suggest that you remove MUcomplete, restart Vim and try to complete text with CTRL-X CTRL-O. If you still get errors, you need to fix your omni-completion plugin first.
