### ISSUE TITLE
g:mucomplete#chains option not working properly

### ISSUE THREAD

**Issue by tripurari001** [lifepillar/vim-mucomplete#144]
Hi There 

I have 

`
let g:mucomplete#chains = { 'default' : ['file', 'c-n'] }
`
in my `init.vim` and when i press tab mu-complete takes a lot of time to show the suggestions list ( also searches from tag file which i don't want ) even i have limited the chain to 'file' and 'c-n' it searches from tag file and all which makes it super slow 

I am using neovim 3.1 and vim 7.4 both have the same issue 

the output of `echo g:mucomplete#chains` is `{'vim': ['path', 'cmd', 'keyn'], 'default': ['file', 'c-n']}`

**Comment by mg979** [comment]
@tripurari001 I  think you should use `'keyn'`, not `'c-n'` in your default value.

`:h i_CTRL-N`

**Comment by lifepillar** [comment]
The `c-n` method corresponds to item 13 (*keywords in 'complete'*) in `:help ins-completion` (see also `:help 'complete'`). As pointed out by @mg979, you likely want `'keyn'` instead, which corresponds to item 2 (*keyword in the current file*) in the same help page.

**Comment by lifepillar** [comment]
Should you want to keep using `'c-n'`, take a look at the paragraph *Optimize your completion chains* in `:help mucomplete-tips`.

**Comment by tripurari001** [comment]
@lifepillar @mg979  thanks for your quick reply 

now I know where I was making the mistake by looking into  `:h i_CTRL-N`  

**What I wanted**
when I press tab I wanted the suggestions from the all loaded buffer and from the path completion option (like ctrl_x + ctrl_f  ) but not from the tag file 

**what I thought**
I thought it's mu-complete who is forcing vim to look into tag-file

**what was the fix**
It's vim's native option `'complete' 'cpt'` which decides where to look when user press `CTRL_N` and all I need to do is remove `t` from this comma separated option
`set complete=.,w,b,u` 

and then 

`let g:mucomplete#chains = { 'default' : ['file', 'c-n'] }` will do the job 👍 

Again Thank you folks 👍

**Comment by tripurari001** [comment]
I will close the issue
