### ISSUE TITLE
Using a list as a custom completion

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-mucomplete#145]
I'm trying to get a list of python exceptions as a custom completion list, when the line begins with `except `.

How to make a custom completion that is used when s:is_exception() is true?

```vim
fun! s:is_exception()
  return match(getline('.'), '^ *except ') == 0
endfun
```

For example, I have a list of exceptions
```vim
  let s:exceptions = ['BaseException', 'Exception', 'ArithmeticError', ] " etc
```

And I would like to call this list with a custom completion named `python_exceptions`

```vim
let g:mucomplete#can_complete.python = {'python_exceptions': 's:is_exception'}
```

I understand I could use `b:mucomplete_wordlist` but what if I want to register that list as a completion type, with its own name? I'd want different custom lists to be used in different contexts defined in `g:mucomplete#can_complete.python`.

**Comment by mg979** [comment]
Also, even using `b:mucomplete_wordlist` wasn't working with the big list I was providing, I could make it work by changing the code but not sure if things were already as they are supposed to be.

**Comment by lifepillar** [comment]
Custom lists are filetype specific. So, you should be able to achieve what you want with something along these lines:

```vim
let g:mucomplete#wordlist = { 'python': s:my_list_of_words }
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.python = { 'list': s:my_activation_condition }
let g:mucomplete#chains = {}
let g:mucomplete#chains.python = ['list', 'keyn']  " For example
```

The activation condition might be your function (but see below).

>even using b:mucomplete_wordlist wasn't working with the big list I was providing

What does that mean? Wrong suggestions? No suggestions? Slow suggestions?

First, make sure that the list is lexicographically sorted. That said, the way lists currently work, you get only matches that *start* with the text you have typed (as completion normally works). So, given your list of words, if you type `ex` you will get only `Exception` and not, for instance, `BaseException`.

**Comment by lifepillar** [comment]
For something more complex than the above, I suggest that you write your own completion function. It's not hard. For a simple example, see `:help complete()`. For full fledged functions, see `:help complete-functions`. You may also browse the files in MUcomplete's `autoload` folder: the simplest to adapt is probably `uspl.vim`.

In a nutshell, you define a function `F()` that calls `complete()` to build the pop-up menu with the entries you want:

```vim
fun! F()
  call complete(col('.'), ['BaseException', 'Exception', 'ArithmeticError'])
  return ''
endf
```

 then define a user-defined completion method in `g:mucomplete#user_mappings` that invokes it:

```vim
let g:mucomplete#user_mappings = { 'python_exception': "\<c-r>=F()<cr>" }
```

After that, you may add your brand new `'python_exception'` method to a Python-specific completion chain and define a filetype-specific activation condition:

```vim
let g:mucomplete#chains = {}
let g:mucomplete#chains.python = ['python_exception', 'keyn']  " For example
let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.python = { 'python_exception': s:is_exception() }
```

This should give you all the flexibility you need.

**Comment by mg979** [comment]
Thanks for the help.

> What does that mean? Wrong suggestions? No suggestions? Slow suggestions?
First, make sure that the list is lexicographically sorted.

Some words triggered the popup, others did not, but sorting the list fixed it. I had modified the function like this, to make it work without needing to sort the list:

```vim
fun! mucomplete#list#completefunc(findstart, base)
  if a:findstart
    return match(getline('.'), '\S\+\%'.col('.').'c')
  else
    return filter(copy(s:wordlist()), 'v:val =~ ''^''.a:base')
  endif
endfun
```

No sure what those while loops were for.

In the end I could make it work with the list:
```vim
if !has_key(g:mucomplete#chains, 'python')
  let g:mucomplete#chains.python = {'pythonString': ['keyn'], 'default': ['list', 'path', 'omni', 'keyn']}
  call extend(g:mucomplete#can_complete.python, {'list': { t -> t =~ '^ *except ' } })
  let g:mucomplete#wordlist.python = sort(['BaseException', 'Exception', 'ArithmeticError', 'FloatingPointError', 'OverflowError', 'ZeroDivisionError', 'AssertionError', 'AttributeError', 'BufferError', 'EOFError', 'ImportError', 'ModuleNotFoundError', 'LookupError', 'IndexError', 'KeyError', 'MemoryError', 'NameError', 'UnboundLocalError', 'OSError', 'BlockingIOError', 'ChildProcessError', 'ConnectionError', 'BrokenPipeError', 'ConnectionAbortedError', 'ConnectionRefusedError', 'ConnectionResetError', 'FileExistsError', 'FileNotFoundError', 'InterruptedError', 'IsADirectoryError', 'NotADirectoryError', 'PermissionError', 'ProcessLookupError', 'TimeoutError', 'ReferenceError', 'RuntimeError', 'NotImplementedError', 'RecursionError', 'StopIteration', 'StopAsyncIteration', 'SyntaxError', 'IndentationError', 'TabError', 'SystemError', 'TypeError', 'ValueError', 'UnicodeError', 'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeTranslateError', 'Warning', 'BytesWarning', 'DeprecationWarning', 'FutureWarning', 'ImportWarning', 'PendingDeprecationWarning', 'ResourceWarning', 'RuntimeWarning', 'SyntaxWarning', 'UnicodeWarning', 'UserWarning', 'GeneratorExit', 'KeyboardInterrupt', 'SystemExit'])
endif
```
But if I don't use a lambda with `g:mucomplete#can_complete`, it throws an error.

I'm trying the other method, but I couldn't get it to work yet.

**Comment by mg979** [comment]
Ok thanks, I could make it work like this:

```vim
if !has_key(g:mucomplete#chains, 'python')
  let g:mucomplete#chains.python = {'pythonString': ['keyn'], 'default': ['python_exceptions', 'path', 'omni', 'keyn']}
  let g:mucomplete#can_complete.python = {'python_exceptions': { t -> t =~ '^ *except' } }
  let g:mucomplete#user_mappings.python_exceptions = "\<c-r>=Python_exceptions()\<cr>"
  let s:exceptions = ['BaseException', 'Exception', 'ArithmeticError', 'FloatingPointError', 'OverflowError', 'ZeroDivisionError', 'AssertionError', 'AttributeError', 'BufferError', 'EOFError', 'ImportError', 'ModuleNotFoundError', 'LookupError', 'IndexError', 'KeyError', 'MemoryError', 'NameError', 'UnboundLocalError', 'OSError', 'BlockingIOError', 'ChildProcessError', 'ConnectionError', 'BrokenPipeError', 'ConnectionAbortedError', 'ConnectionRefusedError', 'ConnectionResetError', 'FileExistsError', 'FileNotFoundError', 'InterruptedError', 'IsADirectoryError', 'NotADirectoryError', 'PermissionError', 'ProcessLookupError', 'TimeoutError', 'ReferenceError', 'RuntimeError', 'NotImplementedError', 'RecursionError', 'StopIteration', 'StopAsyncIteration', 'SyntaxError', 'IndentationError', 'TabError', 'SystemError', 'TypeError', 'ValueError', 'UnicodeError', 'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeTranslateError', 'Warning', 'BytesWarning', 'DeprecationWarning', 'FutureWarning', 'ImportWarning', 'PendingDeprecationWarning', 'ResourceWarning', 'RuntimeWarning', 'SyntaxWarning', 'UnicodeWarning', 'UserWarning', 'GeneratorExit', 'KeyboardInterrupt', 'SystemExit']
endif

fun! Python_exceptions()
  let line = getline('.')
  let col = match(line, '\(except \)\@<=') + 1
  call complete(col, filter(copy(s:exceptions), 'v:val =~ "^".line[col-1:]'))
  return ''
endf
```

Only problem is that `g:mucomplete#user_mappings` is only read when the plugin is loaded,
so I can't put this in the python ftplugin. I had to add this in autoload/mucomplete.vim:

```vim
augroup MUcompleteUpdateCompletions
  au!
  au InsertEnter * call extend(s:compl_mappings, get(g:, 'mucomplete#user_mappings', {}), 'keep')
augroup END
```

**Comment by lifepillar** [comment]
>Not sure what those while loops were for.

The `'list'` method expects your list of words to be sorted so that binary search can be performed, which is what the code you refer to does. You may apply `sort()` to your list before passing it to MUcomplete if necessary.

**Comment by lifepillar** [comment]
>But if I don't use a lambda with `g:mucomplete#can_complete`, it throws an error.

It shouldn't matter if you use a lambda, `function()` or `funcref()`. Perhaps, you didn't get the syntax right?

>Only problem is that `g:mucomplete#user_mappings` is only read when the plugin is loaded,

Correct, but that's pretty much the only thing you must define at the global level. For instance, you may put this in your `vimrc`:

```vim
let g:mucomplete#user_mappings = { 'python_exception': "\<c-r>=python#exceptions()\<cr>" }
let g:mucomplete#empty_text_auto = 1  " To enable autocompletion after spaces
```

and the rest of your configuration in `after/ftplugin/python.vim`:

```vim
fun! s:is_exception(t)
  return a:t =~# '^\s*except\s\+$'
endfun

fun! python#exceptions()
  call complete(col('.'), ['BaseException', 'Exception', 'ArithmeticError'])
  return ''
endf

call extend(g:mucomplete#chains, { 'python': ['python_exception', 'keyn'] })

call extend(g:mucomplete#can_complete,
      \ { 'python' : {'python_exception': { t -> s:is_exception(t) }}})
```

>I'm trying the other method, but I couldn't get it to work yet.

The example above works for me (with autocompletion on): a pop-up menu for completing exceptions appears as soon as I type a space after `except`.

**Comment by lifepillar** [comment]
For a solution based on the `'list`' method, the configuration in `after/ftplugin/python.vim` might be as follows (you don't need anything special in `vimrc`):

```vim
fun! s:is_exception(t)
  return a:t =~# '^\s*except\s\+\k*$'
endfun

let s:exceptions = sort(['BaseException', 'Exception', 'ArithmeticError', 'Etc...'])

call extend(g:mucomplete#chains, { 'python': ['list', 'keyn'] })

call extend(g:mucomplete#can_complete,
      \ { 'python' : {'list': { t -> s:is_exception(t) }}})

let g:mucomplete#wordlist = extend(get(g:, 'mucomplete#wordlist', {}),
      \ { 'python': s:exceptions })
```

In this case, you need to type at least one character before the pop-up menu offers you a list of matching exceptions.

**Comment by mg979** [comment]
Ok thanks. I can close the issue since it's been sorted out.. I just wanted to remark that couple of things, then you may do as appropriate.

1. by using a filter (and not the while loops) I could have my list work without need of sorting it beforehand, and it also looks much simpler to me (but if those while loops were needed for something I don't understand, just ignore this)
```vim
fun! mucomplete#list#completefunc(findstart, base)
  if a:findstart
    return match(getline('.'), '\S\+\%'.col('.').'c')
  else
    return filter(copy(s:wordlist()), 'v:val =~ ''^''.a:base')
  endif
endfun
```

2. about updating `g:mucomplete#user_mappings`: a lot of stuff can be already defined with buffer variables, I think it would be convenient if also completion methods could be defined in this way, so that you don't need to define it in the main vimrc (just in a ftplugin), and plugins can support mucomplete by adding their own methods (impossible if the methods are never updated).

Thanks

**Comment by lifepillar** [comment]
Re your first point, a sorted list permits a much more efficient search for matches, which matters when your list is big. I do not plan to change that, as the inconvenience for the user is minor IMO (`let x = sort(words)` instead of `let x = words`).

As for your second point, I will see what can be done.

**Comment by lifepillar** [comment]
I would appreciate if you could open a new issue about extending the behaviour `g:mucomplete#user_mappings`.
