### ISSUE TITLE
Extending completions in ftplugin

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-mucomplete#146]
Since `g:mucomplete#user_mappings` is only read once, I was thinking of a buffer variable that is read to extend completions, if these are defined in a ftplugin.

In this example I'm using BufEnter because I think it runs after FileType event, and it wouldn't trigger too often. In the `extend` function I'm not using `error` or you'd get an error every time, `keep` could be used but I think it's not so important.

```vim
augroup MUcompleteUpdateCompletions
  au!
  au BufEnter * if exists('b:mucomplete_user_mappings')
        \     |   call extend(s:compl_mappings, b:mucomplete_user_mappings)
        \     | endif
augroup END
```

**Comment by lifepillar** [comment]
I don't think that a buffer variable is ideal  for the situation you describe. I have added a new function to the current master, which can be used as follows (e.g., in your `after/ftplugin/python.vim`):

```vim
call mucomplete#add_user_mapping("python_exception": "\<c-r>=python#exceptions()\<cr>")
```

Note that you cannot override existing methods this way.

**Comment by mg979** [comment]
Thanks it's working

![Imgur](https://i.imgur.com/C7dmmvm.gif)
