### ISSUE TITLE
Incompatability with vim-peekaboo

### ISSUE THREAD

**Issue by tjharman** [lifepillar/vim-mucomplete#15]
Hi,
When using junegunn/vim-peekaboo with the following settings, µcomplete breaks when I type a third letter, I end up with 3 letters on the screen, the vim jumps into normal mode and starts entering what I typed, then if I hit esc I often end up with "pumvisible()?mucomplete#yup():'' written in my buffer.

My settings: 
" µcomplete
let g:mucomplete#enable_auto_at_startup = 1
setl dictionary=/usr/share/dict/british-english-huge

Note that vim-peekaboo has a section about how it has a known issue with macros.   But I don't understand vimscript at all to know if it's something that can be fixed, or if I need to give up using peekaboo.

As soon as I disable vim-peekaboo µcomplete works as expected.

Thanks!

**Comment by lifepillar** [comment]
That's most likely because vim-peekaboo take over `<c-r>` in Insert mode. Try to put this in your `vimrc`:

```
let g:peekaboo_ins_prefix = '<c-x>'
```

**Comment by tjharman** [comment]
Thank you, this fixes the issue.

**Comment by wimstefan** [comment]
Hmm - may I ask how you fixed this? I tried the solution above (which is also mentioned in the peekaboo docs) but then peekaboo stops working completely :-/ That's a pity because this is the only reason which holds me back to use mucomplete ...

**Comment by tjharman** [comment]
You have to press ctrl-x before ctrl-r if you want the peekaboo menu to appear when pasting. If you just press ctrl-r you'll still be able to paste just won't have the menu appear.

**Comment by wimstefan** [comment]
Thank you so much! I just misunderstood the whole suggestion of the prefix :-/ ;-)
