### ISSUE TITLE
sometimes hangup when typing in string

### ISSUE THREAD

**Issue by hushicai** [lifepillar/vim-mucomplete#152]
This is a minimal vimrc:

```viml
call plug#begin('~/.plugged')
Plug 'lifepillar/vim-mucomplete'
call plug#end()

let g:mucomplete#enable_auto_at_startup = 1
" let g:mucomplete#completion_delay = 1
" let g:mucomplete#no_mappings = 1
set completeopt-=preview
set completeopt+=noselect
```
![mucomplete](https://user-images.githubusercontent.com/1249423/58743021-c8aab880-845c-11e9-8841-1648f551d243.gif)

As you can see, when i typing `test` in string, It seams that vim hang up, and i have to  force stop with `ctrl-c`.

If I turn off `enable_auto_at_startup`, and `<tab>` in string, vim also hang up.

Maybe there are something wrong when complete in string.

**Comment by lifepillar** [comment]
That looks like an issue with your omni-completion plugin. Turn off MUcomplete and instead of completing with Tab, use Ctrl-x Ctrl-o. If it still hangs then the issue does not depend on MUcomplete.

With `:setl omnifunc?` you may see which completion function is called.

**Comment by hushicai** [comment]
Yes, I use lsp completion from `ale`, omnifunc is `ale#completion#OmniFunc`.

Using `<c-x><c-o>` keep searching for a long time, but it does not block vim, i can continue typing then.

**Comment by hushicai** [comment]
`ale` supports `ale_completion_enabled` options, everything is ok, if i enable auto completion.

![ale](https://user-images.githubusercontent.com/1249423/58745211-a7f45a00-8480-11e9-9217-0f076d06207a.gif)

**Comment by hushicai** [comment]
It seams that this problem is the same as https://github.com/lifepillar/vim-mucomplete/issues/131#issuecomment-470681826.

`tsserver` get vim stuck.  but `flow lsp` is ok.

**Comment by lifepillar** [comment]
Have you tried what the section `LanguageClient-neovim` in `:help mucomplete-compatibility` suggests?

**Comment by hushicai** [comment]
Yes, i read it. But no help for my case. maybe it's due to the 'tsserver'.

**Comment by lifepillar** [comment]
Ok. You should first make sure that your setup works fine without MUcomplete (using CTRL-X CTRL-O). When it does, MUcomplete should not behave differently. If it does, feel free to reopen this issue.

**Comment by cherryramatisdev** [comment]
I still have this problem only with mucomplete, anyone has this particular bug?

maybe it's with tsserver, I don't have the same behavior with other LSPs

**Comment by lifepillar** [comment]
@cherryramatisdev Sorry for the late reply, I've seen this only now. It would help if you could provide more details about how to reproduce your issue, possibly with a minimal example., including your Vim version, OS, terminal (if you are using a terminal), and tsserver setup.
