### ISSUE TITLE
Mucomplete is automatically inserting completions without trigger

### ISSUE THREAD

**Issue by ismay** [lifepillar/vim-mucomplete#153]
This is my config: https://github.com/ismay/dotfiles/blob/master/vimrc#L172

```viml
  set completeopt=menuone,longest,noselect,noinsert
  set shortmess+=c
  let g:mucomplete#chains = { 'default': ['path', 'incl'] }
  let g:mucomplete#buffer_relative_paths = 1
  let g:mucomplete#enable_auto_at_startup = 1
```

I believe I've set up mucomplete to only autocomplete once I trigger it manually with tab. Mostly it does. However, in certain cases it'll still automatically insert a completion.

See below for example. On line 3 I start with `'./act'`:

<img width="346" alt="Screenshot 2019-07-04 at 13 30 38" src="https://user-images.githubusercontent.com/7355199/60663599-f7eb8580-9e5f-11e9-98e4-9d4b9b5ac318.png">

Then I start typing after the `t` in insert mode, and as soon as I've typed the `i` after `act`, it'll insert the `on` automatically, without me pressing tab:

<img width="432" alt="Screenshot 2019-07-04 at 13 28 41" src="https://user-images.githubusercontent.com/7355199/60663513-bb1f8e80-9e5f-11e9-858e-045f8d6b902c.png">

Is this a bug, or a problem with my configuration? It seems to be inserting the text that is common to all suggestions. I'd like to avoid that.

**Comment by ismay** [comment]
I've found actually that it does this even when there's only a single match: 

<img width="624" alt="Screenshot 2019-07-04 at 14 05 47" src="https://user-images.githubusercontent.com/7355199/60665512-f2446e80-9e64-11e9-9110-9239a59c12d7.png">

Above it was inserting the match automatically after typing `./e`, without pressing tab for completion

**Comment by lifepillar** [comment]
That’s because you have `longest` in `completeopt`. See `:help cot`.

**Comment by ismay** [comment]
Ah apologies. Thought it was probably something I was doing wrong. Thanks for the help!
