### ISSUE TITLE
This plugin is fucking ridiculous

### ISSUE THREAD

**Issue by YunYang1994** [lifepillar/vim-mucomplete#156]
## smart ass ！！！
I wanna write down the word "darknet53", But it always automatically write down "Darknet53" since this word has already appeared. The question is I can't write what I want.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/30433053/61990113-ab652580-b06c-11e9-9205-db59d6a6161e.png">

Is there anything more asshole than that in the world?

**Comment by TrySound** [comment]
Did you added one of these options?
![image](https://user-images.githubusercontent.com/5635476/61990885-f66d4180-b048-11e9-95bf-9fcb2fa811c0.png)

**Comment by lifepillar** [comment]
See `:help infercase` and `:help ignorecase`. Does properly setting those options fix your issue?

**Comment by YunYang1994** [comment]
It's too automatic. it is insane !

**Comment by YunYang1994** [comment]
> Did you added one of these options?
> ![image](https://user-images.githubusercontent.com/5635476/61990885-f66d4180-b048-11e9-95bf-9fcb2fa811c0.png)

it does not work

**Comment by lifepillar** [comment]
Does the output of `set cot` contain `longest`? If so, try to remove it:

```vim
set cot-=longest
```

**Comment by lifepillar** [comment]
If that doesn't work either, please read `:help mucomplete-troubleshooting`. In particular, try to reproduce your issue with the provided `troubleshooting_vimrc`:

```
cd path/to/mucomplete
vim -u troubleshooting_vimrc.vim
```

then report the steps needed to reproduce it. Otherwise, we'll need to keep guessing what your problem is.
