### ISSUE TITLE
Automatically expanding SnipMate snippet not working

### ISSUE THREAD

**Issue by austincrft** [lifepillar/vim-mucomplete#157]
I am trying to get SnipMate working. In the docs, it mentions I should add this code to expand snippets.

```
inoremap <plug>MyEnter <cr>
imap <silent> <expr> <plug>MyCR (pumvisible()
    \ ? "\<c-y>\<plug>snipMateTrigger"
    \ : "\<plug>MyEnter")
imap <cr> <plug>MyCR
```

When I do this, typing `<CR>` from insert mode inserts the following text.

```
(pumvisible() ? "\-\<Plug>snipMateTrigger" : "\<Plug>MyEnter")
```

**Comment by lifepillar** [comment]
I cannot reproduce it. Have you installed [SnipMate](https://github.com/garbas/vim-snipmate) as explained in their [Readme](https://github.com/garbas/vim-snipmate/blob/master/README.md)? Have you verified that SnipMate works without MUcomplete?

If so, please edit `mucomplete/troubleshooting_vimrc.vim` and paste the following at the end:

```vim
set runtimepath+=~/.vim/pack/my/start/mucomplete " CHANGE THIS

" Optionally add additional configuration below this line
" CHANGE THE FOLLOWING PATHS ACCORDING TO YOUR CONFIGURATION
" (YOU NEED ALL THESE PLUGINS):
set rtp+=~/.vim/pack/bundle/start/tlib_vim
set rtp+=~/.vim/pack/bundle/start/vim-addon-mw-utils
set rtp+=~/.vim/pack/bundle/start/snippets
set rtp+=~/.vim/pack/bundle/start/snipmate

let g:snipMate = {}
let g:snipMate['no_match_completion_feedkeys_chars'] = ''

let g:mucomplete#chains = { 'default': ['snip', 'keyn'] }

inoremap <plug>MyEnter <cr>
imap <silent> <expr> <plug>MyCR (pumvisible()
      \ ? "\<c-y>\<plug>snipMateTrigger"
      \ : "\<plug>MyEnter")
imap <cr> <plug>MyCR
```

Then, run `vim -u troubleshooting_vimrc.vim`, set the filetype to, say, C (`:set ft=c`) then type `main<tab><cr>` (`main` followed by Tab then Enter). You should see that the snippet is expanded correctly when you press Enter.

If the above doesn't help you fix your issue,  please provide step-by-step instructions to reproduce it, possibly using the `troubleshooting_vimrc.vim` above.

If the above works for you, but you still have issues with your `vimrc`, then there may be some conflicting configuration in your `vimrc`.

**Comment by austincrft** [comment]
Using the `troubleshooting_vimrc.vim`, I was able to get it working. I think you're right that it must be something in my vimrc, but I have no idea what.

**Comment by austincrft** [comment]
Okay, so it looks like [jiangmiao/auto-pairs](https://github.com/jiangmiao/auto-pairs) is conflicting with it. If I add this line to the `troubleshooting_vimrc.vim`, it is reproducible.

```
set rtp+=~/.vim/plugged/auto-pairs
```

Obviously your path will be different

**Comment by austincrft** [comment]
You can look into this if you want, but I can live without auto-pairs so I'm just going to remove the package. It seems like those instructions will conflict with other plugins that remap `<CR>`

**Comment by lifepillar** [comment]
There is a section in MUcomplete’s help about autopairs’s settings, which should work with SnipMate. Anyway, I’ll check again.

**Comment by lifepillar** [comment]
Reopening as a reminder to myself to check compatibility between autopairs SnipMate.

**Comment by lifepillar** [comment]
If you use the SnipMate + Auto Pairs combo, then these settings, instead of the above, should work:

```vim
set runtimepath+=~/.vim/pack/my/start/mucomplete " CHANGE THIS
" CHANGE THE FOLLOWING PATHS ACCORDING TO YOUR CONFIGURATION:
set rtp+=~/.vim/pack/bundle/start/tlib_vim
set rtp+=~/.vim/pack/bundle/start/vim-addon-mw-utils
set rtp+=~/.vim/pack/bundle/start/snippets
set rtp+=~/.vim/pack/bundle/start/snipmate
set rtp+=~/.vim/pack/bundle/start/auto-pairs

" Optionally add additional configuration below this line
let g:snipMate = {}
let g:snipMate['no_match_completion_feedkeys_chars'] = ''

let g:mucomplete#chains = { 'default': ['snip', 'keyn'] }

let g:AutoPairsMapSpace = 0
imap <silent> <expr> <space> pumvisible()
      \ ? "<space>"
      \ : "<c-r>=AutoPairsSpace()<cr>"

let g:AutoPairsMapCR = 0

inoremap <plug>MyEnter <cr>
imap <silent> <expr> <plug>MyCR (pumvisible()
      \ ? "\<c-y>\<plug>snipMateTrigger"
      \ : "\<plug>MyEnter<Plug>AutoPairsReturn")
imap <cr> <plug>MyCR
```

I have updated MUcomplete's documentation accordingly.
