### ISSUE TITLE
Can I search by the start of each word in a camelCase variable?

### ISSUE THREAD

**Issue by rynoV** [lifepillar/vim-mucomplete#158]
For example, if I have the variable name `thisIsAVariable` and I type `tIAV` and trigger completion, can I configure this plugin to recognize that? Same for snake_case.

**Comment by lifepillar** [comment]
The algorithm used to complete a word is (mostly) orthogonal to the features of this plugin. So, if a completion function exists that is able to expand `tIAV` to `thisIsAVariable`, then MUcomplete will happily use it (e.g., the [Ledger](https://github.com/ledger/vim-ledger.git) plugin has a similar feature, whereby typing, say, `A:Ex:F` may expand to `Assets:Expenses:Food`—and it works fine with MUcomplete).

Out of the box, no such function is available, though, nor is it in the scope of this project.  One possibility is that you define it yourself: see `complete-functions` for the details (you may also get inspiration from the above mentioned Ledger plugin).
