### ISSUE TITLE
Ultisnip completion method - add to chain

### ISSUE THREAD

**Issue by josefson** [lifepillar/vim-mucomplete#16]
It would be super cool if we had a Ultisnip completion method to add to our chain. I have so many snippets created for different cases with a little comment added to the snippets and i got so lazy using YCM and such where i could cycle through the possible snippets that i would really love this kind of feature, if possible.

**Comment by lifepillar** [comment]
That's an interesting idea, but it might get extremely tricky to implement—the tricky part being how completion should work for snippets. How does it work in other completion plugins? What do they insert when you select an UltiSnips entry? What happens when you change your selection?

Also, I'm wondering whether µcomplete is the best place to put this feature. I see that, for NeoComplete/Deoplete, the bulk of the code is inside UltiSnips. I could easily add an `'ulti'` completion method that calls a function in UltiSnips: that's would be ideal for me. @Sirver, maybe you can give us a hint on the best approach to follow?

That said, first I have to solve https://github.com/lifepillar/vim-mucomplete/issues/11.

**Comment by lifepillar** [comment]
To be more specific, something along these lines should work:

```
" In your vimrc or, ultimately, inside µcomplete:
let g:mucomplete#user_mappings = {'mon' :
  \ ["\<c-r>=ultisnips#mucomplete#gather_candidate()\<cr>",
  \ "\<c-r>=ultisnips#mucomplete#gather_candidate()\<cr>"]
  \ }

" Somewhere in UltiSnips:
fun ultisnips#mucomplete#gather_candidates(...)
  " Some code that would likely call complete()
endf
```

**Comment by chenoweth** [comment]
I'm not sure this is what you're looking for, but at the end of `:h UltiSnips#SnippetsInCurrentScope`, they seem to talk about a function similar to `ultisnips#mucomplete#gather_candidate()`. By tweaking it a little, it can return a list of all the possible `tab_triggers` for the current buffer:

```
function! GetAllSnippets()
  call UltiSnips#SnippetsInCurrentScope(1)
  let list = []
  for [key, info] in items(g:current_ulti_dict_info)
    let parts = split(info.location, ':')
    call add(list, {
      \"key": key,
      \"path": parts[0],
      \"linenr": parts[1],
      \"description": info.description,
      \})
  endfor
  return map(list, 'v:val["key"]')
endfunction
```

**Comment by chenoweth** [comment]
I had a look at the example given in `:h complete()` and tweaked it to get a mapping on the `<F5>` key which would give a menu suggesting possible `tab_triggers`:

```
fu! CompleteSnippets() abort
    call UltiSnips#SnippetsInCurrentScope(1)
    let t          = matchstr(strpart(getline('.'), 0, col('.') - 1), '\S\+$')
    let candidates = []
    for [trigger, description] in items(map(copy(g:current_ulti_dict_info), 'v:val["description"]'))
        call add(candidates, {'word': trigger, 'menu': description})
    endfor
    call filter(candidates, 'v:val["word"] =~ "^".t')
    call complete(col('.')-1, candidates)
    return ''
endfu

ino <F5> <C-R>=CompleteSnippets()<CR>

```

It seems to work. So maybe something like this:

```
fu! GatherCandidates() abort
    call UltiSnips#SnippetsInCurrentScope(1)
    let t          = matchstr(strpart(getline('.'), 0, col('.')), '\S\+$')
    let candidates = []
    for [trigger, description] in items(map(copy(g:current_ulti_dict_info), 'v:val["description"]'))
        call add(candidates, {'word': trigger, 'menu': description})
    endfor
    return filter(candidates, 'v:val["word"] =~ "^".t')
endfu
```

… could be useful as an example of `ultisnips#mucomplete#gather_candidate()`.

**Comment by josefson** [comment]
@lifepillar There are 2 plugins which have this feature implemented that i know of, one being YouCompleteMe, and the other being [completor.vim (This link is for the code integration the author used, although his plugin is highly python based)](https://github.com/maralla/completor.vim/blob/793e26ed42a3e84bb79b9d592fdfb7ed4b4c7737/pythonx/completers/common/ultisnips.py).


- It gets the snippet's trigger list and  comment, for the completion word, from UltiSnips.
![Image of completion list] (https://i.imgur.com/Sgqdock.jpg)

- We can cycle through the entire completion list with <tab> <s-tab> or <c-p> <c-n>, just like your plugin. 

- Once we selected the snippet we want to use, either by tabbing to it, or by finishing typing it, we hit UltinSnipets trigger key, which would insert the snippet.
![Image after trigget] (https://i.imgur.com/652L3pe.jpg)

**Comment by lifepillar** [comment]
Thanks for the feedback @chenoweth @josefson. Now I have a better understanding of how it should work. It shouldn't be too difficult to implement.

**Comment by lifepillar** [comment]
I have added support for UltiSnips via an `'ulti'` method (not enabled by default). Please check out the current master and let me know how it works for you (but keep in mind that https://github.com/lifepillar/vim-mucomplete/issues/11 is not fixed yet).

**Comment by josefson** [comment]
Just tested it out and works great. I don't know what #11 is about tho. I could recreate it's issue, but it works fine with python files under similar circumstances.
Now, I'm closing this issue-enhancement since what i did request was added and it seems to be working fine.
Thanks, it is a great plugin you have created.
