### ISSUE TITLE
Resetting completion when there are no results

### ISSUE THREAD

**Issue by mg979** [lifepillar/vim-mucomplete#160]
I don't know if it depends on some of my settings, but I think it doesn't. Basically, I don't have `c-p` in my chains, but often, when I don't get any completion with tab and there is no visible popup, I try `<C-P>` completion. But it doesn't work, I have to press `<C-G><C-G>` first (or `<C-E>`), to reset completion. Otherwise vim still thinks it's in completion mode, even if there is no popup because there are no results. Is it possible to have completion automatically reset, if there are still no results after the last chain has been tried?

To reproduce, use any filetype and do

    :let g:mucomplete#chains[&ft] = ['keyn']

Then type a partial that gives results with `<C-P>`, but not with tab.

- press tab, no results
- press `<C-P>`, no results
- press `<C-G><C-G>`
- press `<C-P>` again, completion works

Note that this gets even worse with `MUcompleteAutoOn`, because then `<C-P>` never works alone (if mucomplete is trying completions with no results).

**Comment by lifepillar** [comment]
Thanks for the detailed report, which I can reproduce. I'll look into it.

**Comment by mg979** [comment]
I could fix it locally just by doing
```diff
-  return ''
+  return s:ctrlx_out
```
at https://github.com/lifepillar/vim-mucomplete/blob/92f0206dae54439bec6503c649263e38167011a9/autoload/mucomplete.vim#L249

**Comment by lifepillar** [comment]
Thanks for looking into it. I’ll check asap.

**Comment by lifepillar** [comment]
Your proposed fix looks good to me. I have implemented it. Thanks!

**Comment by mg979** [comment]
Thanks! By the way it's technically a vim bug, because the same happen in vim (calling `<c-p>` doesn't work after a `<c-x>...` that yields no results), only that with `MUcompleteAutoOn` this became the rule rather than the exception, and it's nice to have it fixed anyway :).

**Comment by lifepillar** [comment]
>it's technically a vim bug

Good to know. Maybe worth reporting?

**Comment by mg979** [comment]
Maybe I'll report it.
