### ISSUE TITLE
The buffers area does not close automatically after auto-completion

### ISSUE THREAD

**Issue by Ni1fheim** [lifepillar/vim-mucomplete#162]
My `.vimrc` Configuration file like this:
```vim
" mucomplete
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#completion_delay = 49 " make sure LanguageClient work
let g:mucomplete#reopen_immediately = 0 " make sure LanguageClient work
let g:mucomplete#msg#short_methods = 1
set completeopt+=menuone,noinsert
set shortmess+=c   " Shut off completion messages
```
I haven't used any other autocomplete plugins, just use mucomplete with LanguageClient-neovim.
When I typing a function / or other structure,  the description of the function appears in the buffer area, but the buffer area is not closed after auto-complete. Like the image blow:
![image](https://user-images.githubusercontent.com/31804253/71541753-bc59f000-2998-11ea-8cc6-a4c261358d90.png)

How can I automatically close this buffer after autocomplete？

Thank you!

**Comment by Ni1fheim** [comment]
or How can I start the buffers manually instead of opening it automatically？

**Comment by lifepillar** [comment]
MUcomplete does not control the preview window. You most likely need to set an option of LanguageClient-neovim. Check `:help g:LanguageClient_hoverPreview ` and `:help g:LanguageClient_useFloatingHover`. Let me know if that helps.

**Comment by lifepillar** [comment]
Btw:

>`let g:mucomplete#msg#short_methods = 1`

Perhaps, you meant to use this instead:

```
MUcompleteNotify 1
```

The value of `g:mucomplete#msg#short_methods` should be a Dictionary that maps each completion method to a message you'd like to be displayed.

**Comment by Ni1fheim** [comment]
Thank you for your reply，
I read the documentation for LanguageClient-neovim. 
Try adding the following configuration to the `.vimrc`

```vim
let g:LanguageClient_hoverPreview = "Never"
let g:LanguageClient_useFloatingHover = 0
let g:LanguageClient_usePopupHover = 0
```

But it doesn't work，🙁
Maybe I should submit an issue with LanguageClient-neovim？

**Comment by Ni1fheim** [comment]
Hi, I found the solution.
Add the following configuration to the `.vimrc`
```vim
set completeopt-=preview

nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
nnoremap <silent> <C-k> :call LanguageClient#textDocument_definition()<CR>
```

Shortcuts will work even without a preview window.
