### ISSUE TITLE
Cannot use <tab> to jump parameters after autocomplete.

### ISSUE THREAD

**Issue by Ni1fheim** [lifepillar/vim-mucomplete#163]
Hi, 
when MUComplete and LSP work together, the function can be completed automatically, but this is the case after completion:
![image](https://user-images.githubusercontent.com/31804253/71559443-032f0f00-2a99-11ea-9f29-4e2839ca091f.png)
![image](https://user-images.githubusercontent.com/31804253/71559450-235ece00-2a99-11ea-9c71-345f5f4406a2.png)
How can I achieve automatic jump parameters and edit the whole block?
Thank you!

**Comment by lifepillar** [comment]
Can you show your settings in `vimrc`? Also, how have you configured LSP?

**Comment by Ni1fheim** [comment]
I haven't used any other autocomplete plugins, just use mucomplete with LanguageClient-neovim., my `.vimrc`  configuration is as follows：

![image](https://user-images.githubusercontent.com/31804253/71641232-48d71c00-2cd3-11ea-93cb-88dcc981c288.png)
![image](https://user-images.githubusercontent.com/31804253/71641268-cbf87200-2cd3-11ea-9505-177eeda2e2e3.png)

Same thing happened on snipmate.

**Comment by lifepillar** [comment]
Ok, I can reproduce this. I don't think MUcomplete can do much about that, because the behavior is the same if you disable MUcomplete and use CTRL-X CTRL-O to complete. You should ask in LanguageClient-neovim repo how you can put the cursor on the parameters.

**Comment by lifepillar** [comment]
For SnipMate, have you tried the mapping suggested in its documentation?

```vim
imap <C-J> <Plug>snipMateNextOrTrigger
```

Then, use CTRL-J to jump to the next parameter. I have tried that with a `for` loop and it works. With MUcomplete's autocompletion on, type `fo`, then Tab to choose the `for` or `forr` entry, then Enter to expand the snippet (requires a bit of configuration, see MUcomplete's help), then CTRL-J to jump to the next parameters.

If you don't use Tab to trigger autocompletion, you may associate the above behavior to Tab itself:

```vim
imap <expr> <tab> pumvisible() ? "\<c-n>" : "\<plug>snipMateNextOrTrigger"
```

Shift-tab is already mapped to move backwards, it seems.

**Comment by Ni1fheim** [comment]
OK, it works for me.
Thank you!
