### ISSUE TITLE
Additional ( while completing python keywords

### ISSUE THREAD

**Issue by oponkork** [lifepillar/vim-mucomplete#164]
Say if I have the following python code
```python
def square(x):
    return x**2

xsq = square(2)
```
And then if I type `xs` and try to complete, I end up with `xsq(` instead of `xsq`. Here's an [asciinema](https://asciinema.org/a/WtXi2HyTYvPN09w9ITyFhfDE0), showing the same. This only happens for keywords which are return values of defined functions.

**Comment by oponkork** [comment]
Something which I noticed. The bug goes away if I remove `omni` from the completion chain.

**Comment by lifepillar** [comment]
I think that it depends on the omni-completion plugin. If that is the case, you should get the additional parenthesis also when you disable MUcomplete and manually trigger omni-completion with CTRL-X CTRL-O.

**Comment by oponkork** [comment]
Yes, just checked that is the case. Should I close it and open an issue with vim/neovim?

**Comment by lifepillar** [comment]
I think so. MUcomplete just wraps around CTRL-X CTRL-O, so as long as the behaviour of MUcomplete is the same as manually triggering omni-completion, MUcomplete's behaviour has to be considered correct.
