### ISSUE TITLE
Question: mucomplete is bringing up autocomplete menu after typing brackets for Go, how to fix this?

### ISSUE THREAD

**Issue by JoeHTR** [lifepillar/vim-mucomplete#165]
Hi guys -

I've been playing around with setting up a Go environment with mucomplete.  Would someone be able to help me with an odd autocomplete issue?

Since I'm a total newbie to Go, I had been following [this tutorial](https://quii.gitbook.io/learn-go-with-tests/go-fundamentals/hello-world) when I encountered this issue. 

EDIT: Forgot to say - I'm using vim-go with mucomplete. 

**What's happening**
When I type in `(`, `{` the autocomplete menu pops up... so if I'm doing something like an if statement in Go or create a new function, this happens.

`(` example:
![image](https://user-images.githubusercontent.com/44413051/72180631-8b74b480-33b5-11ea-9539-c211dd73d312.png)

`{` example:
![image](https://user-images.githubusercontent.com/44413051/72180684-a810ec80-33b5-11ea-9be3-6a5f54a6bc9d.png)

This is kind of annoying because I have to exit out of the autocomplete mode with exit or `ctrl-c` before I can continue typing.  If I press `Enter` the first item from the menu will be inserted, which is not what I want.

I've been using mucomplete with C# and OmniSharp-Vim successfully for the past year after NickSpoons suggested mucomplete for me in https://github.com/OmniSharp/omnisharp-vim/issues/424, and on C# side **this does not happen**.
![image](https://user-images.githubusercontent.com/44413051/72181192-ccb99400-33b6-11ea-9a0d-baeeda5fb1fa.png)

My .vimrc / cs.vim / go.vim sections that are relevant to mucomplete:

.vimrc:
```
augroup csharp_settings
    autocmd!
    " C# only - Show type information automatically when the cursor stops moving
    autocmd CursorHold *.cs call OmniSharp#TypeLookupWithoutDocumentation()

    " Go and C# - Auto remove preview window after autocomplete
    autocmd CompleteDone *.cs,*.go if pumvisible() == 0 | pclose | endif
augroup END
```

cs.vim and go.vim (yes, I'm using the exact same thing for mucomplete on both files):
```
" mucomplete trigger omni completion after a dot or after two characters
let g:mucomplete#enable_auto_at_startup = 1
MUcompleteAutoOn

" source: https://github.com/lifepillar/vim-mucomplete/issues/46
let g:mucomplete#can_complete = {
  \ 'default': {
  \    'omni': { t -> strlen(&l:omnifunc) > 0 && t =~# '\%(\k\k\|\.\)$' }
  \    }
  \  }
```
Looking at comments on issue 46 where I got that `let g:mucomplete#can_complete` block - lifepillar's explanation says omni completion would be triggered on two keywords or a dot - wondering why `(` and `{` triggering this then...? Especially `{` after function declaration or if block declaration because there would be a space before `{`...

**Comment by lifepillar** [comment]
>[MUcomplete's] omni completion would be triggered on two keywords or a dot

Correct. By default, on typing `{` or `(` MUcomplete does absolutely nothing.

Vim-go offers its own support for completion. You are triggering vim-go's completion mechanism.

**Comment by lifepillar** [comment]
Unless the Go filetype has `{` and `(` in `iskeyword` (which is unlikely, but just to be sure you might check that with `:setlocal iskeyword` while in a Go buffer).

**Comment by JoeHTR** [comment]
> Correct. By default, on typing `{` or `(` MUcomplete does absolutely nothing.
> 
> Vim-go offers its own support for completion. You are triggering vim-go's completion mechanism.

Hmm, @lifepillar  could you help me clarify that my understanding is correct here?  

My understanding was that vim-go offers completion capabilities, but with my setup it is mucomplete that is responsible for _triggering_ vim-go's capabilities - specifically, when I am pressing two key characters or a dot.  

I guess what I meant was I was confused as to why typing in a space and then a `{` as shown on the second screenshot would make mucomplete trigger vim-go's completion... unless space and `{` were both keywords in Go somehow...?  Because in C# with omnisharp-vim everything works completely fine. 

I'll go ahead and see `:set local iskeyword` shows when I get back to work on Monday and see what happens thanks :)

**Comment by lifepillar** [comment]
I am not familiar with vim-go, but I may give it a try. What I’m suggesting is that vim-go might also trigger completion by default, which would overlap with MUcomplete’s behavior. Do you get any completions if you disable MUcomplete?

**Comment by lifepillar** [comment]
I have installed vim-go, but I cannot reproduce your issue. Perhaps, you may try to add the necessary vim-go configuration to the `troubleshooting-vimrc.vim` file in MUcomplete folder and run `vim -u troubleshooting-vimrc.vim` and try to narrow down your issue.

**Comment by JoeHTR** [comment]
Correct - without mucomplete (if I comment it out of the vim plug or just get rid of the block below from my `cs.vim` or `go.vim` files)
```
let g:mucomplete#enable_auto_at_startup = 1
MUcompleteAutoOn
```
I don't get autocompletion - I have to trigger the omni completion myself.  

I went through vim-go's documentation again, and everything I could find suggested that vim-go provides completion through omnifunc, but you as the user is responsible for either triggering it yourself or using another plugin for autotriggering...
https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L131

I'll go ahead and try to play around my .vim files more when I get back to work on Monday, was just curious if this was a known issue because I found similar, but not quite the same issues when I searched through here...  thanks for the help so far.

**Comment by lifepillar** [comment]
Ok, I’ll dig deeper.

**Comment by JoeHTR** [comment]
Ok... this is weird.  

I had some free time so setup a brand new env completely from scratch at home, and on this env I couldn't reproduce this issue. `:setlocal iskeyword` was also giving me `@,48-57,_,192-255` on a go buffer, which based on googling should be fine?

On my work machine (where this was happening) last Friday I had tried doing various things like disabling mucomplete, etc to no avail... 

Anyway, the fact that you nor my new environment couldn't reproduce this issue tells me that I must've screwed something up on my work env, and the root cause likely isn't on mucomplete - I'll close this issue.
