### ISSUE TITLE
E227: Mapping already exists for <80>kB

### ISSUE THREAD

**Issue by trickeyd** [lifepillar/vim-mucomplete#167]
Hi - just started using mucomplete and loving it! I've tried virtually everything else and this wins for my needs hands down.

The only issue is that on startup I get the following error:

```
Error detected while processing /Users/jamestrickey/.vim/bundle/vim-mucomplete/plugin/mucomplete.vim:
line   29:
E227: Mapping already exists for <80>kB
```

I have found that that mapping relates to backspace. I'm not mapping it to anything myself, so it must be a plugin clash. How can I avoid this?

Many thanks!

**Comment by lifepillar** [comment]
MUcomplete does not map backspace. Perhaps it’s a conflict between other plugins?

I suggest that you follow `:help mucomplete-troubleshooting`. In particular, try running Vim with the provided `troubleshooting_vimrc.vim` (found in MUcomplete’s folder), adding a plugin at a time until you reproduce the issue.

**Comment by trickeyd** [comment]
Hey thanks for you reply - I looked at line 29 as it said in the error and it is this:
`    imap <unique> <s-tab> <plug>(MUcompleteBwd)
`
Which makes sense as I have mapped that for something else... don't know where I got backspace from.

There are some if statements, so I'm assuming I can override this mapping from my .vimrc - how would i do this? 

Sorry - I'm not very familiar with vim script.

**Comment by lifepillar** [comment]
The simplest solution is to map `<plug>(MUcompleteBwd)` in your `vimrc` to something different from `<s-tab>`, e.g. to use an up arrow:

```
imap <unique> <up> <plug>(MUcompleteBwd)
```

Replace `<up>` with the desired key mapping.

If you want to suppress *all* MUcomplete's mappings, then put this line in your `vimrc`:

```
let g:mucomplete#no_mappings = 1
```

Then you will be responsible to define the mappings you need yourself, similarly to what I have done above. See `:help mucomplete-mappings` and `:help mucomplete-plugs` for more information.

**Comment by lifepillar** [comment]
Note that MUcomplete works just fine with all mappings suppressed (you just need to turn on autocompletion), with one limitation: you won't be able to cycle through different completion methods when the pop-up menu is open (which is accomplished by `<c-j>` and `<c-h>` by default).

I'd recommend that you keep all mappings, though (perhaps redefining those that have a conflict) to be able to use all the functionality that MUcomplete provides.

**Comment by trickeyd** [comment]
Thank you so much. This was a really helpful answer.

As I said, your plugin is easily the best compromise I've found between completion and light weight. I'm really enjoying it.

Godspeed!
