### ISSUE TITLE
Can't insert tab even when no suggestions are shown

### ISSUE THREAD

**Issue by prati0100** [lifepillar/vim-mucomplete#168]
Hi,

When my cursor is at the end of a word and I try to hit \<Tab\>, nothing happens. No suggestions show (because there are none to show), and the tab character doesn't get inserted. I have to hit \<C-V\>\<Tab\> to insert a tab which is a tad bit annoying.

Example:

![2020-01-17-153450_89x26_scrot](https://user-images.githubusercontent.com/8817931/72603696-85e01700-393f-11ea-9668-9d9a3e11ecb3.png)

When I try to press the tab here, nothing happens. The tab character is not inserted and no completion menu is shown.

I have set `completeopt=menuone,noselect`

Is it possible to fix this problem?

**Comment by lifepillar** [comment]
I have added a new option to enable the behaviour you have requested. Upgrade to the current master and try:

```vim
let g:mucomplete#tab_when_no_results = 1
```

Feel free to reopen if this does not work as expected.

**Comment by prati0100** [comment]
Thanks for taking this on, but I have the same behavior as before even after. Tabs are not inserted when there are no suggestions.

Mucomplete related settings I have:

```vimrc
set completeopt+=menuone
set completeopt+=noselect
set previewheight=2
set shortmess+=c
set dictionary+=spell

let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#tab_when_no_results = 1
```

**Comment by lifepillar** [comment]
Sorry, there was a typo in the name of the option. Please update to the current master and try again.

**Comment by prati0100** [comment]
Sorry for the late response. It works now. Thanks.
