### ISSUE TITLE
Is there a way to confirm manually?

### ISSUE THREAD

**Issue by evanliuty** [lifepillar/vim-mucomplete#169]
I am working with CSS and sometime for example I type something, basically define something new, mucomplete automatically confirms an existing word which stops me from creating new variables which is quite annoying. I did not find a way other than disabled it completely. Thanks!

**Comment by lifepillar** [comment]
What's the value of `:set completeopt`? Does it contain `longest`? If so, try:

```vim
set completeopt-=longest
```

If that does not solve your issue, please read `:help mucomplete-troubleshooting`. In particular, add minimal settings to `troubleshooting-vimrc.vim` (in MUcomplete's folder) then run Vim with `vim -u troubleshooting-vimrc.vim`. If you can still reproduce your issue, please post the relevatn configuration.

**Comment by evanliuty** [comment]
Thanks it works. Seems I used the python setting for everything. :D
