### ISSUE TITLE
Insert braces automatically on methods completion

### ISSUE THREAD

**Issue by Shatur95** [lifepillar/vim-mucomplete#171]
Hi! I configured MUcomplete with [nvim-lsp](https://github.com/neovim/nvim-lsp) and it works awesome, but I miss the automatic insertion of brackets for functions after auto-completion :(
Tested with Python and GDScript. Is this LSP issue?

**Comment by Shatur95** [comment]
Yes, I read that this is omnifunc issue.

**Comment by virus-found** [comment]
Will you elaborate on that or give a link to the omnifunc issue? I'm interested in solving this as well.

**Comment by Shatur95** [comment]
I tried to find a link where there was a similar question and there they answered that this is an LSP problem, but I just can not :(

I [submitted](https://github.com/neovim/neovim/issues/11922) an issue to Neovim but it was closed.

Now I decided to try [vsnip](https://github.com/hrsh7th/vim-vsnip), but waiting for [implementation for a functions](https://github.com/hrsh7th/vim-vsnip-integ/issues/10).
