### ISSUE TITLE
Disable completion in buffer?

### ISSUE THREAD

**Issue by comfortablynick** [lifepillar/vim-mucomplete#173]
Is there any mechanism to disable completion in a buffer? Other plugins I've used have this, such as `b:coc_suggest_disable`.

I've been using vim-clap and noticed that in a filetype where I'm using mucomplete, it wreaks havoc with clap when I'm in the clap buffer. There's no good way I can think of to disable it on my end for certain buffers/filetypes. If I use `MUcompleteAutoOff`, clap functions correctly.

I used an autocommand to disable mucomplete when entering the clap window, but then I have to re-enable manually when closing it. Either way, that seems like a really hacky solution.  Here is how clap is handling coc.nvim, since it provides a buffer variable to disable completion:

https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/floating_win.vim#L203

EDIT: this solution seems to work so far using autocommands clap provides:

```vim
augroup clap_on_enter_exit
    autocmd!
    autocmd User ClapOnEnter call s:clap_on_enter()
    autocmd User ClapOnExit call s:clap_on_exit()
augroup END

function! s:clap_on_enter() abort
    if exists('g:loaded_mucomplete')
        MUcompleteAutoOff
        let s:mucomplete_disabled = 1
    endif
endfunction

function! s:clap_on_exit() abort
    if exists('s:mucomplete_disabled')
        MUcompleteAutoOn
        unlet s:mucomplete_disabled
    endif
endfunction
```
I'm sure there's a better way. :)

**Comment by lifepillar** [comment]
You may execute `MUcompleteAutoOn` unconditionally. Other than that, I think that the way you are doing it is fine. I believe that this kind of customization is better left on the user-side.

**Comment by comfortablynick** [comment]
Ok, fair enough. Thanks for the response.
