### ISSUE TITLE
Feature request: regex based scoped completions chains

### ISSUE THREAD

**Issue by vigoux** [lifepillar/vim-mucomplete#174]
Hi, 
Firt of all, I just discovered mucomplete, and started to use it, and I am loving every single part of it so far, so thank you very much for this awesome plugin !

During my configuration of the plugin, I discovered your scoped chains feature (which is one of the neattest features).

The only thing I want to ask is it is possible to have a kind of regex based scoped completion chain ?

Here is an example of what I mean :
```vim
" Without regex
let g:mucomplete#chains = {
			\ 'default': ['tags', 'nsnp'],
			\ 'rust' : {
			\		"default" : ['omni', 'nsnp'],
			\		"rustString" : [],
			\		"rustCommentLine" : [],
			\		"rustCommentBlock" : [],
			\		"rustCommentLineDoc" : [],
			\		"rustCommentBlockDoc" : []
			\		},
			\ 'c' : {
			\		"cComment" : [],
			\		"cString" : []
			\		}
			\ }

" With regex
let g:mucomplete#chains = {
			\ 'default': ['tags', 'nsnp'],
			\ 'rust' : {
			\		"default" : ['omni', 'nsnp'],
			\		"rustString" : [],
			\		"rustComment.*" : [],
			\		},
			\ 'c' : {
			\		"cComment" : [],
			\		"cString" : []
			\		}
			\ }
```
It might be really nicer to use this way, and if there is not to many performance problems with this, a real game changer !

**Comment by vigoux** [comment]
After some tests, I came up with this, which provides the desired functionality, I did not faced any performance issues btw.

The great thing is that, with chains getting smaller, the loop is not that bad, I will try to find a better way though.

Hope this helps.
```diff
diff --git a/autoload/mucomplete.vim b/autoload/mucomplete.vim
index 2c6e6fd..ae6b690 100644
--- a/autoload/mucomplete.vim
+++ b/autoload/mucomplete.vim
@@ -1,6 +1,7 @@
 " Chained completion that works as I want!
 " Maintainer: Lifepillar <lifepillar@lifepillar.me>
 " License: This file is placed in the public domain
+" vim: et ts=2 sts=2 sw=2

 let s:save_cpo = &cpo
 set cpo&vim
@@ -314,10 +315,18 @@ endf
 " If the argument is a completion chain (type() returns v:t_list), return it;
 " otherwise, get the completion chain for the current syntax item.
 fun! s:scope_chain(c)
-  return type(a:c) == 3
-        \ ? a:c
-        \ : get(a:c, synIDattr(synID('.', col('.') - 1, 0), 'name'),
-        \       get(a:c, 'default', g:mucomplete#chains['default']))
+  if type(a:c) == 0000
+    return a:c
+  else
+    let l:current_syntax = synIDattr(synID('.', col('.') - 1, 0), 'name')
+    for l:item in items(a:c)
+      if l:item[0] =~? l:current_syntax
+        return l:item[1]
+      endif
+    endfor
+
+    return get(a:c, 'default', g:mucomplete#chains['default'])
+  endif
 endf

 " Precondition: pumvisible() is false.
```

**Comment by vigoux** [comment]
After some profiling, it seems that the solution wiht a for loop is the best I can get.

Furthermore, with the original implementation (without regexes), running the modified function took 1,75 microsec (on average), and with this implemetentation, it now takes 2.5microsec

**Comment by lifepillar** [comment]
Thanks for the code and the benchmarking. I'll take a look!

**Comment by vigoux** [comment]
I edited the code above, because the comparison inside the loop was false.
