### ISSUE TITLE
Editing single-quoted strings crashes

### ISSUE THREAD

**Issue by NeilGirdhar** [lifepillar/vim-mucomplete#176]
To reproduce:

1. vim a.py
2. Type `i` to enter insert mode, then
```
'a'
``` 
then escape to exit insert mode.
3. Type `h` to go left so that the cursor is over the `a`.
4. Type `i` to enter insert mode, then `a_`.

My vimrc:
```
set nocompatible
filetype off
set runtimepath+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'lifepillar/vim-mucomplete'

call vundle#end()
filetype plugin indent on

let g:mucomplete#enable_auto_at_startup = 1
```

**Comment by lifepillar** [comment]
That's likely a Python configuration error. I get 

```
Error detected while processing function python3complete#Complete:
line   35:                                                                                                     
  File "<string>", line 1
    vimpy3complete('a', ''a_')
                           ^
SyntaxError: invalid syntax
```

likely because my Vim is built with `-python +python3` and I don't have Python 3 in my `PATH`.

**Comment by NeilGirdhar** [comment]
Sorry to waste your time, but there was some leftover configuration in `~/.vim/ftplugin` that was interfering with the autocomplete.  I removed it, and everything works now.  I didn't explore why it was breaking.

**Comment by NeilGirdhar** [comment]
This is happening to me again, but only in gvim.  Have you tested it in the graphical editor?

**Comment by lifepillar** [comment]
I can reproduce it without MUcomplete. Just type CTRL-X CTRL-O after step 4.

This looks like a bug in `python3complete#Complete()`, which invokes:

```
vimpy3complete('a', ''a_')
```

Have you tried contacting its maintainer?

**Comment by NeilGirdhar** [comment]
Oh, wait, that's not you?  Sorry, who's the maintainer?

**Comment by NeilGirdhar** [comment]
Okay, sorry for the bother!  Thanks a lot: https://github.com/vim/vim/issues/5838
