### ISSUE TITLE
How to make the completion go from `line' to the `keyn' automatically?

### ISSUE THREAD

**Issue by psprint** [lifepillar/vim-mucomplete#185]
Hi,
I have the following setup:
```vim
let g:mucomplete#user_mappings = { 'myline' : "\<c-x>\<c-l>", 'myomni' : "\<c-x>\<c-o>",
                                \ 'myfile' : "\<c-x>\<c-f>" }
let g:mucomplete#chains = { 'zsh' : ['myfile', 'myline', 'keyn', 'myomni'] }
"let b:mucomplete_chain= ['file', 'line', 'keyn', 'omni']
let g:mucomplete#completion_delay = 0

call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-easy-align'
Plug 'farmergreg/vim-lastplace'
Plug 'Valodim/vim-zsh-completion'
Plug 'lifepillar/vim-mucomplete'
call plug#end()
```

I observe some glitches when completing, [asciicast1 (successful)](https://asciinema.org/a/xytncHBzAVZmzO8Dr6kaNGxhL), [asciicast2 (failures)](https://asciinema.org/a/8CX8VfR5FipMtoJKzFkhExYOy).

I must say that while mucomplete is a very unique and useful plugin, it lacks a slight but a certain amount of robustness for good usage.

**Comment by lifepillar** [comment]
Please see https://github.com/lifepillar/vim-mucomplete/issues/182#issuecomment-659624885 and `:help mucomplete-methods`. If you want to use any of the completion methods provided by Vim, please use the corresponding name (`"line"`, `"omni"`, etc.) already provided by MUcomplete.

RE the subject, with the popup menu open, you may type CTRL-J and CTRL-H (mappings configurable) to switch between the different completion methods in your chain, among those that have completions to offer.

>I must say that while mucomplete is a very unique and useful plugin, it lacks a slight but a certain amount of robustness for good usage.

I try to make the plugin work as advertised, which may not be what suits you best. Fortunately, there is no lack of choice for completion plugins in Vim land :-)

**Comment by psprint** [comment]
Thanks. I have been convinced to try again the stock-chains with pleasant effects :) However, the C-H and C-J bindings don't work: the first one closes the menu popup and moves the cursor 2 columns left, while C-J closes the menu and moves cursor 1 left 1 down, as presented on this [asciicast](https://asciinema.org/a/OlxcNLIzEMfBYM8JhlmsTa0mk).

**Comment by lifepillar** [comment]
What’s the output of `:verbose imap <c-h>` and `:verbose imap <c-j>`?

**Comment by psprint** [comment]
Ah, I've forgot that I've bound them. Thanks, the switching now works.
