### ISSUE TITLE
mucomplete, vimwiki and TAB key

### ISSUE THREAD

**Issue by arozehnal** [lifepillar/vim-mucomplete#186]
I a running Vim 8.2 on Windows. mucomplete works me fine, but when I edit vimwiki files I'm not able to 
invoke mucomplete due remaping TAB key by vimwiki.
I understand this is collision Mapping, but  I don't know how to solve it :-(
I examined the documentation of both plugins, but I did my best to deactivate TAB for vimwiki plugin. 

Any suggestion how to put mucomplete  into operation for vimwiki files?

**Comment by lifepillar** [comment]
You may create `~/.vim/after/ftplugin/vimwiki.vim` (creating the intermediate directories if necessary) with the following content:

```vim
imap <buffer> <tab> <plug>(MUcompleteFwd)
imap <buffer> <s-tab> <plug>(MUcompleteBwd)
```

It would be better to configure vimwiki not to override an existing mapping, though. I don't know if that is possible, as I am not familiar with vimwiki.

**Comment by arozehnal** [comment]
Your advice help me - thank you.   :-)
