### ISSUE TITLE
enable_auto_at_startup generates at E085 error in auto#enable

### ISSUE THREAD

**Issue by richtong** [lifepillar/vim-mucomplete#191]
When I set the recommended

```
let g:mucomplete#enable_auto_at_startup = 1
```

Wth Vim 8.2 version 1-2550, I get the startup error

```
Error detected while processing /Users/rich/.vim/bundle/vim-mucomplete/plugin/mucomplete.vim[41]..function mucomplete#auto#enable:
line   10:
E805: Using a Float as a Number
```

I'm wondering did I get the syntax wrong.

**Comment by lifepillar** [comment]
Did you perhaps set `mucomplete#completion_delay` as well?

**Comment by richtong** [comment]
Ah yes that's it! I set to 0.5. I was thrown by the error message.

**Comment by richtong** [comment]
Was strange because it just started throwing this message so maybe something changed. Might want to mention in docs integer only :-)

**Comment by richtong** [comment]
That was the issue. Thanks!

Sent via Superhuman iOS ( ***@***.*** )
