### ISSUE TITLE
Error detected while processing function fish#Complete

### ISSUE THREAD

**Issue by MaxGyver83** [lifepillar/vim-mucomplete#192]
When I edit _fish_ files, I often get error messages like this one:

```
Error detected while processing function fish#Complete:
line    8:
E484: Can't open file /tmp/vxL0vJq/2
Press ENTER or type command to continue
```

I use:
* vim 8.2.2398
* fish 3.2.1 (but I had this issue before)
* vim-mucomplete commit 83cd9b3

My _mucomplete_ settings in `~/.vimrc`:

```
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#always_use_completeopt = 1
```

How to reproduce:

```
vim /tmp/x.fish
iecho "te
```

But I can't reproduce it with a minimal config:

`~/.vim/troubleshooting_vimrc.vim`:

```vim
...
" Optionally add additional configuration below this line
set runtimepath+=~/.vim/pack/plugins/start/vim-fish
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#always_use_completeopt = 1
```

`vim -u ~/.vim/troubleshooting_vimrc.vim /tmp/z.fish`

I can't even reproduce it when I append the whole content of my `~/.vimrc` to `~/.vim/troubleshooting_vimrc.vim`.

Btw, [this is my .vimrc](https://github.com/MaxGyver83/dotfiles/blob/master/vim/.vimrc). And this is the function mentioned in the error message: https://github.com/dag/vim-fish/blob/master/autoload/fish.vim#L44

**Comment by lifepillar** [comment]
This looks to me as an issue independent of MUcomplete. To verify that, execute `:MUcompleteAutoOff` and try completing by pressing CTRL-X CTRL-O. If the issue is still there, then the cause of the problem is not MUcomplete.

**Comment by lifepillar** [comment]
If you think that the issue is a setting in your vimrc, I suggest that you perform a binary search by commenting out half of your vimrc, test this issue, then comment/uncomment another fourth according to the result. Iterate until find the offending line.

**Comment by MaxGyver83** [comment]
Thanks! Meanwhile, I can tell for sure that this issue is not caused by my `.vimrc`. I could reproduce this error with a minimal `.vimrc` and only the plugin `vim-fish`loaded. This is my issue for that plugin: https://github.com/dag/vim-fish/issues/50 (But unfortunately, that project seems to be dead.)
