### ISSUE TITLE
Different omnifunc sources depending on section

### ISSUE THREAD

**Issue by inventionate** [lifepillar/vim-mucomplete#193]
Thank you for this great plugin! 

I'm currently trying to use it for my Markdown setup. Unfortunately, I don't quite understand the possibilities yet. Is it possible to use different omni completion settings as different sources depending on the text section? I would like to have the bibliography completion of vim-pandoc in the body text, which requires omnifunc=pandoc#completion#Complete for and then the languageserver for embedded code chunks, i.e. omnifunc=v:lua.vim.lsp.omnifunc.

Thanks in andvance!

**Comment by lifepillar** [comment]
Yes, you may define syntax-dependent completion chains. See the help file.

If you need to use different omni-completion functions in the same buffer, it may get a bit tricky, but possible, I think. If it's only two functions, you may assign one to omni-completion and one to user-completion. If it's more than one, there probably is some other way, but I'd have to think about it.

**Comment by inventionate** [comment]
Great to know! I found the parts about syntax-dependent completion and will try it. Unfortunately the multiple omni-completion setup is complex for me. Can you please give me a little example setup?

**Comment by lifepillar** [comment]
For example, you may put this in your `vimrc`:

```vim
    let g:mucomplete#chains = {}

    " Default chain to be used in all buffers:
    let g:mucomplete#chains['default'] = ['path', 'omni', 'dict', 'uspl']

    " …except for Markdown buffers, where we use scoped chains:
    let g:mucomplete#chains['markdown'] = {
          \ 'markdownCode' : ['omni'],
          \ 'markdownLink' : ['path'],
          \ 'default'      : ['user', 'keyn', 'dict', 'uspl'],
          \ }
```

This will enable different completion chains in Markdown buffers, according to the current syntax group. The `'default'` key in the latter dictionary is used as a fallback when a more specific chain cannot be applied. You should also define `omnifunc` (for `'omni'` completion) and `completefunc` (for `'user'` completion).

So, the above would use omni-completion in code blocks and path completion in links. Elsewhere, user, keyword, dictionary and spelling completion would be used.

For more examples, read `:help mucomplete-chains`.

**Comment by inventionate** [comment]
Thank you very much! I already tried these settings and they work perfectly. Unfortunately my problem is that I want to use two different omni completion setups depending on the markdown scopes, and for that I can't find any example. Something like this:

```vim
    let g:mucomplete#chains = {}

    " Default chain to be used in all buffers:
    let g:mucomplete#chains['default'] = ['path', 'omni', 'dict', 'uspl']

    " …except for Markdown buffers, where we use scoped chains:
    let g:mucomplete#chains['markdown'] = {
          \ 'markdownCode' : ['omni-lsp'],
          \ 'markdownText' : ['omni-pandoc'],
          \ 'default'      : ['user', 'keyn', 'dict', 'uspl'],
          \ }
```

Where omni-lsp means `set omnifunc = v:lua.vim.lsp.omnifunc` and omni-pandoc `set omnifunc = pandoc#completion#Complete`.

**Comment by lifepillar** [comment]
How about this (untested)?

```vim
    set omnifunc=v:lua.vim.lsp.omnifunc
    set completefunc=pandoc#completion#Complete

    let g:mucomplete#chains = {}

    " Default chain to be used in all buffers:
    let g:mucomplete#chains['default'] = ['path', 'omni', 'dict', 'uspl']

    " …except for Markdown buffers, where we use scoped chains:
    let g:mucomplete#chains['markdown'] = {
          \ 'markdownCode' : ['omni'],
          \ 'markdownText' : ['user'],
          \ 'default'      : ['keyn', 'dict', 'uspl'],
          \ }
```

In practice, you should put these settings into `~/.vim/after/ftplugin/markdown.md` and make them local.

**Comment by lifepillar** [comment]
No, there is `markdownText` highlight group (to see which highlight groups are defined, `:edit $VIMRUNTIME/ftplugin/markdown.md`). So, you should probably do something like this:

1. Create `~/.vim/after/ftplugin/markdown.md` (and the intermediate directories if necessary);
2. Put this in that script:

```vim
    setlocal omnifunc=v:lua.vim.lsp.omnifunc
    setlocal completefunc=pandoc#completion#Complete

    let b:mucomplete_chain = {
          \ 'markdownCode' : ['omni'],
          \ 'default'      : ['user'],
          \ }
```

**Comment by inventionate** [comment]
Yes, the MarkdownText thing was just a dummy ;-)

Anyway, thank you very much! Now everything works absolutely perfect :-)
