### ISSUE TITLE
Omni completion does not work with variables in PHP

### ISSUE THREAD

**Issue by inventionate** [lifepillar/vim-mucomplete#194]
Unfortunately, I have to ask for help again. In the meantime, almost everything runs perfectly, only the completion of variables in PHP does not work. I've already seen in nvim-lua/completion-nvim#252 that this is probably a more fundamental problem, but unfortunately I can't get any further with MUComplete. 
When I adjust iskeyword, I'm shown options, but I cannot select any via TAB. And it only works directly after $. If I enter $th, for example, and then TAB, nothing happens. 

Do you have any ideas what else I could try? Many thanks for the help!

**Comment by lifepillar** [comment]
Not reproducible on my side. Can you try building a minimal example exhibiting the problem using the `troubleshooting_vimrc.vim` that comes with MUcomplete?

**Comment by lifepillar** [comment]
See also `:help mucomplete-troubleshooting`.

**Comment by inventionate** [comment]
Thank you very much, again! I tried several things and think it isn't a MUComplete specific problem. This seems to be the Neovim 0.5 nightly LSP client. Built in standard PHP omni completion is working but LSP omni completion not. I think the linked completion-nvim solution is something like a workaround. Maybe I'll find a solution and if so I'll post it here.

**Comment by inventionate** [comment]
There was a bug in the LSP implementation which will soon be fixed (neovim/neovim#14563). Now everything works perfectly. Thanks again for your help!
