### ISSUE TITLE
Disable mucomplete in buffer (Telescope)

### ISSUE THREAD

**Issue by miyl** [lifepillar/vim-mucomplete#200]
It appears that having mucomplete enabled, Telescope starts to auto-select whichever option is currently the closest match, either by default immediately, but if `let g:mucomplete#completion_delay` is set, it waits that amount of time.
Even with `set completeopt+=noinsert` it still does this.

The TelescopePrompt is its own buffer - so is there a way to simply disable mucomplete in a specific buffer?
In that case it could be done with:
`autocmd FileType TelescopePrompt ...`

`:MUcompleteAutoOff` unfortunately seems to not be buffer specific.

**Comment by miyl** [comment]
This vimrc/init.vim is enough for me to experience the issue:
```
call minpac#add('nvim-telescope/telescope.nvim')
call minpac#add('nvim-lua/plenary.nvim')
call minpac#add('lifepillar/vim-mucomplete')

set completeopt+=menuone " Show the completion menu even if there's only one match.
set completeopt+=noinsert   " Set to disable auto-inserting a completion match.
set shortmess+=c   " Shut off completion messages
set belloff+=ctrlg " If Vim beeps during completion
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#completion_delay = 500
```

**Comment by lifepillar** [comment]
You may define autocommand for that. See https://github.com/lifepillar/vim-mucomplete/issues/173 and https://github.com/lifepillar/vim-mucomplete/issues/196.

**Comment by miyl** [comment]
That solution seems quite convoluted. I wonder why this doesn't seem to work:
```
autocmd BufEnter * if &ft == 'TelescopePrompt' | execute 'MUcompleteAutoOff' | endif
autocmd BufLeave * if &ft == 'TelescopePrompt' | execute 'MUcompleteAutoOn' | endif
```

**Comment by lifepillar** [comment]
One autocommand should be enough:

```
autocmd BufEnter * if &ft == "TelescopePrompt" | MUcompleteAutoOn | else | MUcompleteAutoOff | endif
```

**Comment by miyl** [comment]
Finally got around to looking in to bugfixing this again, and it seems to've failed because apparently no `BufEnter` event fires when TelescopePrompt opens - but `ModeChanged` does, so based on your solution:
`autocmd ModeChanged * if &ft == "TelescopePrompt" | MUcompleteAutoOff | else | MUcompleteAutoOn | endif`
