### ISSUE TITLE
Unsure whether autocompletion I obtain in a C++ file is due to vim itself or MuComplete

### ISSUE THREAD

**Issue by TryerGit** [lifepillar/vim-mucomplete#208]
Hello,

I have the following .vimrc:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
  \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
  
call plug#begin('~/.vim/plugged')
Plug 'lifepillar/vim-mucomplete'
call plug#end()
  
set noinfercase
set completeopt-=preview
set completeopt+=menuone,noselect
let g:clang_library_path = '/usr/lib/llvm-10/lib/libclang.so.1'
let g:clang_user_options = '-std=c++14'
let g:clang_complete_auto = 1
let g:mucomplete#enable_auto_at_startup = 1
```

The above is taken from the homepage except that on my computer, I don't have `/usr/local/opt/llvm/lib/libclang.dylib` but only have `/usr/lib/llvm-10/lib/libclang.so.1`

My project structure is:

```
.vimrc
/src/main.cpp
/include/maininclude.h
```

I open vim in this project folder itself. I attah a gif of my experience with basic C++ objects:

![mucomplete](https://user-images.githubusercontent.com/70434658/214223208-5bf90350-0aa3-4167-9921-6136a5d538d5.gif)

I am unsure whether the autocompletion I get is from MuComplete or from plain Vim itself. In the code, I have an object `f` of class `foo_` but I don't seem to be getting the option after pressing `.` of member functions `geta()` and `seta()`. Likewise, I have an `std::vector<int> abc`. But pressing `abc.` does not seem to give any suggestions. When I type `pu` completion of `push_back` comes but that could be because I have used `abc.push_back` earlier in the buffer.

Is there a way to check if MuComplete is active in the current buffer and if yes, why it may not be setup properly to provide completion?

Thank you.

**Comment by lifepillar** [comment]
Have you installed [`clang_complete`](https://github.com/xavierd/clang_complete)? The example from the Readme uses that plugin. Note also that the example might be outdated, so you should refer to the documentation of clang_complete for the correct configuration.

In general, to get some form of “smart” completion, you need to install an “omnifunc” plugin for the language you're interested in. Such plugins set `omnifunc` in the relevant buffers to the name of a function that is used for completion. See `:help omnifunc` for more details. You may check the value of that setting in the current buffer with `:setl omnifunc?` If it's empty, then omni-completion is not enabled.

MUcomplete just streamlines Vim's built-in completion. So, when MUcomplete's autocompletion does not behave as you expect, the first thing to do is disable it with `:MUcompleteAutoOff` and then try to manually complete with built-in mappings (`:help ins-completion`). If you want to check whether omni-completion works, type some text then type CTRL-X CTRL-O (that is CTRL-X followed by CTRL-O). If you do not get any completions, then there is something to be fixed *before* you start using MUcomplete.

If, instead, CTRL-X CTRL-O does open a pop-up menu with the right completions, *but* MUcomplete does not complete the same text, then you should double-check that the default completion chain (`g:mucomplete#chains`) contains `'omni'` (which should be the case, given that you are using the default settings for that variable).

**Comment by lifepillar** [comment]
You may also check this page: https://github.com/lifepillar/vim-mucomplete/wiki/Cpp--member-auto-completion.

**Comment by TryerGit** [comment]
Thank you. I am working through your suggestions step by step.

On using the exact same setup in my .vimrc as specified in the first code snippet on https://github.com/lifepillar/vim-mucomplete/wiki/Cpp--member-auto-completion, I obtain an error:

`E121: Undefined variable: g:mucomplete#can_complete`

when opening up vim. I tested some of the later steps you suggested and ended up getting some results but I wanted to fix this error before testing with the other pointers you have provided.

**Comment by TryerGit** [comment]
Despite the above error, when I go into my .cpp file, I do seem to be getting completion suggestions. 

Is it possible to have the <tab> key accept the suggestion (if there is just a single suggestion) or else cycle through the suggestion list if there is more than one suggestion?

For e.g., please see attached .gif where after pressing `f.g`, the only suggestion is `f.geta()`. On pressing the tab key, this suggestion is not accepted but the cursor advances by a tab press.

![Peek 2023-01-25 22-15](https://user-images.githubusercontent.com/70434658/214626591-9698950d-a28e-483c-8307-54ec5da37793.gif)

**Comment by lifepillar** [comment]
>On pressing the tab key, this suggestion is not accepted but the cursor advances by a tab press

That shoudl not happen. Can you please post a minimal vimrc to reproduce your settings?

**Comment by TryerGit** [comment]
I am not able to repro this with only MuComplete turned on. So, it appears possibly due to some other extension. I know there may be some incompatibility between MuComplete and Ultisnips. Let me explore that on my own and I will update this thread if I encounter this issue then.

**Comment by TryerGit** [comment]
It is exactly a problem when Ultisnips and MuComplete are both on.

Please see archive here:

[mucomplete_mwe.zip](https://github.com/lifepillar/vim-mucomplete/files/10506039/mucomplete_mwe.zip)

With both Ultisnips and MuComplete on, I obtain the following on pressing tab after the menu popup appears.

![mucomplete](https://user-images.githubusercontent.com/70434658/214749809-5522d8e7-fa99-4f1f-9d4d-542bc3a6f819.gif)

I will try to fix this using the suggestions provided at https://github.com/lifepillar/vim-mucomplete/blob/master/doc/mucomplete.txt

**Comment by TryerGit** [comment]
Indeed following the steps in the documentation fixed the conflict between MuC and US.
