### ISSUE TITLE
New feature?

### ISSUE THREAD

**Issue by lee-shun** [lifepillar/vim-mucomplete#210]
can anyone implement tabnine-based complete function?

**Comment by lifepillar** [comment]
I think that something like that is beyond the scope of this project. But if someone comes up with an AI-assisted completion function that integrates with Vim `completefunc`, it might work with MUcomplete.

**Comment by lee-shun** [comment]
Thank you for your comment! I just finish a tabnine-based complete function plugin, which can be easily integrated with mucomplete!

[vim-tabnine-completefunc](https://github.com/lee-shun/vim-tabnine-completefunc)

However, this plug is under development now....
