### ISSUE TITLE
MuComplete not respecting default completeopt arguments behavior

### ISSUE THREAD

**Issue by josefson** [lifepillar/vim-mucomplete#25]
When i open vim with ```vim -u NONE -N myfile``` and ```set completeopt=menuone```, vim selects and insert the last completion option.
I don't like this behavior, so i use ```set completeopt=menuone,noinsert,noselect```, which makes vim present all options but not inserting nor selecting any.
However, MuComplete somehow makes it behave backwards, when i have ```set completeopt=menuone``` it doesn't insert nor select, and when i have ```set completeopt=menuone,noinsert,noselect```, it does insert and select some option.

**Comment by lifepillar** [comment]
I see. I haven't tested much `noinsert` and `noselect`. In fact, from your description it may as well be that I have duplicated functionality already provided by Vim. I'll take a look into it.

**Comment by lifepillar** [comment]
@josefson GitHub automatically closes an issue with I link it from a commit message of the kind: “Fixes #n”… Feel free to reopen this issue if necessary.

**Comment by josefson** [comment]
No man, your fix solved it good. I just didn't want to create a  comment after it being closed as i was afraid i was gonna make it dirty.
But since you opened the door, lemme thank you and congratulate you for this cool and so useful plugin.
