### ISSUE TITLE
Snipmate compatibility

### ISSUE THREAD

**Issue by soyuka** [lifepillar/vim-mucomplete#26]
For bug reports only, please provide the following details:

- [x] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [x] Output of `echo g:mucomplete#chains`: `{'default': ['file', 'omni', 'keyn', 'dict']}`
- [x] Output of `setl completeopt`: `completeopt=menu,preview,menu,menuone,noinsert`
- [x] MUcomplete settings in my `.vimrc`, if any: let g:mucomplete#enable_auto_at_startup = 1

First of all, thanks for trying to make vim completion simple and great again.

I want to avoid all those plugins that are not made with `vimL`, just because they're often a pain to install on a new computer. This is why I prefered SnipMate over UltiSnips (python). The thing is, I can't trigger the snippets, and though you may have a solution.

I don't use any snipmate configuration, I just have the following (using `Vundle`):

```
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
```

Should I do something in particular do add the snipmate support? Thanks!

**Comment by lifepillar** [comment]
Try this:

```vim
  let g:mucomplete#user_mappings = { 'snip' : "\<plug>snipMateShow" }
  let g:mucomplete#chains = { 'default': ['snip', 'keyn'] } " For instance
```

**Comment by lifepillar** [comment]
I think you also need:

```vim
  let g:snipMate['no_match_completion_feedkeys_chars'] = ''
```

**Comment by lifepillar** [comment]
Adding this may also be convenient:

```vim
imap <expr> <c-j> (pumvisible()?"\<c-y>":"")."\<plug>snipMateNextOrTrigger"
```

(assuming that the SnipMate's trigger of your choice is `<c-j>`), because it allows you to expand a snippet without first closing the pop-up menu.

**Comment by soyuka** [comment]
Nice one, thanks 

Just to make sure I understand everything

This adds snippets to the menu:

```
  let g:mucomplete#user_mappings = { 'snip' : "\<plug>snipMateShow" }
  let g:mucomplete#chains = { 'default': ['snip', 'keyn'] } " For instance
```

And 

```
imap <expr> <c-j> (pumvisible()?"\<c-y>":"")."\<plug>snipMateNextOrTrigger"
```

Does expand the snippet with `<c-j>`. Is there a way to make the `tab` key to trigger the snippet?

**Comment by lifepillar** [comment]
>Is there a way to make the tab key to trigger the snippet?

Sure:

```vim
imap <expr> <tab> (pumvisible()?"\<c-y>":"")."\<plug>snipMateNextOrTrigger"
```

Note that µcomplete maps `<tab>` by default, so should either disable µcomplete's mappings:

```vim
let g:mucomplete_no_mappings =1
```

or map the completion trigger (which by defailt is `<tab>`) to something else, e.g.,

```vim
imap <c-j> <plug>(MUcompleteFwd)
```

See also `:h mucomplete-mappings`.

**Comment by lifepillar** [comment]
>`let g:mucomplete_no_mappings =1`

Sorry, that should be

```vim
let g:mucomplete#no_mappings = 1
```

**Comment by soyuka** [comment]
Okay thanks I think I've enough elements to make it work!
