### ISSUE TITLE
ultisnips: "E33: No previous substitute regular expression"  after ~

### ISSUE THREAD

**Issue by gm31** [lifepillar/vim-mucomplete#28]
- [x] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [x] Output of `echo g:mucomplete#chains`: {'default': ['file', 'omni', 'ulti', 'keyn', 'dict']}
- [x] Output of `setl completeopt`: menu,menuone,noinsert
- [x] MUcomplete settings in my `.vimrc`, if any:
```
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#auto_select = 0
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['file','omni','ulti', 'keyn','dict']
```

It seems that if I use ~ in the pathname I got the error from the title. 

`~<Tab>`
or 
`~/xy ` 

leads to:

```
Error detected while processing function mucomplete#ultisnips#complete:
line    5:
E33: No previous substitute regular expression
```

**Comment by lifepillar** [comment]
Thanks for the clear bug report. There were in fact two issues:

1. `~` was not recognized as a path character;
2. the UltiSnips completion method did not like `~` (and other special regexp characters).

Both issues should be fixed.

**Comment by gm31** [comment]
Yep. It seems to be fine now.

Thank you for your quick response. :)
