### ISSUE TITLE
uspl doesn't honour completeopt+=noinsert

### ISSUE THREAD

**Issue by tjharman** [lifepillar/vim-mucomplete#29]
For bug reports only, please provide the following details:

- [X] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [X] Output of `echo g:mucomplete#chains`: let g:mucomplete#chains = { 'default' : ['file', 'omni', 'keyn', 'uspl'] }
- [X] Output of `setl completeopt`: menu,preview,menuone,preview,noinsert,noselect
- [X] MUcomplete settings in my `.vimrc`, if any: 

```  " µcomplete
let g:mucomplete#enable_auto_at_startup = 0
set completeopt+=menuone,preview,noinsert,noselect
set shortmess+=c
let g:mucomplete#chains = { 'default' : ['file', 'omni', 'keyn', 'uspl'] }
````
The new uspl doesn't seem to honour the noinsert flag of completeopt.
If I do :setlocal spelllang=en_au and type hel, then press tab, straight away my text is replaced with Heel.  I get a menu with options, Heel is the first and is unselected.

If I type hel and press ctrl-x-s then I get the expected behaviour - a list of options (of which Heel is the first) nothing is selected and my word isn't changed.

Maybe this is by design, or I misunderstand how it's supposed to work?  If so, I again apologise for time wasting!

**Comment by lifepillar** [comment]
Yes, that's by design: tab completion is supposed… well, to complete (`noinsert` is honoured when automatic completion is on). Although I understand that for spelling suggestions that may not be ideal. I will add an option to fix it.

**Comment by tjharman** [comment]
It would be useful for Spelling, because sometimes the spelling suggestions are so terrible you don't want them! Thanks :)

**Comment by tjharman** [comment]
Fantastic, thank you!
