### ISSUE TITLE
Paste mode

### ISSUE THREAD

**Issue by soyuka** [lifepillar/vim-mucomplete#30]
- [x] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [x] Output of `echo g:mucomplete#chains`: `{'default': ['file', 'omni', 'keyn', 'dict']}`
- [x] Output of `setl completeopt`: `completeopt=menu,preview,menu,menuone,noinsert`
- [x] MUcomplete settings in my `.vimrc`, if any: let g:mucomplete#enable_auto_at_startup = 1

[![asciicast](https://asciinema.org/a/1dgjddlyconni7idupz994fo4.png)](https://asciinema.org/a/1dgjddlyconni7idupz994fo4)

Is it possible to disable completion in paste mode? Check the gif to see what happens, basically it inserts `3 sd<Plug>(MUcompleteFwd)gv<Plug>(MUcompleteFwd)0` when I type.

**Comment by lifepillar** [comment]
Good catch, thanks!

**Comment by soyuka** [comment]
Wow that was fast \o/ :heart:
