### ISSUE TITLE
Feature Request - Ability to set completeopt on MU Auto Toggle

### ISSUE THREAD

**Issue by tjharman** [lifepillar/vim-mucomplete#31]
It would be nice (I think, there are probably good reasons it's not) to have completeopt's settings be toggled for you when MUcompleteAutoOff/On/Toggle is used.

For example (this is bad pseudo code)
```
let g:mucomplete#CompAutoOn = {add : 'noinsert, noselect'}
let g:mucomplete#CompAutoOff = {remove: 'noinsert,noselect'}
```

Does this make sense? Is it a good idea, or a stupid one?

**Comment by lifepillar** [comment]
By design, µcomplete does not set or change any Vim options, much less global options. So, the short answer is: the user has to do it (through a custom command or mapping). For example:

```vim
fun! s:toggle_completeopt()
  if exists('#MUcompleteAuto')
    set completeopt+=noinsert,noselect
  else
   set completeopt-=noinsert,noselect
  endif
endf
nnoremap <silent> coa :<c-u>MUcompleteAutoToggle<cr>:call <sid>toggle_completeopt()<cr>
```

Note that `noinsert` is ignored in manual completion (again, by design), except for spelling suggestions.

**Comment by tjharman** [comment]
This makes perfect sense, thank you.
And thank you for the .vimrc suggestion, that'll do perfectly.
