### ISSUE TITLE
Comparison of vim completers

### ISSUE THREAD

**Issue by waldnercharles** [lifepillar/vim-mucomplete#32]
Obviously this is outside the scope of this project, but I'm wondering if you could help me identify the differences between this plugin and some of the currently more popular auto-complete plugins.

YouCompleteMe, NeoComplete, Deoplete, VimCompletesMe, NeoComplCache, and AutoComplPop.

Are there features that you had to sacrifice to keep the completion simple / minimal that the others might be better for?

Thanks - and great job on the plugin!

**Comment by lifepillar** [comment]
I don't think I am qualified to give a good answer. I have tried YCM, NeoComplete, and Deoplete, but for too short a period to give a thorough evaluation. I had issues with all of them, anyway, and probably I haven't tried hard enough to solve them. I have followed the shorter route of writing my own solution :)

>Are there features that you had to sacrifice to keep the completion simple / minimal that the others might be better for?

I don't view it that way. I didn't start with a list of features that other plugins have and removed some of them to make my plugin simpler. I started with one simple (and not original) idea (fallback completion), and evolved it to something that does exactly what I want, and which I can understand how it works. And you know what? Almost everything was already in Vim. In this sense, I didn't have to sacrifice anything. In fact, I see µcomplete as doing something that other plugins don't do so well :)

Some other plugins use Python or Lua, which are supposedly faster than VimL. They do things asynchronously, which is supposedly faster (admittedly, I do not understand the details of asynchronous completion). These might be things that give an advantage over µcomplete, most likely on large projects.

Sorry if this answer is unsatisfactory. Maybe others will want to chime in. Certainly, this makes it a good topic for a blog post :)

**Comment by waldnercharles** [comment]
Not unsatisfactory at all. I was expecting this kind of response. I suppose I was mostly curious as to why, given so many choices, you decided to create your own plugin; which you answered.

I'll do some research in my spare time, and may report back if that information would be valuable.

**Comment by lifepillar** [comment]
I'm closing this, because it's not a µcomplete issue. But if you find a comparison of Vim completers, feel free to drop a note here!
