### ISSUE TITLE
less common exit_ctrlx_key

### ISSUE THREAD

**Issue by Konfekt** [lifepillar/vim-mucomplete#4]
How about `let g:mucomplete#exit_ctrlx_keys = "\<c-_>\<bs>"` (instead of the default `<c-b><bs>`) as it is less likely to be remapped?

**Comment by lifepillar** [comment]
I have chosen `<c-b>` because it is not mapped by default (see `:h i_CTRL-B-gone`), so it does nothing. From `:h i_CTRL-_` I see that `<c-_>` may have side effects.

Anyway, you may override the default in your `vimrc` if you want, so I don't think it is worth changing the default.

**Comment by lifepillar** [comment]
I have tested that: `<c-_>` is not a good choice, for the reasons above. With `set allowrevins`, it has side effects.
