### ISSUE TITLE
Using `CompleteDone` event for chained completion

### ISSUE THREAD

**Issue by manasthakur** [lifepillar/vim-mucomplete#52]
Hi @lifepillar,

While having a discussion on [r/vim](https://www.reddit.com/r/vim/comments/5nhmlb/completion_for_function_calls/), I got an idea regarding chained-completion.
I was wondering whether the dictionary `v:completed_item` (populated by the `CompleteDone` event) can be used to check whether a previous completion failed. If this can be done, we can even get rid of the requirement to set `menuone` in `completeopt`.
However, I am not sure whether it's feasible. What do you think? Should I try and submit a PR if it works?

Edit: corrected the name of the variable.

**Comment by lifepillar** [comment]
That's an interesting idea. I'll take a look into the details, but a PR would be welcome!

**Comment by lifepillar** [comment]
One thing to keep in mind is that `v:completed_item` has been introduced in Vim 7.4.774, so using it would reduce the compatibility with older Vim versions (not that it shouldn't be done, mainly a reminder to myself at this point).

**Comment by lifepillar** [comment]
I have been pondering this idea some more, and I have come to the conclusion that using`v:completed_item` is not particularly useful for µcomplete, so I am closing this issue. I am still open to pull requests, of course, if you have an idea of how to make `menuone` unnecessary!
