### ISSUE TITLE
<C-h> issue

### ISSUE THREAD

**Issue by stdiopt** [lifepillar/vim-mucomplete#55]
Hi, 

I was hunting down an issue, where when I press my backspace the popup menu would start to change and wouldn't delete the chars at all even sometimes completed the previously inserted word..
I figured out that there are some cases in some terminals that backspace is sent as &lt;C-h> which I guess you know the behavior of that. 

This is just an heads up since I figured my issue, and to avoid any further issues

http://stackoverflow.com/questions/18777705/vim-whats-the-default-backspace-behavior

The answer explains the specific backspace option on certain terminals.

you might want to rebind that  &lt;C-h> or having some global option to do so

Thanks.

**Comment by lifepillar** [comment]
How to remap keys or prevent µcomplete to define any key mappings is explained under `:help mucomplete-mappings`. Does that fix your issue?

**Comment by stdiopt** [comment]
yes it would fix indeed , if I prevent default mapping and redefine, or even iunmap <C-h> it would work, but I solved by changing the terminal behavior on its options, is just that took me awhile to understand what was really going on (was not even aware that terminal was sending <C-h> on backspace)

**Comment by lifepillar** [comment]
>I solved by changing the terminal behavior on its options

Just out of curiosity, which terminal are you using? Also, are you using Vim or NeoVim? Until recently, NeoVim had an issue with `<c-h>` in some terminals (see https://github.com/neovim/neovim/issues/2048).

**Comment by stdiopt** [comment]
Using Vim

Currently using Secure Shell chrome extension I think it defaults backpace to C-h, 

Putty also have the option but seems to default to char 127 
![image](https://cloud.githubusercontent.com/assets/1675748/22461461/83620280-e790-11e6-9a96-ca8a7a167861.png)

**Comment by lifepillar** [comment]
Ok, thanks. So, I think this issue may be closed, since it may be fixed by either changing µcomplete's mapping or by configuring your terminal.
