### ISSUE TITLE
CPU issue with ultisnips

### ISSUE THREAD

**Issue by hellohuangjin** [lifepillar/vim-mucomplete#57]
I've been using this plugin for some time, it is very nice. but I can not make mucomplete work with ultisnips.CPU is high load, vim no response.
![error](https://cloud.githubusercontent.com/assets/12655469/24068760/15139210-0bd2-11e7-8d29-27087e1f27bb.gif)

vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 00:01:12)
MacOS X (unix) version
Included patches: 1-473

settings:

    set noshowmode shortmess+=c
    set noinfercase
    set completeopt-=preview
    set completeopt+=longest,menuone,noinsert,noselect

    let g:mucomplete#chains = {
			\ 'default' : ['file', 'omni', 'keyn', 'dict'],
			\ 'vim'     : ['file', 'cmd', 'keyn'],
			\ 'python'  : ['file', 'omni', 'ulti'],
			\ 'cpp'     : ['file', 'ulti', 'keyn', 'incl', 'omni', 'dict']
			\ }

    let g:mucomplete#enable_auto_at_startup = 1

    imap <Leader>j <plug>(MUcompleteCycFwd)
    imap <Leader>k <plug>(MUcompleteCycBwd)

How can I solve this problem?

**Comment by lifepillar** [comment]
I cannot reproduce it. Please follow the steps described at `:help mucomplete-troubleshooting`. In particular, does that happen when you invoke UltiSnips expansion directly? Can you reproduce the problem using the minimal vimrc provided with µcomplete? Which version of µcomplete are you using?

**Comment by hellohuangjin** [comment]
I am sorry. jedi cause this problem. very nice plugin
