### ISSUE TITLE
E227: mapping already exists for ^I - Error when loading plugin.

### ISSUE THREAD

**Issue by josefson** [lifepillar/vim-mucomplete#58]
```
Error detected while processing /Users/josefson/dotfiles/vim/.vim/bundle/vim-mucomplete/plugin/mucomplete.vim:
line   22:
E227: mapping already exists for ^I
Press ENTER or type command to continue
```

**Comment by lifepillar** [comment]
Have you mapped <tab> in you `vimrc`? If not, check for other plugins loaded before µcomplete, which map `<tab>`. Can you work around the error by defining a different completion mapping? E.g.,

```vim
imap <c-j> <plug>(MUcompleteFwd)
```

**Comment by josefson** [comment]
Sorry, i had supertab activated. And i think it used to work with it before so i got confused. Anyway, i'm closing this, and i apologize for the confusion

**Comment by lifepillar** [comment]
>And i think it used to work with it before so i got confused

Correct, the check for the uniqueness of mappings has been added to master very recently, precisely to avoid situations like that (µcomplete silently overriding a mapping from another plugin) going undetected.
