### ISSUE TITLE
Clang library path on linux

### ISSUE THREAD

**Issue by ps2931** [lifepillar/vim-mucomplete#60]
Hi,

I am new to C++ and Vim. I am using Ubuntu 16.04 and have gcc and clang installed. 

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

My problem is, I cannot find libclang.dylib file on my system. Some google search shows that this file is specific to Mac OS and does not exist on linux. If that's the case which file I can use for clang_library_path?

Thanks,

**Comment by lifepillar** [comment]
Take a look at [clang-complete's Readme](https://github.com/Rip-Rip/clang_complete).
