### ISSUE TITLE
2 Characters deleted on CR

### ISSUE THREAD

**Issue by tjharman** [lifepillar/vim-mucomplete#61]
For bug reports only, please provide the following details:

- [X] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [X] Output of `echo g:mucomplete#chains`: let g:mucomplete#chains = { 'default' : ['keyp', 'keyn'] }
- [X] Output of `setl completeopt`: menu,preview,noinsert,noselect,menu,menuone
- [X] MUcomplete settings in my `.vimrc`, if any: 

```vim
" µcomplete
set completeopt+=noinsert,noselect
let g:mucomplete#enable_auto_at_startup = 1
inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")
set completeopt+=menu,menuone
set shortmess+=c
let g:mucomplete#spel#good_words = 1
let g:mucomplete#spel#max = 10
let g:mucomplete#chains = { 'default' : ['keyp', 'keyn'] }
fun! s:toggle_completeopt()
  if exists('#MUcompleteAuto')
    setlocal completeopt+=noinsert,noselect
  else
   setlocal completeopt-=noinsert,noselect
  endif
endf
nnoremap <silent> <leader>u :<c-u>MUcompleteAutoToggle<CR>:call <sid>toggle_completeopt()<CR>   " Toggle AutoCompletion
```

With the above settings, I have issues with a new blank vim document if I type:

```
Port<cr>
Port<cr>
```

The second (and later lines) when I press return on the end of Port, it deletes 2 characters so I end up with

```
Po
```

If I comment out "let g:mucomplete#chains = { 'default' : ['keyp', 'keyn'] }" the issue goes away.
If I turne off Autocomplete it also goes away.

Not sure what other debugging I can offer sorry, please let me know.

**Comment by lifepillar** [comment]
I can reproduce this. I'll look into it.

**Comment by lifepillar** [comment]
That's weird. I can reproduce the problem with your vimrc, but not with mine, so it looks like a strange interaction with some Vim setting. Now, go figure which one.

**Comment by tjharman** [comment]
Ok I will do more testing and see if I can figure it out.

**Comment by lifepillar** [comment]
Ok, so the problem is Vim (btw, I can reproduce it with my vimrc, just I had mistakenly swapped the order of the two methods in my completion chain). Run `vim -Nn --noplugin -u NONE` and execute `:set completeopt+=menuone,noinsert,noselect`. Then type:

```
Port
Po<c-x><c-p>rt<cr>
```
and you will remain with `Po` instead of `Port`.

Possibly worth reporting to the Vim project.

**Comment by tjharman** [comment]
I see that @vimeitor has kindly opened an issue [here](https://github.com/vim/vim/issues/1645).

I think we can close this bug report, thanks for helping troubleshooting it.

**Comment by lifepillar** [comment]
FYI, starting with Vim 8.0.1731, this issue should be fixed, so `'keyp'` and `'c-p'` should not cause character deletions any longer.
