### ISSUE TITLE
Show snippet completion option in menu

### ISSUE THREAD

**Issue by qazip** [lifepillar/vim-mucomplete#64]
Hello,

Using YCM, it's easy to differentiate between a snippet and a variable. One says "[ID]" and the other says "snippet". 

Is there a way to have the same behaviour for mucomplete? Is there a way to have snippets show up as an option, in the pop-up menu?

**Comment by lifepillar** [comment]
Do you mean UltiSnips snippets? Can you please elaborate? In YCM, are `[ID]` entries provided by UltiSnips?

**Comment by qazip** [comment]
Yes, I mean ultisnips snippets. With mucomplete, I cannot see the snippets in the menu completion, for example, in CPP, if I type "for", I expected it to show me that there's a snippet for "for". That does not happen.

**Comment by lifepillar** [comment]
I assume that you are using a completion chain that puts omni-completion before UltiSnips completion. That's expected then, because when omni-completion kicks in, µcomplete stops trying other completion methods.

For circumstances like the one you describe, you may press `<c-j>` while the pop-up menu is visible to try the next completion method. Or you may put `'ulti'` in front of your completion chain to give UltiSnips suggestions higher priority:

```vim
let g:mucomplete#chain.cpp = [ 'ulti', 'omni']
```

Aggregating suggestions for different completion methods into one menu is an open feature request (see https://github.com/lifepillar/vim-mucomplete/issues/62).

**Comment by qazip** [comment]
Hey,

After adding that command to my init.vim, I get the following error when trying to open a file with vim:
`E121: Undefined variable: g:mucomplete#chains`

Removing the ".cpp" part (since I want this to be true for all files), I get the following:

`E712: Argument of extend() must be a List or Dictionary`

**Comment by lifepillar** [comment]
Use:

```vim
let g:mucomplete#chains = {}
let g:mucomplete#chains.cpp = ['ulti', 'omni']
```

or

```vim
let g:mucomplete#chains = { 'default': [ 'ulti', 'omni'] }
```

The variable `g:mucomplete#chains` is not yet defined when your `vimrc` is loaded.

**Comment by qazip** [comment]
Thank you. Snippets are now showing in the completion menu, but words are not. Here's my mucomplete config:

```
"mucomplete:
let g:mucomplete#enable_auto_at_startup = 1
set completeopt+=menuone

"inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
"inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")

let g:mucomplete#chains = { 'default': [ 'ulti', 'omni'] }
set completeopt+=preview
"set completeopt+=longest,menuone,noinsert,noselect
set completeopt+=noselect,noinsert,menu,menuone

set shortmess+=c

For example, if I have the following document:

"for1 for2 for3", after typing "for", I expected the pop-up to show me the "for" snippet (which it does) and "for1", "for2" and "for3", which it does not.
```

**Comment by lifepillar** [comment]
You may extend your completion chain with other methods. For instance:

```vim
let g:mucomplete#chains = { 'cpp': [ 'ulti', 'omni', 'keyn', 'incl'] }
```

**Comment by lifepillar** [comment]
Ah, wait. You mean, it doesn't show the all the matches *at once*… No, it does not. That requires defining a custom completion method that aggregates several sources, which has been discussed previously (see https://github.com/lifepillar/vim-mucomplete/issues/62).

**Comment by qazip** [comment]
Ah, ok. Thank you!
