### ISSUE TITLE
Cannot perform imap <C-J> with minimal vimrc

### ISSUE THREAD

**Issue by austincrft** [lifepillar/vim-mucomplete#65]
I am getting the following error when trying to perform an `imap` for `<C-J>`:

```
Error detected while processing /Users/austincrft/.vim/plugged/vim-mucomplete/plugin/mucomplete.vim:
line   27:
E227: mapping already exists for ^@
```

For bug reports only, please provide the following details:

- [x] I have followed the instructions in `:help mucomplete-troubleshooting`.
- [x] Output of `echo g:mucomplete#chains`:
```
{'vim': ['path', 'cmd', 'keyn'], 'default': ['path', 'omni', 'keyn', 'dict', 'uspl']}
```
- [x] Output of `setl completeopt`:
```
completeopt=menu,preview
```
- [x] MUcomplete settings in my `.vimrc`, if any:
```vim
" vim: foldmethod=marker foldenable
" Do not change this section {{{
set nocompatible
set nobackup noswapfile
if has('persistent_undo')
  set noundofile
endif
if has('writebackup')
  set nowritebackup
endif
if has('viminfo')
  set viminfo=""
endif
if has('packages')
  set packpath=
endif
set completeopt=menuone
if has('patch-7.4.775')
  if !has('patch-7.4.784')
    echomsg "WARNING: noinsert and noselect may not work properly with this version of Vim."
  endif
  set completeopt+=noinsert
else
  echomsg "Automatic completion is not available in this version of Vim."
endif
set showmode
if has('patch-7.4.314')
  set shortmess-=c
endif
set runtimepath=
" }}}

set runtimepath+=~/.vim/plugged/vim-mucomplete  " CHANGE THIS

" Optionally add additional configuration below this line
imap <C-J> iHello World!<ESC>
```

**Comment by lifepillar** [comment]
That's expected behaviour, because µcomplete by default maps `<c-j>` to `<plug>(MUcompleteCycFwd)` and, of course, it doesn't want to silently overwrite your own mapping. You should also redefine that plug, e.g.:

```vim
imap <right> <plug>(MUcompleteCycFwd)
imap <c-j> Hello World!<esc>
```

Or, more drastically, prevent µcomplete from defining any mapping:

```vim
let g:mucomplete#no_mappings = 1
```

**Comment by austincrft** [comment]
Great, that works perfectly!

I ran into this issue when I was following the snipmate tips in the mucomplete help docs. The help docs suggest the following mapping:

```vim
imap <expr> <c-j> (pumvisible() ? "\<c-y>" : "")
    \               . "\<plug>snipMateNextOrTrigger"
```

Do you think it would be useful to include the need to remap `MUcompleteCycFwd` in this section to avoid confusion in the future?

**Comment by lifepillar** [comment]
>Do you think it would be useful to include the need to remap MUcompleteCycFwd in this section to avoid confusion in the future?

I will update the docs. Thanks for pointing that out.

**Comment by austincrft** [comment]
No problem! Thanks for creating an awesome plugin! This is the first one I've found with sane defaults, and I've been through them all. 😄
