### ISSUE TITLE
Can I disable tilde being autoexpanded to my home directory?

### ISSUE THREAD

**Issue by SilverEzhik** [lifepillar/vim-mucomplete#68]
I installed Mucomplete, and it's pretty cool, but the one thing that bothers me is that whenever I type the tilde character by itself, it autoexpands to my home directory. 

I am not very familiar with vim script, however, I found that I could disable this behavior by commenting out line 16 in `vim-mucomplete/autoload/mucomplete/path.vim`, but is there a more proper way of doing this? Some flag I could set?

Thank you.

**Comment by lifepillar** [comment]
>I installed Mucomplete, and it's pretty cool, but the one thing that bothers me is that whenever I type the tilde character by itself, it autoexpands to my home directory.

MUcomplete should offer the *option* of expanding the tilde, but it should not *auto*-expand it. What is the output of `:set completeopt`?

If you are not interested in path completion in general, just remove `'path'` from your completion chain. For instance, put this in your `.vimrc`:

```vim
let g:mucomplete#chains = { 'default': ['omni', 'keyn', 'dict', 'uspl'] }
```

**Comment by SilverEzhik** [comment]
This is what `:set completeopt` looks like: 

`completeopt=menu,menuone,longest,noinsert,noselect`

This is what it looks like when I type a standalone tilde:

![image](https://user-images.githubusercontent.com/4080683/28140861-1b6408aa-6728-11e7-82df-510c085d87c3.png)

If I tab twice, it will show the tilde again.

**Comment by lifepillar** [comment]
Please remove `longest` from `completeopt`. Let me know if that works for you.

**Comment by lifepillar** [comment]
I assume that `longest` was the culprit. If `completeopt` does not contain `longest` and `noselect`, the tilde is not expanded.

Also, a literal tilde can always be inserted with `<c-v>~` (see `:help i_CTRL-V`), no matter what the value of `completeopt` is.
