### ISSUE TITLE
Getting many errors for "mapping already exists for ^@"

### ISSUE THREAD

**Issue by tngreene** [lifepillar/vim-mucomplete#72]
- [x] Output of `echo g:mucomplete#chains`:
Error detected while processing C:\Users\Ted\.vim\bundle\vim-mucomplete\autoload\mucomplete.vim:
line   19:
E227: mapping already exists for ^@
g:mucomplete#chains   {'vim': ['path', 'cmd', 'keyn'], 'default': ['path', 'omni', 'keyn', 'dict', 'uspl']}

- [x] Output of `setl completeopt`: …
  completeopt=menuone,menu,longest,preview,noinsert

- [x] MUcomplete settings in my `.vimrc`, if any: …

	"vim-mucomplete
	set completeopt+=menuone
	inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
	inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
	inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")

	set completeopt+=noinsert

	set shortmess+=c   " Shut off completion messages
	set belloff+=ctrlg " If Vim beeps during completion

	let g:mucomplete#enable_auto_at_startup = 1
	let g:mucomplete#no_mappings = 0

I've noticed (I think) when #no_mappings is = 0, I get this error message often when (I think) I trigger an auto-completion method.
Error detected while processing C:\Users\Ted\.vim\bundle\vim-mucomplete\autoload\mucomplete.vim:
line   19:
E227: mapping already exists for ^@

#no_mappings = 1 seems to fix it, but I'm not sure.

possibly mapping already exists for other ones as well, but I've been moving so quick I haven't picked up which ones it is.

I'm using GVim8x64 with huge features.

**Comment by lifepillar** [comment]
That looks like there is already a mapping for `<c-j>`, possibly set by another plugin. What does:

```vim
:verbose imap ^@
```

show? (Note that `^@` is obtained by pressing CTRL-V followed by CTRL-J).

**Comment by jwmann** [comment]
I'm getting this as well.
![screen shot 2017-09-25 at 11 13 51 pm](https://user-images.githubusercontent.com/436270/30840789-45c17c86-a247-11e7-95e7-031f17ab8d4f.PNG)

I have no real allegiance to [Matchem](https://github.com/ervandew/matchem)  
Maybe there's a newer better alternative?

**Comment by lifepillar** [comment]
Matchem maps `<nl>` (which is the same as `<c-j>`) in Insert mode. As far as I see, that mapping cannot be customised. So, to resolve the conflict you should remap `<plug>(MUcompleteCycFwd)`. For example, to use CTRL-B instead of CTRL-J, you may put this in your `vimrc`:

```vim
inoremap <silent> <plug>(MUcompleteFwdKey) <c-b>
imap <c-b> <plug>(MUcompleteCycFwd)
```

>Maybe there's a newer better alternative?

Sorry, I do not use Matchem, so I have no idea what might be a better alternative.

**Comment by jwmann** [comment]
Thanks for this potential fix.
I ended up just switching to [Auto-pairs](https://github.com/jiangmiao/auto-pairs)

**Comment by lifepillar** [comment]
Ok, the error is intended behaviour: it warns the user that one of µcomplete's mappings conflicts with a mapping defined elsewhere. I have added an explanation in the documentation about E227 and how to fix it. Feel free to reopen this issue if necessary.
