### ISSUE TITLE
Question: Why must we add those 3 lines to .vimrc?

### ISSUE THREAD

**Issue by tjharman** [lifepillar/vim-mucomplete#75]
This is a question, not an issue.

```
  inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
  inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
  inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")

```
Why must those be added to .vimrc?  I'm curious why they're not in the plugin itself.

**Comment by lifepillar** [comment]
Good question. The idea is that the user must keep control. Suppose that those mappings are defined by µcomplete. Then, for some reason you map `<cr>` in your `vimrc`. Your mapping will silently override µcomplete's, and µcomplete will not behave correctly. By leaving those definitions to you, you know that your mapping must take into account µcomplete's requirements.

I am not happy with those settings, but I have found no better way to detect when the user presses those keys while the pop-up menu is open (suggestions are welcome). And maybe I am being over-zealous: I have seen other plugins happily redefining `<cr>` in Insert mode…

I leave this issue open for discussion. Simplifying the user's configuration is very desirable: maybe you or someone else will come up with some clever idea.

**Comment by tjharman** [comment]
Thank you, I see why you do this.

Could you use the mapcheck command to see if it's mapped?
On activation of Autocomplete mode, you check if they are already defined and print an error.  If not defined, then you define them and off you go.  Make it a one time check when Autocomplete is first enabled.

That said, I have almost zero understanding of vimscript and aren't sure if the mapcheck can do this or not.

Thanks again for mu-complete, it's great.

**Comment by tjharman** [comment]
So I figured out some really basic vimscript (don't laugh, I'm not much of a coder)

Could something like this be run either when mu-complete loads, or when MUcompleteAutoOn is first called?

`if maparg('<c-y>','i') != ""
  echo "Warning: control-y is already mapped! mu-complete's autocomplete functionality requires this mapping to operate correctly."
endif
if maparg('<c-e>','i') != ""
  echo "Warning: control-e is already mapped! mu-complete's autocomplete functionality requires this mapping to operate correctly."
endif
if maparg('<cr>','i') != ""
  echo "Warning: <cr> is already mapped! mu-complete's autocomplete functionality requires this mapping to operate correctly."
endif
`

**Comment by dbmrq** [comment]
I like the freedom of defining those mappings however I want. I prefer `<cr>` to behave like `<c-y>` when completing, and I have it mapped to a bunch of other stuff too. My current mapping looks like this:

```vim
function! SnipOrCYOrCR()
    let snippet = UltiSnips#ExpandSnippet()
    if g:ulti_expand_res > 0
        return snippet
    elseif pumvisible()
        return mucomplete#popup_exit("\<c-y>")
    else
        for comment in map(split(&l:comments, ','),
            \ 'substitute(v:val, "^.\\{-}:", "", "")')
                if getline('.') =~ '\V' . escape(comment, '\') . ' \$'
                    return repeat("\<BS>", strchars(comment) + 1)
                endif
        endfor
        return "\<cr>"
    endif
endfunction
inoremap <silent> <expr> <CR> "<C-R>=SnippetOrCYOrCR()<CR>"
```

If the text is a UltiSnips snippet, `<cr>` completes the snippet; otherwise, if the pop up menu is visible, `<cr>` calls `mucomplete#popup_exit("\<c-y>")`; otherwise, if the current line is just a comment character, `<cr>` deletes the comment (when you're writing a comment, `set fo+=r` makes `<cr>` start the next line with a comment automatically, so I have a second `<cr>` delete it); otherwise I get a regular `<cr>`.

@tjharman's suggestion would have µcomplete give me unnecessary warnings all the time. And even checking if `mucomplete#popup_exit("\<cr>")` is mapped to a different key wouldn't work in my case, since I never use `mucomplete#popup_exit("\<cr>")` (I prefer `mucomplete#popup_exit("\<c-y>")`, and I call it from a function anyway).

**Comment by lifepillar** [comment]
Btw, see https://github.com/lifepillar/vim-mucomplete/issues/66.

**Comment by lifepillar** [comment]
A compromise might be as follows: let µcomplete define those mappings by default, but allow the user to suppress them with an option (e.g. `g:mucomplete_no_popup_mappings`). What do you think?

**Comment by kevinushey** [comment]
I like that idea quite a bit, personally.

While I certainly can't speak for all Vim users, one of the reasons why I love the ecosystem of Vim plugins is that the majority of them 'just work' right out of the box with little to no configuration, but configuration is available for the users who want (or need) it. The universe of completion plugins is unfortunately not in that camp -- most require the user to do some gymnastics to get the plugin installed, require relatively new versions of Vim compiled with features not always available by default, and then fall flat on their face when you accidentally misconfigure things in a way not expected by the plugin.

I think this a big reason why µcomplete is so compelling -- minimal Vim requirements + 'just works' with existing mode-specific completion systems. Providing these bindings by default would mean µcomplete would 'just work' for the majority of users out of the box, but remain configurable for the other users who need it.

Once a user has installed multiple plugins that compete for space in the user's mappings (e.g. as endwise and µcomplete do with `<CR>`) I agree the onus moves to the user to get the plugins to work together -- and so it's nice to be able to disable the default mappings when needed.

**Comment by tjharman** [comment]
I was waiting till I had a minute to write up my thoughts on this, but @kevinushey has said pretty much word for word what I was going to say.
So, "What he said"

**Comment by lifepillar** [comment]
Please try the current master. Mapping `<c-e>`, `<c-y>`, and `<cr>` in one's `vimrc` is not required any more. You will need to update your `vimrc`, but µcomplete will prompt you to do so. Let me know how it works for you.

@dbmrq You should add something along this lines to your `vimrc`:

```vim
imap <plug>Unused <plug>(MUcompleteCR)
```

to prevent µcomplete from complaining about `<cr>` being already mapped.

**Comment by dbmrq** [comment]
@lifepillar Perfect, thanks for letting me know!

**Comment by tjharman** [comment]
No problems here, though I didn't get any warning/message about the lines I already had in .vimrc (I have since removed them anyway)

**Comment by lifepillar** [comment]
>though I didn't get any warning/message about the lines I already had in .vimrc

You wouldn't get the warning at startup, but as soon as `autoload/mucomplete.vim` is loaded (i.e., when completion is tried).

**Comment by tjharman** [comment]
Ahh yes, I see it now.
Thanks!

**Comment by sharethewisdom** [comment]
Hi, I adopted and expanded what @dbmrq used (see below). Could someone please help me find out how I could fix (i.e. replace `return mucomplete#popup_exit("\<c-y>")`) in my custom `CR()`? I remember that I could find a function here https://github.com/lifepillar/vim-mucomplete/blob/0c761169cef93a5ff41bcbfebf5dd6ed51846340/autoload/mucomplete/auto.vim#L80 but it wasn't accessible somehow. I was very busy at the time. Having tried many things, but I ended up freezing the repo on https://github.com/lifepillar/vim-mucomplete/commit/836fd59460d7682761ae95b9f6df8ac6a776c7ac . Here's my customization:

```viml
    function! s:CR() abort
      if &ft=='sh' || &ft=='zsh' || &ft=='vim'
        let l:line = getline('.')
        let l:words = [ 'else', 'fi', 'then', 'done',
          \ 'endif', 'endfor', 'endwhile' ]
        if index(map(l:words, 'l:line =~ v:val'), 1) > -1
          if exists("g:loaded_unimpaired")
            " return "\<c-e>\<cr>"
            return "\<esc>]\<space>o"
          else
            return "\<esc>o"
          endif
        endif
      elseif pumvisible()
        return mucomplete#popup_exit("\<c-y>")
      else
        if neosnippet#expandable_or_jumpable()
          return "\<c-l>"
        endif
        for comment in map(split(&l:comments, ','),
          \ 'substitute(v:val, "^.\\{-}:", "", "")')
          if getline('.') =~ '\V' . escape(comment, '\') . ' \$'
            return repeat("\<BS>", strchars(comment) + 1)
          endif
        endfor
      endif
      if &ft=='vimwiki' && exists(':VimwikiReturn')
        return "\<Esc>:VimwikiReturn 1 5\<CR>"
      else
        return "\<cr>"
      endif
    endfunction
```

**Comment by sharethewisdom** [comment]
thanks, it works. Embarrassingly I didn't try that simple solution. I'm using neovim:

    NVIM v0.3.1-1-gfa2ad305e
    Features: +acl +iconv +jemalloc +tui

**Comment by lifepillar** [comment]
Fine, NeoVim 0.3.1 includes patch 8.0.0283.
