### ISSUE TITLE
Don't be silenced <Plug>(MUcompleteTry)

### ISSUE THREAD

**Issue by tanrax** [lifepillar/vim-mucomplete#79]
For bug reports only, please provide the following details:

- [ ] I have followed the instructions in `:help mucomplete-troubleshooting`. 
Yes
- [ ] Output of `echo g:mucomplete#chains`:
![screen shot 2017-12-15 at 15 53 34](https://user-images.githubusercontent.com/4553672/34047315-28cd3d7e-e1b0-11e7-8a59-0baf51c400ed.jpg)

- [ ] Output of `setl completeopt`:
![screen shot 2017-12-15 at 15 54 38](https://user-images.githubusercontent.com/4553672/34047358-4edf3620-e1b0-11e7-9752-8a21edafb305.jpg)

- [ ] MUcomplete settings in my `.vimrc`, if any:
```
" Mucomplete
set completeopt-=preview
set completeopt+=noinsert,menuone,noinsert,noselect
set shortmess+=c   " Shut off completion messages
set belloff+=ctrlg " If Vim beeps during completion
let g:mucomplete#enable_auto_at_startup = 1
"" Types
autocmd FileType css,sass,scss setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags
inoremap <expr> <c-e> mucomplete#popup_exit("\<c-e>")
inoremap <expr> <c-y> mucomplete#popup_exit("\<c-y>")
inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")
inoremap <silent> <plug>(MUcompleteFwdKey) <c-b>
inoremap <silent> <plug>(MUcompleteTry) <c-b>
imap <c-b> <plug>(MUcompleteCycFwd)
imap <c-j> <plug>(MUcompleteCycFwd)
"let g:mucomplete#no_mappings = 1
```

If your problem has to do with specific completion methods, please provide the
output of the relevant settings (choose all that apply):

![screen shot 2017-12-15 at 15 49 46](https://user-images.githubusercontent.com/4553672/34047443-8a869826-e1b0-11e7-84b0-7ce697779ed3.jpg)

![screen shot 2017-12-15 at 15 59 13](https://user-images.githubusercontent.com/4553672/34047558-ef0c64f6-e1b0-11e7-9cf9-fe4541c022b1.jpg)

**Comment by lifepillar** [comment]
Can you reproduce the issue if you put your settings in µcomplete's `troubleshooting_vimrc.vim`? If so, what does `:verbose imap <c-r>` print? It might be a conflict with another plugin.

**Comment by lifepillar** [comment]
Btw, not sure what you are trying to do with this line:

```vim
inoremap <silent> <plug>(MUcompleteTry) <c-b>
```

You are not supposed to change that plug.

**Comment by tanrax** [comment]
You're right, there is a conflicting plugin.
[vim-paste-easy](https://github.com/roxma/vim-paste-easy)
Many thanks and congratulations for your wonderful plugin
