### ISSUE TITLE
Compatibility with vim-endwise?

### ISSUE THREAD

**Issue by kevinushey** [lifepillar/vim-mucomplete#81]
I'm using [vim-endwise](https://github.com/tpope/vim-endwise), and it seems like this plugin conflicts with µcomplete. Whenever I try to press enter in insert mode, the text:

```
mucomplete#popup_exit("\
")
```

is inserted. Endwise basically appends behaviors to `<CR>` insertions, so I have the following:

```
i  <CR>        &@mucomplete#popup_exit("\<CR>")<SNR>102_DiscretionaryEnd
i  <CR>        & mucomplete#popup_exit("\<CR>")<SNR>102_DiscretionaryEnd
```

This is hopefully a minimal `.vimrc` for reproducing the issue if you use [vim-plug](https://github.com/junegunn/vim-plug) (note that it doesn't reproduce if you try placing it in a separate file and running with e.g. `vim -u .vimrc.debug`; at least, it didn't for me)

```vim
call plug#begin('~/.vim/bundle')
Plug 'tpope/vim-endwise'
Plug 'lifepillar/vim-mucomplete'
call plug#end()

set completeopt+=menuone
set completeopt+=noselect
set shortmess+=c   " Shut off completion messages
set belloff+=ctrlg " If Vim beeps during completion

inoremap <expr>  <cr> mucomplete#popup_exit("\<cr>")

let g:mucomplete#enable_auto_at_startup = 1
```

It's possible to disable the endwise mapping by setting `g:endwise_no_mappings = 1`, but I'm curious as to whether there's a way to get these plugins to play nicely together.

For posterity:

```
g:mucomplete#chains: {'vim': ['path', 'cmd', 'keyn'], 'default': ['path', 'omni', 'keyn', 'dict', 'uspl']}
completeopt=menu,preview,menuone,noselect
```

**Comment by kevinushey** [comment]
This seems (?) like it could be a solution, although it's kind of gross. I think it ultimately comes down to `endwise` not being compatible with pre-existing `<expr>` mappings? (this strategy is discussed a bit here: https://github.com/tpope/vim-endwise/issues/91)

```vim
let g:CR = "<CR>"
inoremap <silent> <SID>PopupExitCR  <C-R>=mucomplete#popup_exit(g:CR)<CR>
imap     <script> <Plug>PopupExitCR <SID>PopupExitCR
imap              <CR> <Plug>PopupExitCR
```

**Comment by lifepillar** [comment]
I believe you'd be better off overriding endwise's mappings:

```vim
    let g:endwise_no_mappings = 1
    fun! MyEndwise()
      return mucomplete#popup_exit("")."\<cr>\<plug>DiscretionaryEnd"
    endf
    imap <expr> <cr> MyEndwise()
```

**Comment by lifepillar** [comment]
You can do it without disabling endwise's mappings, after all:

```vim
    fun! MyCR(x)
      return mucomplete#popup_exit("")
    endf
    inoremap <cr> <cr><c-r>=MyCR('<Plug>xCR')<cr>
```

The argument of `MyCR()` tricks endwise into believing that a plug has been defined. The (aesthetic) drawback with this is that endwise does not use `<silent>`, so you will see the mapping below the status line.

>I think it ultimately comes down to endwise not being compatible with pre-existing <expr> mappings? 

That's correct. The culprit is this line:

```vim
    exe "imap <CR> ".maparg('<CR>', 'i')."<Plug>DiscretionaryEnd"
```

Basically, endwise appends its own plug to whatever was already defined (`maparg('<CR>','i')`), which is unlikely to work (if at all) when the existing mapping is an `<expr>` mapping.

**Comment by lifepillar** [comment]
Btw, this shows (once again!) that it is better to leave the definition of such mappings to the user (see https://github.com/lifepillar/vim-mucomplete/issues/75).

**Comment by kevinushey** [comment]
I think endwise makes a reasonable compromise -- it works for 99% of users (those without a pre-existing mapping to `<CR>`, and those who use a non-`<expr>` mappings). It's nice to be able to install a plugin that 'just works' with no configuration when possible.

That said, it's also nice to see that there's an escape hatch for handling exactly this case on the endwise side. Since it seems like the onus is on the user to get these plugins to play nicely together I'll close this.

Thanks for the thoughtful responses!

**Comment by lifepillar** [comment]
With the current master, all you need now in your `vimrc` is:

```vim
imap <Plug>MyCR <Plug>(MUcompleteCR)
imap <cr> <Plug>MyCR
```

(see `:help mucomplete-compatibility`). Feel free to re-open this issue if this does not work as expected.

**Comment by lifepillar** [comment]
The current master (past v1.0.0) should not require any workaround to coexist with endwise. Please open a new issue if that is not the case.

**Comment by kevinushey** [comment]
Just want to confirm everything is working great :-) Thanks!
