### ISSUE TITLE
Request: Please add additional option for disabling specific default key mapping

### ISSUE THREAD

**Issue by dd4fqa** [lifepillar/vim-mucomplete#82]
When I use vim-mucomplete with mswin.vim, key mapping confiliction was occurred by following steps.

1. Source mswin.vim in my `.gvimrc` (`runtime mswin.vim`).
2. Run Gvim.
3. Enter insert mode.
4. Type `<Tab>`.
5. Following error is occurred.

```
Error detected while processing C:\Users\dd4fqa\.vim\pack\main\start\vim-mucomplete\autoload\mucomplete.vim:
line 23:
E227: mapping already exists for ^H
```

In mswin.vim, `<C-h>` is mapped for replacement dialog since [Vim 8.0.321](https://github.com/vim/vim/commit/8cc2a9c062fa38e133a62778518f769a423a2526#diff-4db2ac3abef259a3a1f885f51c426087).

For key mapping confliction, vim-mucomplete has `g:mucomplete#no_mappings`.
But this option is all or nothing. I want to disable only specific default key mapping (`<C-h>`).

If it is possible, would you add additional option for disabling specific default key mapping?

**Comment by lifepillar** [comment]
You may disable a key mapping by defining the corresponding plug. In your case, putting this in your `vimrc` should suffice:

```vim
imap <plug>Unused <plug>(MUcompleteCycBwd)
```

But I'd recommend overriding the default mapping instead, as explained in `:h mucomplete-mappings`.

**Comment by dd4fqa** [comment]
Thanks! I will try it.
