### ISSUE TITLE
Turn off mucomplete for specific filetypes

### ISSUE THREAD

**Issue by shardulbee** [lifepillar/vim-mucomplete#83]
Hi, I'm wondering how I can turn off mucomplete for `gitcommit` files. Using this with `vim-rhubarb` causes me to hit a github api rate limit since rhubarb will ping github everytime I type. 

Thanks.

**Comment by lifepillar** [comment]
Create `~/.vim/after/ftplugin/gitcommit.vim` with this content:

```vim
MUcompleteAutoOff
```

Or put something like this (untested) in your `vimrc`:

```vim
autocmd BufEnter * if &ft ==# 'gitcommit' | MUcompleteAutoOff | else | MUcompleteAutoOn | endif
```

**Comment by shardulbee** [comment]
Works for me now -- thanks!
