### ISSUE TITLE
enhancement request : async support?

### ISSUE THREAD

**Issue by damnskippy** [lifepillar/vim-mucomplete#84]
Firstly, just want to say this plugin rocks, and thank you!
Does exactly what's promised without unnecessary overhead.

Question/enhancement request: just wondering if (vim8) async support (à la deoplete, completor, etc) is something you have considered adding/supporting?  If not, perhaps something to think about. Would be a great addition to an already awesome plugin, IMHO.

Thanks again.

**Comment by lifepillar** [comment]
Asynchronous completion is not a goal. It would make µcomplete significantly more complex, so it is at odds with µcomplete's minimalist philosophy. It also is at odds with µcomplete's approach (fallback completion), which by its nature is sequential.

Besides, in my limited experience with asynchronous completion plugins, I did not notice such a difference (performance-wise) compared to built-in completion to be impressed. On the contrary, I have always found built-in completion much more predictable and well-behaved than any other plugin.

But that's my experience, and of course yours may be totally different. Fortunately, there is no lack of asynchronous completion plugins :)

**Comment by damnskippy** [comment]
Agreed - please feel free to close this request.
