### ISSUE TITLE
can_complete for omni is too restrictive for python

### ISSUE THREAD

**Issue by mtikekar** [lifepillar/vim-mucomplete#85]
With vim's built-in omnifunc=python3complete#Complete for python, I can type into the buffer something like: `sys.<C-x><C-o>` and I see a list of completions. However, it doesn't show up with `sys.<Tab>`. This happens because `.` is not in iskeyword.

Perhaps the default checks for omnifunc and completefunc should run call them once with findstart=1 and check if return value is negative?

**Comment by lifepillar** [comment]
If you do not want to add `.` to `iskeyword`, you may customise `mucomplete#can_complete` for Python. For example:

```vim
let mucomplete#can_complete = { }
let mucomplete#can_complete.python = { 'omni' : { t -> t =~ '\m\%(\k\k\|\.\)$' } } 
```

**Comment by lifepillar** [comment]
There may be some problems with `python3complete#Complete`. Turn off µcomplete and type:

```
import sys<c-x><c-o>
```

The pop-up menu appears showing one entry with `sys` (in the wrong position, btw: it should appear under the text, but it's displaced to the right). If that entry is selected, then a `.` is inserted (why?); If you type a `.` instead, the menu is not dismissed (why?). That does not seem a correct way to perform completion.

Besides, if I type:

```
import sys.<c-x><c-o>
```

the pop-up menu correctly shows several completions, among which two (in my system) starting with `a` (`abiflags` and `api_version`). But if I type:

```
import sys.a<c-x><c-o>
```

or even

```
import sys.ab<c-x><c-o>
```

there is no completion (why?). Again, this does not look correct to me.

**Comment by mtikekar** [comment]
It is strange indeed. I don't really use `python3complete#Complete`; I used it here only to make the bug easily reproducible.

**Comment by lifepillar** [comment]
If the problem is only that omni-completion is not triggered after a dot, that may be fixed as explained above (add `.` to `iskeyword` or use a custom activation condition matching a dot). Does that solve your issue?

I might include the latter solution in MUcomplete, but with the current Python omni-completion that would not work too well.

**Comment by mtikekar** [comment]
I would prefer the custom activation condition (I've gotten used to `.` not being a keyword.) I do wonder if this is going to be a problem for other languages too. Many of them use `.` for accessing members of structs, classes, etc.

**Comment by stefanos82** [comment]
I had the same issue with Python and due to its [off-side rule](https://en.wikipedia.org/wiki/Off-side_rule), I had to map a different set of keys to work without the tab key in order to use the auto-completion.

Another issue I have noticed with μcomplete is that it does not auto-complete inside double-quotes.

Is this normal?

**Comment by lifepillar** [comment]
>Another issue I have noticed with μcomplete is that it does not auto-complete inside double-quotes. Is this normal?

**Comment by lifepillar** [comment]
>I had the same issue with Python and due to its off-side rule, I had to map a different set of keys to work without the tab key in order to use the auto-completion.

Usually, when Tab is pressed and there are only spaces in front of the cursor, a normal tab character should be inserted. Maybe, you can open a new issue explaining with a reproducible example why the default behaviour does not work for you in Python.

**Comment by lifepillar** [comment]
I have added a custom activation pattern for omni-completion in Python buffers. Now you should be able to type `import sys.<tab>` and see the completions.

**Comment by stefanos82** [comment]
Cool!

Cheers @lifepillar :+1:
