### ISSUE TITLE
Does mucomplete support repeat operator?

### ISSUE THREAD

**Issue by jordwalke** [lifepillar/vim-mucomplete#86]
Usually completion plugins break repeat `.`. So if you `cw` and then type half of the replacement word, hitting enter/tab to replace the rest of the word, then if you use `.` it won't insert the full word you just replaced somewhere else. Plugins usually use something like [repeat.vim](https://github.com/tpope/vim-repeat) to solve this. How does `mucomplete` handle this?

**Comment by lifepillar** [comment]
That should work as expected in all circumstances. In the specific example you mention, typing `.` would insert the completed word, not just what you typed. MUcomplete does not need repeat.vim, but as far as I can tell (I use repeat.vim) is fully compatible with it.

**Comment by lifepillar** [comment]
And to answer your last question, µcomplete does absolutely nothing to make that work: all the merit belongs to Vim :)

**Comment by lifepillar** [comment]
I assume that your question is answered. Feel free to re-open is you need further clarifications!
