### ISSUE TITLE
Changing color of the popup menu

### ISSUE THREAD

**Issue by cSchubes** [lifepillar/vim-mucomplete#88]
First of all, thanks so much for mucomplete. It's solved a lot of my problems.

However, currently the popup menu looks terrible - a bright pink background over dark text. I have scoured the internet and attempted many things to no avail. I didn't see anything in the mucomplete.txt file regarding color customization.

So, is it possible to customize the colors mucomplete uses?

**Comment by lifepillar** [comment]
MUcomplete uses whatever colors are configured by Vim or the user. So, changing the colors of the pop-up menu is not a µcomplete's task. Either install a colorscheme or change the relevant highlight group definitions yourself. You may want to read about `:help :highlight` and, in particular, the `Pmenu`, `PmenuSel`, `PmenuSbar`, and `PmenuThumb` highlight groups.

**Comment by cSchubes** [comment]
thank you!! I was trying to set the Pmenu colors using just _hi_ last night, and I suppose that was the issue. Using _highlight_ fixed it.

**Comment by lifepillar** [comment]
For the record, `:hi` and `:highlight` are exactly the same command, so, it was likely something else. Anyway, good to know that you have fixed your issue!
