### ISSUE TITLE
Completion method cycling working incorrectly in special situation

### ISSUE THREAD

**Issue by markwu** [lifepillar/vim-mucomplete#89]
Here comes with my minimal vimrc to reproduce this bug.

```vim
set nocompatible
filetype off

execute 'source ~/.vim/bundle/vim-plug/plug.vim'
call plug#begin('~/.vim/bundle/')

Plug 'junegunn/vim-plug'

" Put your bundle below here
Plug 'lifepillar/vim-mucomplete'
" Put your bundle above here

call plug#end()

syntax on
filetype plugin indent on

" Put your plugin settings below here
set completeopt-=preview
set completeopt+=menu,menuone,noinsert,noselect
set shortmess+=c

inoremap <silent> <Plug>(MUcompleteFwdKey) <Right>
imap <Right> <Plug>(MUcompleteCycFwd)
inoremap <silent> <Plug>(MUcompleteBwdKey) <Left>
imap <Left> <Plug>(MUcompleteCycBwd)

let g:mucomplete#enable_auto_at_startup = 1

let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['path', 'omni', 'keyn', 'dict', 'ulti']
" Put your plugin settings above here
```

You can follow the instructions to reproduce this bug:
1. Use my minimal vimrc
2. Open vim, and entering insert mode
3. press `<right>` key
4. you will see the following key mapping show on your vim
![2018-03-04 12 43 22](https://user-images.githubusercontent.com/196861/36936829-207cec28-1f45-11e8-9309-50b6ddc57b3c.png)
5. press `<right>` key, again. There is nothing happened (This is the right behavior).

if you type something first in step 4, for example "aabb", then press `<right>`, there is nothing happened (This is the right behavior).

I tested in Macvim and Neovim, all of them have the same issue.

My systems:
Mac OSX 10.13.3
Macvim 8.0.1555
Neovim 0.2.3-768

Hope these information enough for you to find out the problems.

**Comment by lifepillar** [comment]
Thanks for the report! Plugs for cycling keys for defined lazily. I have moved those definitions in the plugin file. This should fix your issue.

**Comment by markwu** [comment]
Thanks, I confirmed this bug fixed.
