### ISSUE TITLE
Question: Does μcomplete always scan for header files before auto-completion?

### ISSUE THREAD

**Issue by stefanos82** [lifepillar/vim-mucomplete#90]
As the title says, this is the behavior I have only with C and C++ languages.

Every time I press the `tab` key, it starts scanning all my directories to find what I'm trying to auto-complete.

Isn't there a way to cache the results so it can fetch results faster?

An SQLite database would be really awesome for caching.

**Comment by lifepillar** [comment]
Are you using the default completion chain? If not, what is the output of the following commands?

```vim
:echo b:mucomplete_chain
:echo g:mucomplete#chains
```

**Comment by stefanos82** [comment]
Yes, I'm using the following:
```vim
let g:mucomplete#chains = { 'default': ['omni', 'defs', 'keyn', 'incl'] }
```

**Comment by lifepillar** [comment]
The `defs` and `'incl'` completion methods both scan included files (see `:h i_CTRL-X_CTRL-D` and `:h i_CTRL-X_CTRL-I`). Try removing one of them at a time. If the problem still persists, the culprit may be the omni-completion function (`'omni'`).

To alleviate your issue, you should give the slowest completion methods the lowest priority. In your case, putting `'keyn'` in front of `'defs'` might help. Depending on your use case, you might also define a custom activation condition for those methods, more restrictive than the default one (so, they would be called less often). See `g:mucomplete#can_complete`.

Regarding the caching: MUcomplete uses, but has no control over those completion methods, as they are built-in in Vim.

**Comment by stefanos82** [comment]
By removing `incl`, the auto-completion stops as a whole; that is, either by using tab key or by using `<C-x><C-o>`.

With `incl` it parses it with one core 100% CPU usage and takes a long time to complete, because it scans recursively.

![image](https://user-images.githubusercontent.com/1777466/37468936-cd8b6144-286c-11e8-9416-241b0ba122f5.png)

**Comment by lifepillar** [comment]
Turn off µcomplete and use `<C-x><C-i>`. Do you experience the same CPU usage and slowness? Then, that depends on Vim.

**Comment by stefanos82** [comment]
Well, my CPU usage is the same, but my scanning feels like it had double its speed.

I get my result in half time than its previous behavior.

**Comment by lifepillar** [comment]
>I get my result in half time than its previous behavior.

If you remove `'defs'`, but keep `'incl'`, does µcomplete become approximately as fast as `<c-x><c-i>`? My guess is that, with your configuration, Vim first searches for definitions/macros (also in included files), then the search fails and it tries to search keywords (also in included files). That would explain why it takes 2x as much.

Also, how about defining `set complete=di`, then removing both `'defs'` and `'incl'` and adding `'c-p'` instead?

**Comment by stefanos82** [comment]
What is `complete=di` supposed to do?

I get this error message if I add `set complete=di`:
```vim
E535: Illegal character after <d>: complete=di
```

**Comment by stefanos82** [comment]
> If you remove 'defs', but keep 'incl', does µcomplete become approximately as fast as <c-x><c-i>? My guess is that, with your configuration, Vim first searches for definitions/macros (also in included files), then the search fails and it tries to search keywords (also in included files). That would explain why it takes 2x as much.

Yes, it behaves faster now, like I use `<C-x><C-o>`.

**Comment by lifepillar** [comment]
Sorry, that should be: `set complete=d,i`. This option makes `’c-p’` search definitions/macros *and* keywords in included files, so it’s equivalent to `‘defs’` plus `‘incl’`, and possibly faster.

**Comment by stefanos82** [comment]
It's as slow as my initial performance with `defs` and `incl` included.

Anyway, I will use what I have.

The `clang_complete` plugin looks interesting. I might take a look at it at a later time.

**Comment by lifepillar** [comment]
Ok, so I am closing this, because there is nothing µcomplete can do to speed up `'defs'` and `'incl'` methods, as they just use built-in Vim functionality.

One more thing you may try is to adjust the value of the `'path'` option (see `:help 'path'`), e.g., by removing `/usr/include`, which likely contains lots of files.

**Comment by lifepillar** [comment]
Btw, in the `'path'` option you may also specify the recursion depth. For example, if you set:

```vim
set path=./**2
```
Vim will search the current directory up to two levels deep. See `:help file-searching` for the syntax. You may also use `:checkpath!` to see which included files are found and which not, given your settings.

**Comment by stefanos82** [comment]
Thank you @lifepillar for the suggestion. I already have it set like this.

Anyway, no worries; I will figure things out eventually.
