### ISSUE TITLE
Completion source on popup

### ISSUE THREAD

**Issue by bbtdev** [lifepillar/vim-mucomplete#91]
Hello,
Just wanted to stay that I tested every possible plugin and mu just ticks all the boxes for me. Nice work!

Now, is it possible to have the source of the word in the pop up, like in other plugins?

**Comment by lifepillar** [comment]
What do you mean by “source of the word”? The file where the word has been found?

**Comment by bbtdev** [comment]
if it's a tag "t" for example

**Comment by lifepillar** [comment]
This can be done only for user-defined functions. The pop-up menu for built-in completion methods (i.e., everything listed in `:help mucomplete-methods` except for `'omni'`, `'user'`, `'path'`, and `'uspl'`) cannot be modified. If you remove `c` from `'shortmess'`, you get some information about the current completion under the status line (e.g., for tags a “Scanning tags” message would appear). I find that more annoying than useful, though.

Where adding information to the pop-up menu is possible, µcomplete already does it. For example, for the `'path'` method (which is implemented by µcomplete), µcomplete shows whether each item is a file or a directory.
