### ISSUE TITLE
Word gets distorted in neovim when you type it and not choose if from popup, in ruby files

### ISSUE THREAD

**Issue by bbtdev** [lifepillar/vim-mucomplete#96]
I think the problem appeared afttter the smart-enter merge.
In vim I could not replicate behaviour, only in neovim, and not in a simple buffer, I'm opening a ruby file (test.rb)
Steps:
- star nvim with -u troubleshoot.vim below
- type _else_, enter
- type _else_, enter
 - you should see _eelse_, not _else

Could not upload gif on github, so here is the link:
https://gfycat.com/DelectableAggravatingBlackwidowspider

config
set runtimepath+=/home/bogdan/.vim/plugged/vim-mucomplete " CHANGE THIS
"set runtimepath+=/home/bogdan/.vim/plugged/vim-endwise/

```
" Optionally add additional configuration below this line
setglobal complete-=t
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['c-n']
let g:mucomplete#chains.vim = ['c-n', 'cmd']
let g:mucomplete#chains.ruby = ['c-n']
set completeopt+=noselect
let g:mucomplete#smart_enter = 0
" set completeopt+=noinsert
let g:mucomplete#always_use_completeopt = 1
let g:mucomplete#enable_auto_at_startup = 1
"set wildmenu
"set wildmode=list:longest,full
```

**Comment by lifepillar** [comment]
A difference between Vim and NeoVim is that the second `else` is re-indented before pressing Enter in NeoVim.

And I can reproduce the issue with older versions of µcomplete, so it is not a recent regression.

**Comment by lifepillar** [comment]
This is a NeoVim and endwise issue. To reproduce without µcomplete, use this `test_vimrc`:

```vim
set nocompatible
set runtimepath=$VIMRUNTIME
set runtimepath+=/home/bogdan/.vim/plugged/vim-endwise/
set completeopt+=menuone,noselect
syntax enable
filetype plugin indent on
```

Run `nvim -u test_vimrc`, edit a Ruby buffer, enter Insert mode and type:

```vim
else
els<c-n>e<cr>
```

Possibly worth reporting to endwise repository.

**Comment by lifepillar** [comment]
No, not even endwise is to blame. This is a NeoVim bug (v0.2.2). I can reproduce it without plugins. Run `nvim -u NONE -i NONE -n --noplugin`, then:

```vim
:set completeopt=menuone,noselect
:filetype indent on
:set ft=ruby
```

Type:

```
else
els<c-n>e<cr>
```

and you should still see the bug.
