### ISSUE TITLE
you do not need to map <cr> in your vimrc any longer

### ISSUE THREAD

**Issue by dylnmc** [lifepillar/vim-mucomplete#97]
I map `<cr>` myself (not related to your plugin at all). Your plugin says "[MUcomplete] NOTE: since v1.0.0, you do not need to map <cr> in your vimrc any longer." when I enter insert mode for the first time.

You make my life difficult, also, trying to interoperate with ultisnips since you make it not very easy to figure out which mappings are mapped to what keys and becase you use way too many keys. By default, you should map no keys and let the user define which functions to map, but that's another issue, if you want to take that advice, but I keep getting `<c-j> is already mapped`, `<c-l> is already mapped`, `<every key on the entire keyboard> is already mapped` \</joke>

**Comment by dylnmc** [comment]
And every time that the menu is open, I have to press `<cr>` twice in order to get one ^m …

**Comment by lifepillar** [comment]
>I map <cr> myself (not related to your plugin at all).

In that case, you need to add `<plug>(MUcompleteCR)` to your own mapping. To behave correctly, MUcomplete needs to detect when the user closes the pop-up menu by pressing Enter and that plug has that purpose.

>You make my life difficult, also, trying to interoperate with ultisnips

See `:help mucomplete-troubleshooting`. Both µcomplete and UltiSnips map CTRL-J, so one of the two mappings must be changed.

>By default, you should map no keys and let the user define which functions to map

You may put

```vim
let g:mucomplete#no_mappings = 1
```

in your `vimrc` and take care of mappings yourself. That this should be the default is debatable: most users expect µcomplete to work “out of the box”.

>I keep getting `<c-j>` is already mapped, `<c-l>` is already mapped, …

That's much better that silently overriding existing mappings :) Btw, µcomplete does not map `<c-l>`. See `:help mucomplete-mappings` for a list of mapped keys.

>every time that the menu is open, I have to press <cr> twice in order to get one ^m …

If you provide more details about your mapping and use case, I may suggest a way to fix that.

**Comment by dylnmc** [comment]
I am writing a plugin that uses analyzes the opening/closing braces, parens, and quotes on the current line when the user presses `<cr>` and then appropriately responds. So, I map an `<expr>`+*function* to `<cr>` I believe. I just don't see why you need to use `<cr>`.

Regarding the issue of mapping various key bindings by default in the prime realestate (`<tab>`, `<s-tab>`, `<c-h>`, `<c-j>`) … with a small vimrc, I am sure this works great, and I bet many users appreciate this. I don't think it's scalable, and when you start customizing vim to suit your needs, as I have been doing, then all of this overhead just causes problems.

I guess I think of it like this: you've built a house that people might want to live in, but if someone already has the blueprints for a house, they just need the plumming and circuitry to be able to complete their ideal house. However, it seems as though you don't just provide an easy way for people to use your plumming; you try your best to force all of these structures onto the user.

I just need a little plumbing—not a whole damn house.

I admire the house you've built, and I am sure many people like living in your house, but I have my own house (I would like to use `<tab>`, `<c-j>` and `<c-k>` for ultisnips.

---

Back to the issue at hand regarding `<cr>`:

* I have put this in my vimrc:

```vim
let g:mucomplete#no_mappings = 1
let g:mucomplete#no_mappings = 1
let g:mucomplete#enable_auto_at_startup = 1all
set completeopt=menu,menuone,preview,noselect
imap <expr> <down> pumvisible() ? "\<plug>(MUcompleteExtendFwd)" : "\<down>"
let g:mucomplete#no_mappings = 1
inoremap <silent> <plug>(MUcompleteFwdKey) <right>
imap <right> <plug>(MUcompleteCycFwd)
inoremap <silent> <plug>(MUcompleteBwdKey) <left>
imap <left> <plug>(MUcompleteCycBwd)
```

Now two things happen:

1. **`pumvisibile()` is `1` but no options are selected**
  - This is now where I need to press `<cr>` twice
2. **`pumvisible()` is `1` and an option is selected from the menu**
  - I can safely press `<cr>` and get a carriage return or my execute my function which (currently) only works when a paren or bracket lies directly before the cursor)

**Comment by lifepillar** [comment]
>I am writing a plugin

Even if µcomplete didn't define any mapping, you would still have issues with plenty of other plugins. The approach adopted by µcomplete is to accept that conflicts are inevitable and explain (in the documentation) how to fix such conflicts.

>I just don't see why you need to use `<cr>`.

That mapping is needed only when automatic completion is on and it has been discussed in the past (https://github.com/lifepillar/vim-mucomplete/issues/66). Making the mapping part of the plugin has been discussed as well (https://github.com/lifepillar/vim-mucomplete/issues/75).

>it seems as though you don't just provide an easy way for people to use your plumming; you try your best to force all of these structures onto the user.

I agree that plugins, as a guideline, should not define mappings. But plugins should also provide sensible defaults (i.e., those that make the majority of users, possibly the less expert ones, happy). This is not always an easy trade-off. In the case of µcomplete, I think I have made reasonable choices. For users like you, who need to tweak µcomplete for advanced uses, disabling all mappings is just a matter of adding one line to your `vimrc`.

>Back to the issue at hand regarding `<cr>`:

You need to press Enter twice because you have suppressed all mappings, including `<cr>`. If you suppress all mappings, then it is your responsibility to provide suitable definitions. In this specific case, you need to add this (or a definition to the same effect) to your `vimrc`:

```vim
imap <cr> <plug>(MUcompleteCR)
```

and similar definitions for `<c-e>` and `<c-y>`. Since you are using µcomplete with a plugin that also maps `<cr>`, you need a different mapping, of course, which includes the definition for your plugin.

>I do not want to add <plug>(MUcompleteCR) to the mapping in my plugin …

Sure. I thought it was for your `vimrc`. In `:help mucomplete-compatibility` there are a couple of examples of settings for making µcomplete compatible with other plugins that map `<cr>`: you may find those examples useful.

**Comment by dylnmc** [comment]
Alright!

I will take a look at this when I get home, and for now I will close the issue.

I suppose I have been a little impetuous and unthoughtful about how I have been approaching this. I should have read through more thouroughly.

So, thanks for putting up with me, and I'll try it out later.

Thank you

**Comment by lifepillar** [comment]
I wish I could dispose of some mappings. If you have an idea on how to detect how a pop-up menu is closed (e.g., with `<cr>` vs another key) without using mappings, let me know!

**Comment by dylnmc** [comment]
I was not going to reopen this quite yet, but I might as well. While I have been quite busy with school (exams approach!), work, etc, I also just tried to figure out how to get mucomplete to work with my setup so that I can continue to be productive at work and coding for other things.

## setup

For now I decided to merely use the AutoPair that is list in your help doc, since I am sick of hacking things together while I am quite busy. I have this in my vimrc:

```vim
" autopairs
let g:AutoPairsMapCR = 0
" let g:mucomplete#smart_enter = 0
imap <expr> <plug>MyCR pumvisible() ? "\<plug>(MUcompleteCR)\<plug>AutoPairsReturn" : "\<plug>AutoPairsReturn"
imap <cr> <Plug>MyCR


set completeopt=menu,menuone,preview,noselect
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {
	\ 'default': [ 'keyp', 'c-p', 'ulti', 'omni', 'cmd' ],
	\ 'html': [ 'omni', 'keyp', 'c-p', 'path', 'ulti' , 'cmd'],
	\ 'css': [ 'keyp', 'c-p', 'ulti' , 'cmd']
\}
```

I additionally tried to use exactly what you have in the help doc, but I get the same result.

## What happens?

I am unable to insert `<cr>` in insert mode.

## no configuration

If I only have this:

```vim
set completeopt=menu,menuone,preview,noselect
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {
	\ 'default': [ 'keyp', 'c-p', 'ulti', 'omni', 'cmd' ],
	\ 'html': [ 'omni', 'keyp', 'c-p', 'path', 'ulti' , 'cmd'],
	\ 'css': [ 'keyp', 'c-p', 'ulti' , 'cmd']
\}
```

Then when I use `<cr>` in insert mode and `pumvisible()`, the text I have typed disappears as though I have issued `<c-y>` (to select the current option which doesn't exist because I have `completeopt+=noselect`, which makes mucomplete delete all the text I have typed).

## conclusion

It seems as though everything I try, I get a very undesirable result—some more undesirable than others.

Do you have any tips on how to interpolate your plugin? I know you have a section in the help about it, but it doesn't seem to help.

**Comment by dylnmc** [comment]
The issue is `noselect`. I wish to use mucomplete with `noinsert`.

This setup works:

```vim
" autopairs
let g:AutoPairsMapCR = 0
imap <Plug>MyCR <Plug>(MUcompleteCR)<Plug>AutoPairsReturn
imap <cr> <Plug>MyCR

set completeopt=menu,menuone,preview,noinsert
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {
	\ 'default': [ 'keyp', 'c-p', 'ulti', 'omni', 'cmd' ],
	\ 'html': [ 'omni', 'keyp', 'c-p', 'path', 'ulti' , 'cmd'],
	\ 'css': [ 'keyp', 'c-p', 'ulti' , 'cmd']
\}
```

But I do not like `noinsert` and would prefer `noselect` but whenever I set `noselect` with completeopt, then it deletes the text I type when I press <kbd>Return</kbd> and have not yet selected any options from  PUM.

**Comment by dylnmc** [comment]
Ahhh .. Yes I finally got it .. very strange and thank you for helping me work this kink out so that I can be more productive at work and home.

For reference:

```vim
" autopairs
let g:AutoPairsMapCR = 0
let g:mucomplete#smart_enter = 1
" shutup mucomplete and autopairs plugs
let g:AutoPairsMapCR = 0
imap <Plug>MyCR <Plug>(MUcompleteCR)<Plug>AutoPairsReturn
imap <cr> <Plug>MyCR

set completeopt=menu,preview,noselect
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {
	\ 'default': [ 'keyn', 'c-n', 'ulti', 'omni', 'cmd' ],
	\ 'html': [ 'omni', 'keyn', 'c-n', 'path', 'ulti' , 'cmd'],
	\ 'css': [ 'keyn', 'c-n', 'ulti' , 'cmd']
\}
```

Thank you

**Comment by dylnmc** [comment]
Also, the links above where you can use

```vim
let g:mucomplete#popup_direction = { 'keyn': -1, 'c-n': -1 }
```

is nifty; thanks

**Comment by lifepillar** [comment]
The current master (past v1.0.0) does not map `<cr>` any longer. @dylnmc This should (partially) relieve your pain!
