### ISSUE TITLE
Compatibility with Ultisnips and AutoPairs

### ISSUE THREAD

**Issue by crdueck** [lifepillar/vim-mucomplete#98]
Hi!

I had accidentally submitted this issue before I finished writing the body, then noticed this [recent issue](https://github.com/lifepillar/vim-mucomplete/issues/97) was very similar to my question.

Anyways, following the conversation in that issue I managed to get all 3 plugins working nicely (mu-complete, ultisnips and auto-pairs) but I'd appreciate your feedback if there's a better/cleaner way to do this. I think you also use these same plugins, so I wonder how does your configuration look?

My goal is to have auto-pairs handle insert-mode `<CR>` via `<Plug>AutoPairsReturn`, but also have ultisnips snippet-expansion triggered by `<CR>` when `pumvisible` is true. As I understand it, mu-complete also needs to hook into `<CR>` to know when the popup menu is exited.

Here's the relevant bits from my `vimrc`:

```
" auto-pairs
let g:AutoPairsMapCR = 0

" mu-complete
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {
  \ 'default':  ['ulti', 'omni', 'keyp'],
  \ 'markdown': ['ulti', 'dict', 'keyp'],
  \ }

imap <Plug>OmniEnter <Plug>(MUcompleteCR)<Plug>AutoPairsReturn
imap <CR> <Plug>OmniEnter

" ultisnips
let g:UltiSnipsExpandTrigger = "<nop>"
imap <expr> <CR> pumvisible() ? "<C-R>=UltiSnips#ExpandSnippetOrJump()<CR>" : "\<Plug>OmniEnter"
```

Please feel free to close this issue again if there's no improvements to be made, but I figured I'd post my configuration in case it helps someone who's trying to create a similar setup.

**Comment by lifepillar** [comment]
I don't use UltiSnips or AutoPairs, but your snippet looks good to me (`imap <cr> <plug>OmniEnter` seems redundant). I would rewrite it as follows (omitting µcomplete's settings):

```vim
let g:AutoPairsMapCR = 0
let g:UltiSnipsExpandTrigger = "<nop>"

fun! OmniCR()
  return pumvisible()
        \ ? "\<c-r>=UltiSnips#ExpandSnippetOrJump()\<cr>"
        \ : "\<plug>(MUcompleteCR)\<plug>AutoPairsReturn"
endf

imap <expr> <plug>OmniCR OmniCR()
imap <cr> <plug>OmniCR
```

I would use `<plug>OmniCR` instead of `<plug>OmniEnter`: should you ever want to add endwise to the mix,  a plug ending with `CR` would be recognised by endwise and dealt with correctly without further settings.

**Comment by crdueck** [comment]
Ah, I thought I had read in another issue that you at least used Ultisnips, but I guess I'm mistaken.  

That is certainly cleaner that what I had originally. Since I'm not using endwise (for now at least) I can remove the redundant `<plug>OmniCR` and just have `imap <expr> <cr> OmniCR()`

Thanks for your suggestions, and for writing this great plugin!
