### ISSUE TITLE
Incorrect behavior if the indent is adjusted while popup is open

### ISSUE THREAD

**Issue by mrbiggfoot** [lifepillar/vim-mucomplete#99]
Here is the scenario, for VimL:
1. Say, you have this function definition and you type "en" (endfunction) when the completion popup appears:
```
function F()
  en
```
2. Then you type "d", and the whole word "end" gets aligned to "function", while the completion popup is still open. So you now have this:
```
function F()
end
```
3. Start selecting completion candidates. They now place the word at the old position, so if I select "endfunction", I get this:
```
function F()
enendfunction
```

See the gif here: https://giphy.com/gifs/mucomplete-bug-1wnFYNzXFi8WkJHTGZ/fullscreen
I apologize for the quality, but it's possible to understand what's going on. Thanks for the great plugin! :)

**Comment by lifepillar** [comment]
I cannot reproduce it after setting the filetype to `vim`. Can you please edit `troubleshooting_vimrc.vim` (the file is in the plugin) then try with `vim -u troubleshooting_vimrc.vim`? Then post the relevant settings used to reproduce the issue.

**Comment by mrbiggfoot** [comment]
The problem happens on `neovim` for me, the most current version built from source (commit 4744142fad9209a1adaa190b9bf16ddcbcb67ca9). I have not checked the other versions, but I update neovim regularly and this problem has always existed for me.

I can reproduce it with this `vimrc`:
```
" vim: foldmethod=marker foldenable
" Do not change this section {{{
set nocompatible
set nobackup noswapfile
if has('persistent_undo')
  set noundofile
endif
if has('writebackup')
  set nowritebackup
endif
if has('viminfo')
  set viminfo=""
endif
if has('packages')
  set packpath=
endif
set runtimepath=$VIMRUNTIME
set completeopt=menuone
if has('patch-7.4.775')
  if !has('patch-7.4.784')
    echomsg "WARNING: noinsert and noselect may not work properly with this version of Vim."
  endif
  set completeopt+=noinsert
else
  echomsg "Automatic completion is not available in this version of Vim."
endif
set showmode
if has('patch-7.4.314')
  set shortmess-=c
endif
syntax enable
filetype plugin indent on
" }}}

set runtimepath+=~/neovim/plugged/vim-mucomplete/

" Optionally add additional configuration below this line
let g:mucomplete#enable_auto_at_startup = 1
let g:mucomplete#chains = {}
let g:mucomplete#chains.default = ['path', 'c-n', 'dict', 'uspl']
set complete=.,w,b,u
set autoindent smartindent
```

...and this file, let's call it "a.vim":
```
function enhanced
endfunction

function F()
```

The sequence is:
1. `nvim -u ./troubleshooting_vimrc.vim a.vim`
2. Type this sequence:
* `G` - cursor is now at 4,1
* `o` - cursor is now at 5,2-9
* `en` - at this point completion popup appears
<img width="201" alt="screen shot 2018-04-30 at 2 22 00 pm" src="https://user-images.githubusercontent.com/12175496/39450972-ee692a0c-4c81-11e8-9b1d-00f4551c65a3.png">

* `h` - at this point only one completion candidate "enhanced" remains
<img width="189" alt="screen shot 2018-04-30 at 2 22 52 pm" src="https://user-images.githubusercontent.com/12175496/39450994-048dd67a-4c82-11e8-80cc-d21cb0dccebb.png">

* `<BS>` - to delete the last "h", so the completion popup shows candidates for "en"
<img width="191" alt="screen shot 2018-04-30 at 2 23 56 pm" src="https://user-images.githubusercontent.com/12175496/39451045-2bd691d6-4c82-11e8-8d9e-efde92bbb161.png">

* `d` - now the word "end" gets moved to the beginning of the line, the cursor is at 5,5-12
<img width="180" alt="screen shot 2018-04-30 at 2 24 34 pm" src="https://user-images.githubusercontent.com/12175496/39451075-3d52b57a-4c82-11e8-991e-9fb3771d7911.png">

* `<TAB>` - the candidate list has only "endfunction" and the buffer has "eendfunction"
<img width="254" alt="screen shot 2018-04-30 at 2 18 56 pm" src="https://user-images.githubusercontent.com/12175496/39450830-7e05e192-4c81-11e8-8766-024c2a0bcdbc.png">

* `<CR>` - the "eendfunction" remains.

**Comment by lifepillar** [comment]
That is a NeoVim issue, possibly related to https://github.com/lifepillar/vim-mucomplete/issues/96. Using your vimrc, you can reproduce it without MUcomplete as follows (I am using NeoVim v0.2.2):

1. `nvim -u ./troubleshooting_vimrc.vim a.vim`
2. `MUcompleteAutoOff`
3. `Goen<c-n>d<c-n>`

**Comment by mrbiggfoot** [comment]
Ok, thanks for looking into it! I will report it to NeoVim.
